FROM debian

RUN adduser devel
RUN adduser devel staff

RUN apt-get update
RUN apt-get -y upgrade
RUN apt-get -y install git

USER devel
WORKDIR /home/devel

RUN mkdir src

WORKDIR src

USER root

COPY debian-packages.txt .

RUN apt-get -y install $(cat debian-packages.txt) debhelper-compat eatmydata git-buildpackage

USER devel

