<?xml version="1.0"?>
<xsl:stylesheet version="1.0"
    xmlns:cx='http://johannes-willkomm.de/xml/code-xml/'
    xmlns:ca='http://johannes-willkomm.de/xml/code-xml/attributes/'
    xmlns:xsl="http://www.w3.org/1999/XSL/Transform">

  <xsl:include href="reproduce.xsl"/>

  <xsl:output method="text" encoding="latin1"/>

</xsl:stylesheet>
<!-- $Id: reproduce-latin1.xsl 75 2014-10-24 16:21:34Z johannes.willkomm@googlemail.com $ -->
