// -*- javascript -*- 
// This file has been automatically generated by 
// gennc.sh / gennc-js.xsl
// from definition file ../src/xml/assoc.ncd.xml.

if (typeof window == "undefined") {
  var ENUM = require('./gennc-common.js')
}
ENUM.createParserAssoc = function() {
 var k=0
 var prefix='ASSOC_'
 var index={
 NONE: (k=0),
 LEFT: (k=1),
 RIGHT: (k=2),
 }
 var comments
 var res=ENUM.createENUM(index, prefix, comments)
 return res
}
ENUM.ParserAssoc=ENUM.createParserAssoc()
if (typeof window == 'undefined') {
 for (k in ENUM) {
  exports[k]=ENUM[k]
 }
}
  