// -*- javascript -*- 
// This file has been automatically generated by 
// gennc.sh $Id: gennc-js.xsl 76 2016-01-04 22:04:05Z jwillkomm $
// from definition file ../src/xml/assoc.ncd.xml.

var ENUM = require('./gennc-common.js')
ENUM.createParserAssoc = function() {
 var k=0
 var prefix='ASSOC_'
 var index={
 NONE: (k=0),
 LEFT: ++k,
 RIGHT: ++k,
 }
 var comments
 var res=ENUM.createENUM(index, prefix, comments)
 return res
}
ENUM.ParserAssoc=ENUM.createParserAssoc()
if (typeof window == 'undefined') {
 for (k in ENUM) {
  exports[k]=ENUM[k]
 }
}
  