// -*- javascript -*- 
// This file has been automatically generated by 
// gennc.sh / gennc-js.xsl
// from definition file ../src/xml/modes.ncd.xml.

if (typeof window == "undefined") {
  var ENUM = require('./gennc-common.js')
}
ENUM.createParserMode = function() {
 var k=0
 var prefix='MODE_'
 var index={
 IGNORE: (k=1),
 ITEM: (k=2),
 UNARY: (k=3),
 POSTFIX: (k=4),
 BINARY: (k=5),
 UNARY_BINARY: (k=6),
 LINE_COMMENT: (k=7),
 PAREN: (k=32),
 BLOCK_COMMENT: (k=64),
 }
 var comments
 var res=ENUM.createENUM(index, prefix, comments)
 return res
}
ENUM.ParserMode=ENUM.createParserMode()
if (typeof window == 'undefined') {
 for (k in ENUM) {
  exports[k]=ENUM[k]
 }
}
  