#! /bin/bash

NODE=nodejs

if ! test -x $(which $NODE); then 
   NODE=node
fi

srcdir=$(dirname $BASH_SOURCE)

main_src=p2x-main.js

if test -r $srcdir/$main_src; then
    file=$srcdir/$main_src
elif test -r $srcdir/../share/p2x/js/$main_src; then
    file=$srcdir/../share/p2x/js/p2x-main.js
fi

$NODE $file $*
