#! /bin/bash

NODE=nodejs

if ! test -x $(which $NODE); then 
   NODE=node
fi

srcdir=$(dirname $BASH_SOURCE)

if test -r $srcdir/test-read-cnf.js; then
    file=$srcdir/test-read-cnf.js
elif test -r $srcdir/../share/p2x/js/test-read-cnf.js; then
    file=$srcdir/../share/p2x/js/test-read-cnf.js
fi

$NODE $file $*
