// -*- c++ -*- 
// This file has been automatically generated by 
// gennc.sh $Id: gennc.xsl 50 2015-04-08 12:45:49Z jwillkomm $ 
// from definition file xml/assoc.ncd.xml. Class mode is false.
#ifndef gennc_funcParserAssoc__hh
#define gennc_funcParserAssoc__hh

    char const *getParserAssocName(unsigned long c);
    char const *getParserAssocComment(unsigned long c);
    ParserAssoc getParserAssocValue(char const *name, int *res = 0);
    
    inline ParserAssoc getParserAssocValue(std::string const &t, int *res = 0) {
       return getParserAssocValue(t.c_str(), res);
    }
    
    unsigned long getNumParserAssoc();
    ParserAssoc getParserAssoc(int which);
    
    inline std::ostream &operator << (std::ostream &out, ParserAssoc t) {
       out << getParserAssocName(t);
       return out;
    }
    #endif

