// -*- c++ -*- 
// This file has been automatically generated by
// gennc.sh 47
// from definition file xml/assoc.ncd.xml.
#ifndef gennc_enumParserAssoc__hh
#define gennc_enumParserAssoc__hh

    enum ParserAssoc {
ASSOC_NONE,
ASSOC_LEFT,
ASSOC_RIGHT
    };
  #endif

