// -*- c++ -*- 
// This file has been automatically generated by
// gennc.sh $Id: gennc.xsl 110 2018-10-09 15:02:12Z jwillkomm $
// from definition file xml/assoc.ncd.xml. Class mode is false.

#include <string>
#include <cstring>
#include <iostream>
#include <cstdlib>
#include <stdio.h>
#include "assoc.ncd.enum.hh"
#include "assoc.ncd.hh"
    char const *getParserAssocName(unsigned long c) {
      switch(c) { 
       case ASSOC_NONE: return "NONE";
       case ASSOC_LEFT: return "LEFT";
       case ASSOC_RIGHT: return "RIGHT";
        default: break;
      }
      return "unknown value in enumeration ParserAssoc";
    }
    char const *getParserAssocComment(unsigned long c) {
      switch(c) { 
       case ASSOC_NONE: return "";
       case ASSOC_LEFT: return "";
       case ASSOC_RIGHT: return "";
        default: break;
      }
      return "unknown value in enumeration ParserAssoc";
    }
    ParserAssoc getParserAssocValue(char const *name, int *res) {
       if (res) *res = 0;
       if (name == 0 || *name == 0) { return ASSOC_NONE;
       } else if (strcasecmp("NONE", name) == 0
          || strcasecmp("ASSOC_NONE", name) == 0) {
          return ASSOC_NONE;
       } else if (strcasecmp("LEFT", name) == 0
          || strcasecmp("ASSOC_LEFT", name) == 0) {
          return ASSOC_LEFT;
       } else if (strcasecmp("RIGHT", name) == 0
          || strcasecmp("ASSOC_RIGHT", name) == 0) {
          return ASSOC_RIGHT;
       } else {
          if (! res) {
            fprintf(stderr, "error: unknown %s constant named `%s'\n",
              "ParserAssoc", name);
          } else {
             *res = 1;
          }
          return ASSOC_NONE;
       }
    }
    unsigned long getNumParserAssoc() {
      return 3;
    }
    ParserAssoc getParserAssoc(int which) {
      switch(which) { 
       case 0: return ASSOC_NONE;
       case 1: return ASSOC_LEFT;
       case 2: return ASSOC_RIGHT;
       default: break;
      }
      fprintf(stderr, "error: ParserAssoc constant index %d out of range\n",
              which);
      return ASSOC_NONE;
    }
    
