// -*- c++ -*- 
// This file has been automatically generated by
// gennc.sh 47
// from definition file xml/assoc.ncd.xml.

#include <string>
#include <cstring>
#include <iostream>
#include <cstdlib>
#include <stdio.h>
#include <stdint.h>
#include <stddef.h>


#define ParserAssoc__prefixLen 6


typedef uint8_t ParserAssoc_IndexT;



static int ParserAssoc__compnames(const void *m1, const void *m2) {
  char const * const * mi1 = (char const * const *) m1;
  char const * const * mi2 = (char const * const *) m2;
  return strcasecmp(*mi1, *mi2);
}

static  char const* const ParserAssoc__names[ParserAssoc__numItems + 1] = {
  "LEFT", "NONE", "RIGHT"
};

static ParserAssoc_IndexT const ParserAssoc__indexNames[ParserAssoc__numItems] = {
  1, 0, 2
};

static ParserAssoc_IndexT const ParserAssoc__invNames[ParserAssoc__numItems + 1] = {
  1, 0, 2, ParserAssoc__numItems
};

size_t ParserAssoc_getLength() {
  return ParserAssoc__numItems;
}

char const* ParserAssoc_getPrefix() {
  return ParserAssoc__prefix;
}

ParserAssoc_T ParserAssoc_getIthCode(int i) {
  if (i >= 0 && i < ParserAssoc__numItems) {

    return (ParserAssoc_T) i;

  }
  return (ParserAssoc_T) -1;
}

char const* ParserAssoc_getIthName(int i) {
  if (i >= 0 && i < ParserAssoc__numItems) {
    return ParserAssoc__names[ParserAssoc__invNames[i]];
  }
  return 0;
}

char const* ParserAssoc_getIthComment(int) {

  return 0;
}

int ParserAssoc_isCode(ParserAssoc_T n) {
  return ParserAssoc_getName(n) != 0;
}

static ParserAssoc_IndexT ParserAssoc__getCodeIndex(ParserAssoc_T code) {
  if ((unsigned) code < ParserAssoc__numItems) return code;
  return ParserAssoc__numItems;
}

char const *ParserAssoc_getName(ParserAssoc_T code) {
  return ParserAssoc__names[ParserAssoc__invNames[ParserAssoc__getCodeIndex(code)]];
}

ParserAssoc_T ParserAssoc_getCode(char const *name, int* res) {
  char const* const* found = (char const* const*)  bsearch(&name, ParserAssoc__names, ParserAssoc__numItems, sizeof(char const*), &ParserAssoc__compnames);
  if (res) *res = found == 0;
  if (found) {
    ParserAssoc_IndexT n = found - ParserAssoc__names;
    return (ParserAssoc_T) ParserAssoc__indexNames[n];
  }
  return (ParserAssoc_T) -1;
}

ParserAssoc_T ParserAssoc_getCodeFullName(char const *name, int* res) {
  return ParserAssoc_getCode(name + ParserAssoc__prefixLen, res);
}

char const *ParserAssoc_getComment(ParserAssoc_T) {

  return 0;

}


char const *getParserAssocName(ParserAssoc_T c) {
  return ParserAssoc_getName(c);
}

char const *getParserAssocComment(ParserAssoc_T c) {
  return ParserAssoc_getComment(c);
}

ParserAssoc_T getParserAssocValue(char const *name, int *res) {
   if (strncasecmp(name, ParserAssoc__prefix, ParserAssoc__prefixLen) == 0) {
     return ParserAssoc_getCodeFullName(name, res);
   } else {
     return ParserAssoc_getCode(name, res);
   }
}

size_t getNumParserAssoc() {
  return ParserAssoc_getLength();
}

ParserAssoc_T getParserAssoc(int which) {
  return ParserAssoc_getIthCode(which);
}

