// -*- c++ -*- 
// This file has been automatically generated by 
// gennc.sh $Id: gennc.xsl 50 2015-04-08 12:45:49Z jwillkomm $ 
// from definition file xml/assoc.ncd.xml. Class mode is false.
#ifndef gennc_enumParserAssoc__hh
#define gennc_enumParserAssoc__hh

    enum ParserAssoc {
ASSOC_NONE = 0, 
ASSOC_LEFT, 
ASSOC_RIGHT
    };
  #endif

