// -*- c++ -*- 
// This file has been automatically generated by 
// gennc.sh $Id: gennc.xsl 31 2013-11-07 18:56:43Z jwillkomm $ 
// from definition file xml/assoc.ncd.xml. Class mode is false.

#include <string>
#include <cstring>
#include <iostream>
#include "assoc.ncd.enum.hh"
#include "assoc.ncd.hh"
    char const *getParserAssocName(unsigned long c) {
      switch(c) { 
       case ASSOC_NONE: return "NONE";
       case ASSOC_LEFT: return "LEFT";
       case ASSOC_RIGHT: return "RIGHT"; 
        default: break;
      }
      return "unknown value in enumeration ParserAssoc";
    }
    char const *getParserAssocComment(unsigned long c) {
      switch(c) { 
       case ASSOC_NONE: return "";
       case ASSOC_LEFT: return "";
       case ASSOC_RIGHT: return ""; 
        default: break;
      }
      return "unknown value in enumeration ParserAssoc";
    }
    ParserAssoc getParserAssocValue(char const *name, int *res) {
       if (res) *res = 0;
       if (name == 0 or *name == 0) { return ASSOC_NONE; 
       } else if (strcasecmp("NONE", name) == 0
          or strcasecmp("ASSOC_NONE", name) == 0) {
          return ASSOC_NONE; 
       } else if (strcasecmp("LEFT", name) == 0
          or strcasecmp("ASSOC_LEFT", name) == 0) {
          return ASSOC_LEFT; 
       } else if (strcasecmp("RIGHT", name) == 0
          or strcasecmp("ASSOC_RIGHT", name) == 0) {
          return ASSOC_RIGHT;  
       } else {
          if (not res) {
             std::cerr << "error: unknown ParserAssoc constant named `" << name << "'\n";
          } else {
             *res = 1;
          }
          return ASSOC_NONE;
       }
    }
    unsigned long getNumParserAssoc() {
      return 3;
    }
    ParserAssoc getParserAssoc(int which) {
      switch(which) { 
       case 0: return ASSOC_NONE;
       case 1: return ASSOC_LEFT;
       case 2: return ASSOC_RIGHT; 
       default: break;
      }
      std::cerr << "error: ParserAssoc constant index " << which << " out of range\n";
      return ASSOC_NONE;
    }
    
