// -*- c++ -*- 
// This file has been automatically generated by
// gennc.sh 47
// from definition file xml/assoc.ncd.xml.
#ifndef gennc_funcParserAssoc__hh
#define gennc_funcParserAssoc__hh


    #include <stddef.h>
    #include <stdint.h>

    #define ParserAssoc__numItems 3
    #define ParserAssoc__prefix "ASSOC_"
    typedef ParserAssoc ParserAssoc_T;


    size_t ParserAssoc_getLength();
    char const *ParserAssoc_getPrefix();

    ParserAssoc_T ParserAssoc_getIthCode(int i);
    char const* ParserAssoc_getIthName(int i);
    char const* ParserAssoc_getIthComment(int i);

    char const *ParserAssoc_getName(ParserAssoc_T c);
    char const *ParserAssoc_getComment(ParserAssoc_T c);
    ParserAssoc_T ParserAssoc_getCode(char const *name, int *res = 0);
    ParserAssoc_T ParserAssoc_getCodeFullName(char const *name, int *res = 0);

    // backward compat
    char const *getParserAssocName(ParserAssoc_T c);
    char const *getParserAssocComment(ParserAssoc_T c);
    ParserAssoc_T getParserAssocValue(char const *name, int *res = 0);

    inline ParserAssoc getParserAssocValue(std::string const &t, int *res = 0) {
       return getParserAssocValue(t.c_str(), res);
    }

    size_t getNumParserAssoc();
    ParserAssoc_T getParserAssoc(int which);
    
    inline std::ostream &operator << (std::ostream &out, ParserAssoc t) {
       out << getParserAssocName(t);
       return out;
    }
    #endif

