// -*- c++ -*- 
// This file has been automatically generated by
// gennc.sh 47
// from definition file xml/logger.ncd.xml.

#define LogLevel__numItems 12
#define LogLevel__prefix ""
typedef LogLevel LogLevel_T;


#define LogLevel__prefixLen 0


typedef uint8_t LogLevel_IndexT;



static int LogLevel__compnames(const void *m1, const void *m2) {
  char const * const * mi1 = (char const * const *) m1;
  char const * const * mi2 = (char const * const *) m2;
  return strcasecmp(*mi1, *mi2);
}


static int LogLevel__compcodes(const void *m1, const void *m2) {
  LogLevel_T const* mi1 = (LogLevel_T const*) m1;
  LogLevel_T const* mi2 = (LogLevel_T const*) m2;
  if (*mi1 < *mi2) return -1;
  else if (*mi1 == *mi2) return 0;
  else return 1;
}
static constexpr  char const* const LogLevel__names[LogLevel__numItems + 1] = {
  "CONFIG", "DEBUG", "ERROR", "FILES", "HELP", "IGNORE", "INFO", "IO", "PARSE", "SCAN",
  "TIMES", "WARNING"
};

static constexpr LogLevel_T const LogLevel__codes[LogLevel__numItems] = {
  CONFIG, PARSE, SCAN, TIMES, FILES, IO, HELP, IGNORE, ERROR, WARNING,
  INFO, DEBUG
};
static constexpr LogLevel_IndexT const LogLevel__indexNames[LogLevel__numItems] = {
  5, 4, 1, 9, 11, 0, 3, 10, 6, 7,
  8, 2
};

static constexpr LogLevel_IndexT const LogLevel__invNames[LogLevel__numItems + 1] = {
  5, 2, 11, 6, 1, 0, 8, 9, 10, 3,
  7, 4, LogLevel__numItems
};

static constexpr LogLevel_IndexT const LogLevel__indexCodes[LogLevel__numItems] = {
  5, 9, 11, 10, 6, 7, 8, 0, 1, 2,
  3, 4
};

static constexpr LogLevel_IndexT const LogLevel__invCodes[LogLevel__numItems] = {
  7, 8, 9, 10, 11, 0, 4, 5, 6, 1,
  3, 2
};
static size_t LogLevel_getLength() {
  return LogLevel__numItems;
}

static char const* LogLevel_getPrefix() {
  return LogLevel__prefix;
}

static LogLevel_T LogLevel_getIthCode(int i) {
  if (i >= 0 && i < LogLevel__numItems) {

    return LogLevel__codes[LogLevel__invCodes[i]];

  }
  return (LogLevel_T) -1;
}

static char const* LogLevel_getIthName(int i) {
  if (i >= 0 && i < LogLevel__numItems) {
    return LogLevel__names[LogLevel__invNames[i]];
  }
  return 0;
}

static char const* LogLevel_getIthComment(int) {

  return 0;
}

static int LogLevel_isCode(LogLevel_T n) {
  return LogLevel_getName(n) != 0;
}

static LogLevel_IndexT LogLevel__getCodeIndex(LogLevel_T code) {
  LogLevel_T const* found = (LogLevel_T const*) bsearch(&code, LogLevel__codes, LogLevel__numItems, sizeof(LogLevel_T), &LogLevel__compcodes);
  if (found) {
    LogLevel_IndexT n = found - LogLevel__codes;
    return LogLevel__indexCodes[n];
  }
  return LogLevel__numItems;
}

static char const *LogLevel_getName(LogLevel_T code) {
  return LogLevel__names[LogLevel__invNames[LogLevel__getCodeIndex(code)]];
}

static LogLevel_T LogLevel_getCode(char const *name, int* res) {
  char const* const* found = (char const* const*)  bsearch(&name, LogLevel__names, LogLevel__numItems, sizeof(char const*), &LogLevel__compnames);
  if (res) *res = found == 0;
  if (found) {
    LogLevel_IndexT n = found - LogLevel__names;
    return LogLevel__codes[LogLevel__invCodes[LogLevel__indexNames[n]]];
  }
  return (LogLevel_T) -1;
}

static LogLevel_T LogLevel_getCodeFullName(char const *name, int* res) {
  return LogLevel_getCode(name + LogLevel__prefixLen, res);
}

static char const *LogLevel_getComment(LogLevel_T) {

  return 0;

}


static char const *getLogLevelName(LogLevel_T c) {
  return LS::LogLevel_getName(c);
}

static char const *getLogLevelComment(LogLevel_T c) {
  return LS::LogLevel_getComment(c);
}

static LogLevel_T getLogLevelValue(char const *name, int *res) {
   if (strncasecmp(name, LogLevel__prefix, LogLevel__prefixLen) == 0) {
     return LS::LogLevel_getCodeFullName(name, res);
   } else {
     return LS::LogLevel_getCode(name, res);
   }
}

static size_t getNumLogLevel() {
  return LS::LogLevel_getLength();
}

static LogLevel_T getLogLevel(int which) {
  return LS::LogLevel_getIthCode(which);
}

inline static LogLevel getLogLevelValue(std::string const &t, int *res = 0) {
   return getLogLevelValue(t.c_str(), res);
}

