// -*- c++ -*- 
// This file has been automatically generated by 
// gennc.sh $Id: gennc.xsl 31 2013-11-07 18:56:43Z jwillkomm $ 
// from definition file xml/logger.ncd.xml. Class mode is true.
#ifndef gennc_enumLogLevel__hh
#define gennc_enumLogLevel__hh

    enum LogLevel {
       /**  */ 
IGNORE = 0, 
 /**  */ 
ERROR = 1, 
 /**  */ 
WARNING = 2, 
 /**  */ 
INFO = 4, 
 /**  */ 
DEBUG = 8, 
 /**  */ 
CONFIG = 0x10, 
 /**  */ 
PARSE = 0x20, 
 /**  */ 
SCAN = 0x40
 
    };
  #endif

