// -*- c++ -*- 
// This file has been automatically generated by
// gennc.sh 47
// from definition file xml/logger.ncd.xml.
#ifndef gennc_enumLogLevel__hh
#define gennc_enumLogLevel__hh

    enum LogLevel {
IGNORE = 0,
ERROR = 1,
WARNING = 2,
INFO = 4,
DEBUG = 8,
CONFIG = 0x10,
PARSE = 0x20,
SCAN = 0x40,
TIMES = 0x80,
FILES = 0x100,
IO = 0x200,
HELP = 0x400
    };
  #endif

