// -*- c++ -*- 
// This file has been automatically generated by
// gennc.sh 47
// from definition file xml/logger.ncd.xml.
#ifndef gennc_funcLogLevel__hh
#define gennc_funcLogLevel__hh


    #include <stddef.h>
    #include <stdint.h>

    #define LogLevel__numItems 12
    #define LogLevel__prefix ""
    typedef LS::LogLevel LogLevel_T;

    inline std::ostream &operator << (std::ostream &out, LS::LogLevel t) {
       out << LS::getLogLevelName(t);
       return out;
    }
    #endif

