// -*- c++ -*- 
// This file has been automatically generated by 
// gennc.sh $Id: gennc.xsl 50 2015-04-08 12:45:49Z jwillkomm $ 
// from definition file xml/logger.ncd.xml. Class mode is true.
#ifndef gennc_funcLogLevel__hh
#define gennc_funcLogLevel__hh

    inline std::ostream &operator << (std::ostream &out, LS::LogLevel t) {
       out << LS::getLogLevelName(t);
       return out;
    }
    #endif

