// -*- c++ -*- 
// This file has been automatically generated by
// gennc.sh 47
// from definition file xml/modes.ncd.xml.
#ifndef gennc_funcParserMode__hh
#define gennc_funcParserMode__hh


    #include <stddef.h>
    #include <stdint.h>

    #define ParserMode__numItems 9
    #define ParserMode__prefix "MODE_"
    typedef ParserMode ParserMode_T;


    size_t ParserMode_getLength();
    char const *ParserMode_getPrefix();

    ParserMode_T ParserMode_getIthCode(int i);
    char const* ParserMode_getIthName(int i);
    char const* ParserMode_getIthComment(int i);

    char const *ParserMode_getName(ParserMode_T c);
    char const *ParserMode_getComment(ParserMode_T c);
    ParserMode_T ParserMode_getCode(char const *name, int *res = 0);
    ParserMode_T ParserMode_getCodeFullName(char const *name, int *res = 0);

    // backward compat
    char const *getParserModeName(ParserMode_T c);
    char const *getParserModeComment(ParserMode_T c);
    ParserMode_T getParserModeValue(char const *name, int *res = 0);

    inline ParserMode getParserModeValue(std::string const &t, int *res = 0) {
       return getParserModeValue(t.c_str(), res);
    }

    size_t getNumParserMode();
    ParserMode_T getParserMode(int which);
    
    inline std::ostream &operator << (std::ostream &out, ParserMode t) {
       out << getParserModeName(t);
       return out;
    }
    #endif

