// -*- c++ -*- 
// This file has been automatically generated by 
// gennc.sh $Id: gennc.xsl 31 2013-11-07 18:56:43Z jwillkomm $ 
// from definition file xml/modes.ncd.xml. Class mode is false.

#include <string>
#include <cstring>
#include <iostream>
#include "modes.ncd.enum.hh"
#include "modes.ncd.hh"
    char const *getParserModeName(unsigned long c) {
      switch(c) { 
       case MODE_IGNORE: return "IGNORE";
       case MODE_ITEM: return "ITEM";
       case MODE_UNARY: return "UNARY";
       case MODE_POSTFIX: return "POSTFIX";
       case MODE_BINARY: return "BINARY";
       case MODE_UNARY_BINARY: return "UNARY_BINARY";
       case MODE_PAREN: return "PAREN"; 
        default: break;
      }
      return "unknown value in enumeration ParserMode";
    }
    char const *getParserModeComment(unsigned long c) {
      switch(c) { 
       case MODE_IGNORE: return "";
       case MODE_ITEM: return "";
       case MODE_UNARY: return "";
       case MODE_POSTFIX: return "";
       case MODE_BINARY: return "";
       case MODE_UNARY_BINARY: return "";
       case MODE_PAREN: return ""; 
        default: break;
      }
      return "unknown value in enumeration ParserMode";
    }
    ParserMode getParserModeValue(char const *name, int *res) {
       if (res) *res = 0;
       if (name == 0 or *name == 0) { return MODE_IGNORE; 
       } else if (strcasecmp("IGNORE", name) == 0
          or strcasecmp("MODE_IGNORE", name) == 0) {
          return MODE_IGNORE; 
       } else if (strcasecmp("ITEM", name) == 0
          or strcasecmp("MODE_ITEM", name) == 0) {
          return MODE_ITEM; 
       } else if (strcasecmp("UNARY", name) == 0
          or strcasecmp("MODE_UNARY", name) == 0) {
          return MODE_UNARY; 
       } else if (strcasecmp("POSTFIX", name) == 0
          or strcasecmp("MODE_POSTFIX", name) == 0) {
          return MODE_POSTFIX; 
       } else if (strcasecmp("BINARY", name) == 0
          or strcasecmp("MODE_BINARY", name) == 0) {
          return MODE_BINARY; 
       } else if (strcasecmp("UNARY_BINARY", name) == 0
          or strcasecmp("MODE_UNARY_BINARY", name) == 0) {
          return MODE_UNARY_BINARY; 
       } else if (strcasecmp("PAREN", name) == 0
          or strcasecmp("MODE_PAREN", name) == 0) {
          return MODE_PAREN;  
       } else {
          if (not res) {
             std::cerr << "error: unknown ParserMode constant named `" << name << "'\n";
          } else {
             *res = 1;
          }
          return MODE_IGNORE;
       }
    }
    unsigned long getNumParserMode() {
      return 7;
    }
    ParserMode getParserMode(int which) {
      switch(which) { 
       case 0: return MODE_IGNORE;
       case 1: return MODE_ITEM;
       case 2: return MODE_UNARY;
       case 3: return MODE_POSTFIX;
       case 4: return MODE_BINARY;
       case 5: return MODE_UNARY_BINARY;
       case 6: return MODE_PAREN; 
       default: break;
      }
      std::cerr << "error: ParserMode constant index " << which << " out of range\n";
      return MODE_IGNORE;
    }
    
