// -*- c++ -*- 
// This file has been automatically generated by 
// gennc.sh $Id: gennc.xsl 50 2015-04-08 12:45:49Z jwillkomm $ 
// from definition file xml/modes.ncd.xml. Class mode is false.
#ifndef gennc_funcParserMode__hh
#define gennc_funcParserMode__hh

    char const *getParserModeName(unsigned long c);
    char const *getParserModeComment(unsigned long c);
    ParserMode getParserModeValue(char const *name, int *res = 0);
    
    inline ParserMode getParserModeValue(std::string const &t, int *res = 0) {
       return getParserModeValue(t.c_str(), res);
    }
    
    unsigned long getNumParserMode();
    ParserMode getParserMode(int which);
    
    inline std::ostream &operator << (std::ostream &out, ParserMode t) {
       out << getParserModeName(t);
       return out;
    }
    #endif

