// -*- c++ -*- 
// This file has been automatically generated by
// gennc.sh 47
// from definition file xml/modes.ncd.xml.

#include <string>
#include <cstring>
#include <iostream>
#include <cstdlib>
#include <stdio.h>
#include <stdint.h>
#include <stddef.h>


#define ParserMode__prefixLen 5


typedef uint8_t ParserMode_IndexT;



static int ParserMode__compnames(const void *m1, const void *m2) {
  char const * const * mi1 = (char const * const *) m1;
  char const * const * mi2 = (char const * const *) m2;
  return strcasecmp(*mi1, *mi2);
}


static int ParserMode__compcodes(const void *m1, const void *m2) {
  ParserMode_T const* mi1 = (ParserMode_T const*) m1;
  ParserMode_T const* mi2 = (ParserMode_T const*) m2;
  if (*mi1 < *mi2) return -1;
  else if (*mi1 == *mi2) return 0;
  else return 1;
}
static  char const* const ParserMode__names[ParserMode__numItems + 1] = {
  "BINARY", "BLOCK_COMMENT", "IGNORE", "ITEM", "LINE_COMMENT", "PAREN", "POSTFIX", "UNARY", "UNARY_BINARY"
};

static ParserMode_T const ParserMode__codes[ParserMode__numItems] = {
  MODE_IGNORE, MODE_ITEM, MODE_UNARY, MODE_POSTFIX, MODE_BINARY, MODE_UNARY_BINARY, MODE_LINE_COMMENT, MODE_PAREN, MODE_BLOCK_COMMENT
};
static ParserMode_IndexT const ParserMode__indexNames[ParserMode__numItems] = {
  4, 8, 0, 1, 6, 7, 3, 2, 5
};

static ParserMode_IndexT const ParserMode__invNames[ParserMode__numItems + 1] = {
  2, 3, 7, 6, 0, 8, 4, 5, 1, ParserMode__numItems
};

static ParserMode_IndexT const ParserMode__indexCodes[ParserMode__numItems] = {
  0, 1, 2, 3, 4, 5, 6, 7, 8
};

static ParserMode_IndexT const ParserMode__invCodes[ParserMode__numItems] = {
  0, 1, 2, 3, 4, 5, 6, 7, 8
};
size_t ParserMode_getLength() {
  return ParserMode__numItems;
}

char const* ParserMode_getPrefix() {
  return ParserMode__prefix;
}

ParserMode_T ParserMode_getIthCode(int i) {
  if (i >= 0 && i < ParserMode__numItems) {

    return ParserMode__codes[ParserMode__invCodes[i]];

  }
  return (ParserMode_T) -1;
}

char const* ParserMode_getIthName(int i) {
  if (i >= 0 && i < ParserMode__numItems) {
    return ParserMode__names[ParserMode__invNames[i]];
  }
  return 0;
}

char const* ParserMode_getIthComment(int) {

  return 0;
}

int ParserMode_isCode(ParserMode_T n) {
  return ParserMode_getName(n) != 0;
}

static ParserMode_IndexT ParserMode__getCodeIndex(ParserMode_T code) {
  ParserMode_T const* found = (ParserMode_T const*) bsearch(&code, ParserMode__codes, ParserMode__numItems, sizeof(ParserMode_T), &ParserMode__compcodes);
  if (found) {
    ParserMode_IndexT n = found - ParserMode__codes;
    return ParserMode__indexCodes[n];
  }
  return ParserMode__numItems;
}

char const *ParserMode_getName(ParserMode_T code) {
  return ParserMode__names[ParserMode__invNames[ParserMode__getCodeIndex(code)]];
}

ParserMode_T ParserMode_getCode(char const *name, int* res) {
  char const* const* found = (char const* const*)  bsearch(&name, ParserMode__names, ParserMode__numItems, sizeof(char const*), &ParserMode__compnames);
  if (res) *res = found == 0;
  if (found) {
    ParserMode_IndexT n = found - ParserMode__names;
    return ParserMode__codes[ParserMode__invCodes[ParserMode__indexNames[n]]];
  }
  return (ParserMode_T) -1;
}

ParserMode_T ParserMode_getCodeFullName(char const *name, int* res) {
  return ParserMode_getCode(name + ParserMode__prefixLen, res);
}

char const *ParserMode_getComment(ParserMode_T) {

  return 0;

}


char const *getParserModeName(ParserMode_T c) {
  return ParserMode_getName(c);
}

char const *getParserModeComment(ParserMode_T c) {
  return ParserMode_getComment(c);
}

ParserMode_T getParserModeValue(char const *name, int *res) {
   if (strncasecmp(name, ParserMode__prefix, ParserMode__prefixLen) == 0) {
     return ParserMode_getCodeFullName(name, res);
   } else {
     return ParserMode_getCode(name, res);
   }
}

size_t getNumParserMode() {
  return ParserMode_getLength();
}

ParserMode_T getParserMode(int which) {
  return ParserMode_getIthCode(which);
}

