// -*- c++ -*- 
// This file has been automatically generated by 
// gennc.sh $Id: gennc.xsl 50 2015-04-08 12:45:49Z jwillkomm $ 
// from definition file xml/modes.ncd.xml. Class mode is false.
#ifndef gennc_enumParserMode__hh
#define gennc_enumParserMode__hh

    enum ParserMode {
MODE_IGNORE = 1, 
MODE_ITEM, 
MODE_UNARY, 
MODE_POSTFIX, 
MODE_BINARY, 
MODE_UNARY_BINARY, 
MODE_PAREN = 32
    };
  #endif

