// -*- c++ -*- 
// This file has been automatically generated by
// gennc.sh 47
// from definition file xml/output-modes.ncd.xml.

#include <string>
#include <cstring>
#include <iostream>
#include <cstdlib>
#include <stdio.h>
#include <stdint.h>
#include <stddef.h>


#define OutputMode__prefixLen 12


typedef uint8_t OutputMode_IndexT;



static int OutputMode__compnames(const void *m1, const void *m2) {
  char const * const * mi1 = (char const * const *) m1;
  char const * const * mi2 = (char const * const *) m2;
  return strcasecmp(*mi1, *mi2);
}

static  char const* const OutputMode__names[OutputMode__numItems + 1] = {
  "MERGED", "NESTED", "NONE"
};

static OutputMode_IndexT const OutputMode__indexNames[OutputMode__numItems] = {
  2, 1, 0
};

static OutputMode_IndexT const OutputMode__invNames[OutputMode__numItems + 1] = {
  2, 1, 0, OutputMode__numItems
};

size_t OutputMode_getLength() {
  return OutputMode__numItems;
}

char const* OutputMode_getPrefix() {
  return OutputMode__prefix;
}

OutputMode_T OutputMode_getIthCode(int i) {
  if (i >= 0 && i < OutputMode__numItems) {

    return (OutputMode_T) i;

  }
  return (OutputMode_T) -1;
}

char const* OutputMode_getIthName(int i) {
  if (i >= 0 && i < OutputMode__numItems) {
    return OutputMode__names[OutputMode__invNames[i]];
  }
  return 0;
}

char const* OutputMode_getIthComment(int) {

  return 0;
}

int OutputMode_isCode(OutputMode_T n) {
  return OutputMode_getName(n) != 0;
}

static OutputMode_IndexT OutputMode__getCodeIndex(OutputMode_T code) {
  if ((unsigned) code < OutputMode__numItems) return code;
  return OutputMode__numItems;
}

char const *OutputMode_getName(OutputMode_T code) {
  return OutputMode__names[OutputMode__invNames[OutputMode__getCodeIndex(code)]];
}

OutputMode_T OutputMode_getCode(char const *name, int* res) {
  char const* const* found = (char const* const*)  bsearch(&name, OutputMode__names, OutputMode__numItems, sizeof(char const*), &OutputMode__compnames);
  if (res) *res = found == 0;
  if (found) {
    OutputMode_IndexT n = found - OutputMode__names;
    return (OutputMode_T) OutputMode__indexNames[n];
  }
  return (OutputMode_T) -1;
}

OutputMode_T OutputMode_getCodeFullName(char const *name, int* res) {
  return OutputMode_getCode(name + OutputMode__prefixLen, res);
}

char const *OutputMode_getComment(OutputMode_T) {

  return 0;

}


char const *getOutputModeName(OutputMode_T c) {
  return OutputMode_getName(c);
}

char const *getOutputModeComment(OutputMode_T c) {
  return OutputMode_getComment(c);
}

OutputMode_T getOutputModeValue(char const *name, int *res) {
   if (strncasecmp(name, OutputMode__prefix, OutputMode__prefixLen) == 0) {
     return OutputMode_getCodeFullName(name, res);
   } else {
     return OutputMode_getCode(name, res);
   }
}

size_t getNumOutputMode() {
  return OutputMode_getLength();
}

OutputMode_T getOutputMode(int which) {
  return OutputMode_getIthCode(which);
}

