// -*- c++ -*- 
// This file has been automatically generated by
// gennc.sh 47
// from definition file xml/output-modes.ncd.xml.
#ifndef gennc_funcOutputMode__hh
#define gennc_funcOutputMode__hh


    #include <stddef.h>
    #include <stdint.h>

    #define OutputMode__numItems 3
    #define OutputMode__prefix "OUTPUT_MODE_"
    typedef OutputMode OutputMode_T;


    size_t OutputMode_getLength();
    char const *OutputMode_getPrefix();

    OutputMode_T OutputMode_getIthCode(int i);
    char const* OutputMode_getIthName(int i);
    char const* OutputMode_getIthComment(int i);

    char const *OutputMode_getName(OutputMode_T c);
    char const *OutputMode_getComment(OutputMode_T c);
    OutputMode_T OutputMode_getCode(char const *name, int *res = 0);
    OutputMode_T OutputMode_getCodeFullName(char const *name, int *res = 0);

    // backward compat
    char const *getOutputModeName(OutputMode_T c);
    char const *getOutputModeComment(OutputMode_T c);
    OutputMode_T getOutputModeValue(char const *name, int *res = 0);

    inline OutputMode getOutputModeValue(std::string const &t, int *res = 0) {
       return getOutputModeValue(t.c_str(), res);
    }

    size_t getNumOutputMode();
    OutputMode_T getOutputMode(int which);
    
    inline std::ostream &operator << (std::ostream &out, OutputMode t) {
       out << getOutputModeName(t);
       return out;
    }
    #endif

