// -*- c++ -*- 
// This file has been automatically generated by 
// gennc.sh $Id: gennc.xsl 31 2013-11-07 18:56:43Z jwillkomm $ 
// from definition file xml/output-modes.ncd.xml. Class mode is false.
#ifndef gennc_enumOutputMode__hh
#define gennc_enumOutputMode__hh

    enum OutputMode {
       /**  */ 
OUTPUT_MODE_NONE = 0, 
 /**  */ 
OUTPUT_MODE_NESTED, 
 /**  */ 
OUTPUT_MODE_MERGED
 
    };
  #endif

