// -*- c++ -*- 
// This file has been automatically generated by 
// gennc.sh $Id: gennc.xsl 31 2013-11-07 18:56:43Z jwillkomm $ 
// from definition file xml/output-modes.ncd.xml. Class mode is false.

#include <string>
#include <cstring>
#include <iostream>
#include "output-modes.ncd.enum.hh"
#include "output-modes.ncd.hh"
    char const *getOutputModeName(unsigned long c) {
      switch(c) { 
       case OUTPUT_MODE_NONE: return "NONE";
       case OUTPUT_MODE_NESTED: return "NESTED";
       case OUTPUT_MODE_MERGED: return "MERGED"; 
        default: break;
      }
      return "unknown value in enumeration OutputMode";
    }
    char const *getOutputModeComment(unsigned long c) {
      switch(c) { 
       case OUTPUT_MODE_NONE: return "";
       case OUTPUT_MODE_NESTED: return "";
       case OUTPUT_MODE_MERGED: return ""; 
        default: break;
      }
      return "unknown value in enumeration OutputMode";
    }
    OutputMode getOutputModeValue(char const *name, int *res) {
       if (res) *res = 0;
       if (name == 0 or *name == 0) { return OUTPUT_MODE_NONE; 
       } else if (strcasecmp("NONE", name) == 0
          or strcasecmp("OUTPUT_MODE_NONE", name) == 0) {
          return OUTPUT_MODE_NONE; 
       } else if (strcasecmp("NESTED", name) == 0
          or strcasecmp("OUTPUT_MODE_NESTED", name) == 0) {
          return OUTPUT_MODE_NESTED; 
       } else if (strcasecmp("MERGED", name) == 0
          or strcasecmp("OUTPUT_MODE_MERGED", name) == 0) {
          return OUTPUT_MODE_MERGED;  
       } else {
          if (not res) {
             std::cerr << "error: unknown OutputMode constant named `" << name << "'\n";
          } else {
             *res = 1;
          }
          return OUTPUT_MODE_NONE;
       }
    }
    unsigned long getNumOutputMode() {
      return 3;
    }
    OutputMode getOutputMode(int which) {
      switch(which) { 
       case 0: return OUTPUT_MODE_NONE;
       case 1: return OUTPUT_MODE_NESTED;
       case 2: return OUTPUT_MODE_MERGED; 
       default: break;
      }
      std::cerr << "error: OutputMode constant index " << which << " out of range\n";
      return OUTPUT_MODE_NONE;
    }
    
