// -*- c++ -*- 
// This file has been automatically generated by 
// gennc.sh $Id: gennc.xsl 50 2015-04-08 12:45:49Z jwillkomm $ 
// from definition file xml/output-modes.ncd.xml. Class mode is false.

#include <string>
#include <cstring>
#include <iostream>
#include <cstdlib>
#include <stdio.h>
#include "output-modes.ncd.enum.hh"
#include "output-modes.ncd.hh"
    char const *getOutputModeName(unsigned long c) {
      switch(c) { 
       case OUTPUT_MODE_NONE: return "NONE";
       case OUTPUT_MODE_NESTED: return "NESTED";
       case OUTPUT_MODE_MERGED: return "MERGED"; 
        default: break;
      }
      return "unknown value in enumeration OutputMode";
    }
    char const *getOutputModeComment(unsigned long c) {
      switch(c) { 
       case OUTPUT_MODE_NONE: return "";
       case OUTPUT_MODE_NESTED: return "";
       case OUTPUT_MODE_MERGED: return ""; 
        default: break;
      }
      return "unknown value in enumeration OutputMode";
    }
    OutputMode getOutputModeValue(char const *name, int *res) {
       if (res) *res = 0;
       if (name == 0 || *name == 0) { return OUTPUT_MODE_NONE; 
       } else if (strcasecmp("NONE", name) == 0
          || strcasecmp("OUTPUT_MODE_NONE", name) == 0) {
          return OUTPUT_MODE_NONE; 
       } else if (strcasecmp("NESTED", name) == 0
          || strcasecmp("OUTPUT_MODE_NESTED", name) == 0) {
          return OUTPUT_MODE_NESTED; 
       } else if (strcasecmp("MERGED", name) == 0
          || strcasecmp("OUTPUT_MODE_MERGED", name) == 0) {
          return OUTPUT_MODE_MERGED;  
       } else {
          if (! res) {
            fprintf(stderr, "error: unknown %s constant named `%s'\n",
              "OutputMode", name);
          } else {
             *res = 1;
          }
          return OUTPUT_MODE_NONE;
       }
    }
    unsigned long getNumOutputMode() {
      return 3;
    }
    OutputMode getOutputMode(int which) {
      switch(which) { 
       case 0: return OUTPUT_MODE_NONE;
       case 1: return OUTPUT_MODE_NESTED;
       case 2: return OUTPUT_MODE_MERGED; 
       default: break;
      }
      fprintf(stderr, "error: OutputMode constant index %d out of range\n",
              which);
      return OUTPUT_MODE_NONE;
    }
    
