// -*- c++ -*- 
// This file has been automatically generated by
// gennc.sh $Id: gennc.xsl 110 2018-10-09 15:02:12Z jwillkomm $
// from definition file xml/output-modes.ncd.xml. Class mode is false.
#ifndef gennc_enumOutputMode__hh
#define gennc_enumOutputMode__hh

    enum OutputMode {
OUTPUT_MODE_NONE = 0,
OUTPUT_MODE_NESTED,
OUTPUT_MODE_MERGED
    };
  #endif

