// -*- c++ -*- 
// This file has been automatically generated by
// gennc.sh 47
// from definition file xml/output-modes.ncd.xml.
#ifndef gennc_enumOutputMode__hh
#define gennc_enumOutputMode__hh

    enum OutputMode {
OUTPUT_MODE_NONE,
OUTPUT_MODE_NESTED,
OUTPUT_MODE_MERGED
    };
  #endif

