// -*- c++ -*- 
// This file has been automatically generated by 
// gennc.sh $Id: gennc.xsl 31 2013-11-07 18:56:43Z jwillkomm $ 
// from definition file xml/output-modes.ncd.xml. Class mode is false.
#ifndef gennc_funcOutputMode__hh
#define gennc_funcOutputMode__hh

    char const *getOutputModeName(unsigned long c);
    char const *getOutputModeComment(unsigned long c);
    OutputMode getOutputModeValue(char const *name, int *res = 0);
    inline OutputMode getOutputModeValue(std::string const &t, int *res = 0) {
       return getOutputModeValue(t.c_str(), res);
    }
    unsigned long getNumOutputMode();
    OutputMode getOutputMode(int which);
    
    inline std::ostream &operator << (std::ostream &out, OutputMode t) {
       out << getOutputModeName(t);
       return out;
    }
    #endif

