/* Generated by re2c 1.1.1 on Fri Nov 16 20:21:48 2018 */
#line 1 "re2c-scanner-m.re"
/*
This file is part of P2X.
Copyright © 2018 Johannes Willkomm
See the file p2x.cc for copying conditions.
*/

#include "token.ncd.enum.hh"

#define YYMAXFILL 4


#line 15 "re2c-scanner-m.cc"
enum YYCONDTYPE {
	yycINITIAL,
	yycSTARTEXP,
};
#line 11 "re2c-scanner-m.re"


typedef unsigned char uint8_t;

static int re2c_scanner_m_c = yycINITIAL;

int re2c_scanner_m_lex(const uint8_t *&s, const uint8_t *&m, uint8_t const * lim)
{

  

    lim += YYMAXFILL;

    
#line 35 "re2c-scanner-m.cc"
{
	uint8_t yych;
	unsigned int yyaccept = 0;
	switch (re2c_scanner_m_c) {
	case yycINITIAL: goto yyc_INITIAL;
	case yycSTARTEXP: goto yyc_STARTEXP;
	}
/* *********************************** */
yyc_INITIAL:
	if ((lim - s) < 4) return false;
	yych = *s;
	switch (yych) {
	case 0x00:	goto yy3;
	case '\t':	goto yy7;
	case '\n':	goto yy9;
	case '\r':	goto yy11;
	case ' ':	goto yy13;
	case '!':	goto yy16;
	case '"':	goto yy18;
	case '#':	goto yy19;
	case '%':	goto yy21;
	case '&':	goto yy23;
	case '\'':	goto yy25;
	case '(':	goto yy27;
	case ')':	goto yy29;
	case '*':	goto yy31;
	case '+':	goto yy33;
	case ',':	goto yy35;
	case '-':	goto yy37;
	case '.':	goto yy39;
	case '/':	goto yy41;
	case '0':	goto yy43;
	case '1':
	case '2':
	case '3':
	case '4':
	case '5':
	case '6':
	case '7':
	case '8':
	case '9':	goto yy45;
	case ':':	goto yy47;
	case ';':	goto yy49;
	case '<':	goto yy51;
	case '=':	goto yy53;
	case '>':	goto yy55;
	case '?':	goto yy57;
	case '@':	goto yy59;
	case 'A':
	case 'B':
	case 'C':
	case 'D':
	case 'E':
	case 'F':
	case 'G':
	case 'H':
	case 'I':
	case 'J':
	case 'K':
	case 'L':
	case 'M':
	case 'N':
	case 'O':
	case 'P':
	case 'Q':
	case 'R':
	case 'S':
	case 'T':
	case 'U':
	case 'V':
	case 'W':
	case 'X':
	case 'Y':
	case 'Z':
	case '_':
	case 'a':
	case 'b':
	case 'c':
	case 'd':
	case 'e':
	case 'f':
	case 'g':
	case 'h':
	case 'i':
	case 'j':
	case 'k':
	case 'l':
	case 'm':
	case 'n':
	case 'o':
	case 'p':
	case 'q':
	case 'r':
	case 's':
	case 't':
	case 'u':
	case 'v':
	case 'w':
	case 'x':
	case 'y':
	case 'z':	goto yy61;
	case '[':	goto yy64;
	case '\\':	goto yy66;
	case ']':	goto yy68;
	case '^':	goto yy70;
	case '{':	goto yy72;
	case '|':	goto yy74;
	case '}':	goto yy76;
	case '~':	goto yy78;
	case 0xC0:
	case 0xC1:
	case 0xC2:
	case 0xC3:
	case 0xC4:
	case 0xC5:
	case 0xC6:
	case 0xC7:
	case 0xC8:
	case 0xC9:
	case 0xCA:
	case 0xCB:
	case 0xCC:
	case 0xCD:
	case 0xCE:
	case 0xCF:
	case 0xD0:
	case 0xD1:
	case 0xD2:
	case 0xD3:
	case 0xD4:
	case 0xD5:
	case 0xD6:
	case 0xD7:
	case 0xD8:
	case 0xD9:
	case 0xDA:
	case 0xDB:
	case 0xDC:
	case 0xDD:
	case 0xDE:
	case 0xDF:	goto yy80;
	case 0xE0:
	case 0xE1:
	case 0xE2:
	case 0xE3:
	case 0xE4:
	case 0xE5:
	case 0xE6:
	case 0xE7:
	case 0xE8:
	case 0xE9:
	case 0xEA:
	case 0xEB:
	case 0xEC:
	case 0xED:
	case 0xEE:
	case 0xEF:	goto yy81;
	case 0xF0:
	case 0xF1:
	case 0xF2:
	case 0xF3:
	case 0xF4:
	case 0xF5:
	case 0xF6:
	case 0xF7:	goto yy82;
	default:	goto yy5;
	}
yy3:
	++s;
#line 143 "re2c-scanner-m.re"
	{ return TOKEN_EOF; }
#line 207 "re2c-scanner-m.cc"
yy5:
	++s;
yy6:
#line 145 "re2c-scanner-m.re"
	{ return TOKEN_ILLEGAL_CHAR; }
#line 213 "re2c-scanner-m.cc"
yy7:
	++s;
	re2c_scanner_m_c = yycSTARTEXP;
#line 137 "re2c-scanner-m.re"
	{ return TOKEN_TAB; }
#line 219 "re2c-scanner-m.cc"
yy9:
	++s;
	re2c_scanner_m_c = yycSTARTEXP;
#line 136 "re2c-scanner-m.re"
	{ return TOKEN_NEWLINE; }
#line 225 "re2c-scanner-m.cc"
yy11:
	++s;
	re2c_scanner_m_c = yycSTARTEXP;
#line 135 "re2c-scanner-m.re"
	{ return TOKEN_CRETURN; }
#line 231 "re2c-scanner-m.cc"
yy13:
	++s;
	if (lim <= s) return false;
	yych = *s;
	switch (yych) {
	case ' ':	goto yy13;
	default:	goto yy15;
	}
yy15:
	re2c_scanner_m_c = yycSTARTEXP;
#line 138 "re2c-scanner-m.re"
	{ return TOKEN_SPACE; }
#line 244 "re2c-scanner-m.cc"
yy16:
	yych = *++s;
	switch (yych) {
	case '=':	goto yy83;
	default:	goto yy17;
	}
yy17:
	re2c_scanner_m_c = yycSTARTEXP;
#line 92 "re2c-scanner-m.re"
	{ return TOKEN_EXCLAM; }
#line 255 "re2c-scanner-m.cc"
yy18:
	yyaccept = 0;
	yych = *(m = ++s);
	switch (yych) {
	case 0x00:
	case '\n':	goto yy6;
	default:	goto yy86;
	}
yy19:
	++s;
#line 133 "re2c-scanner-m.re"
	{ return TOKEN_HASH; }
#line 268 "re2c-scanner-m.cc"
yy21:
	++s;
	re2c_scanner_m_c = yycSTARTEXP;
#line 108 "re2c-scanner-m.re"
	{ return TOKEN_MOD; }
#line 274 "re2c-scanner-m.cc"
yy23:
	yych = *++s;
	switch (yych) {
	case '&':	goto yy92;
	default:	goto yy24;
	}
yy24:
	re2c_scanner_m_c = yycSTARTEXP;
#line 99 "re2c-scanner-m.re"
	{ return TOKEN_AND; }
#line 285 "re2c-scanner-m.cc"
yy25:
	++s;
	re2c_scanner_m_c = yycSTARTEXP;
#line 111 "re2c-scanner-m.re"
	{ return TOKEN_APOS; }
#line 291 "re2c-scanner-m.cc"
yy27:
	++s;
	re2c_scanner_m_c = yycSTARTEXP;
#line 70 "re2c-scanner-m.re"
	{ return TOKEN_L_PAREN; }
#line 297 "re2c-scanner-m.cc"
yy29:
	++s;
#line 71 "re2c-scanner-m.re"
	{ return TOKEN_R_PAREN; }
#line 302 "re2c-scanner-m.cc"
yy31:
	yych = *++s;
	switch (yych) {
	case '=':	goto yy94;
	default:	goto yy32;
	}
yy32:
	re2c_scanner_m_c = yycSTARTEXP;
#line 107 "re2c-scanner-m.re"
	{ return TOKEN_MULT; }
#line 313 "re2c-scanner-m.cc"
yy33:
	yych = *++s;
	switch (yych) {
	case '=':	goto yy96;
	default:	goto yy34;
	}
yy34:
	re2c_scanner_m_c = yycSTARTEXP;
#line 104 "re2c-scanner-m.re"
	{ return TOKEN_PLUS; }
#line 324 "re2c-scanner-m.cc"
yy35:
	++s;
	re2c_scanner_m_c = yycSTARTEXP;
#line 95 "re2c-scanner-m.re"
	{ return TOKEN_COMMA; }
#line 330 "re2c-scanner-m.cc"
yy37:
	yych = *++s;
	switch (yych) {
	case '=':	goto yy98;
	default:	goto yy38;
	}
yy38:
	re2c_scanner_m_c = yycSTARTEXP;
#line 105 "re2c-scanner-m.re"
	{ return TOKEN_MINUS; }
#line 341 "re2c-scanner-m.cc"
yy39:
	yyaccept = 1;
	yych = *(m = ++s);
	switch (yych) {
	case '\'':	goto yy100;
	case '*':	goto yy102;
	case '.':	goto yy104;
	case '/':	goto yy105;
	case '0':
	case '1':
	case '2':
	case '3':
	case '4':
	case '5':
	case '6':
	case '7':
	case '8':
	case '9':	goto yy107;
	case '\\':	goto yy110;
	case '^':	goto yy112;
	default:	goto yy40;
	}
yy40:
	re2c_scanner_m_c = yycSTARTEXP;
#line 97 "re2c-scanner-m.re"
	{ return TOKEN_FULL_STOP; }
#line 368 "re2c-scanner-m.cc"
yy41:
	yych = *++s;
	switch (yych) {
	case '=':	goto yy114;
	default:	goto yy42;
	}
yy42:
	re2c_scanner_m_c = yycSTARTEXP;
#line 106 "re2c-scanner-m.re"
	{ return TOKEN_DIV; }
#line 379 "re2c-scanner-m.cc"
yy43:
	yyaccept = 2;
	yych = *(m = ++s);
	switch (yych) {
	case 'x':	goto yy121;
	default:	goto yy46;
	}
yy44:
#line 64 "re2c-scanner-m.re"
	{ return TOKEN_INTEGER; }
#line 390 "re2c-scanner-m.cc"
yy45:
	yyaccept = 2;
	m = ++s;
	if ((lim - s) < 3) return false;
	yych = *s;
yy46:
	switch (yych) {
	case '.':	goto yy116;
	case '0':
	case '1':
	case '2':
	case '3':
	case '4':
	case '5':
	case '6':
	case '7':
	case '8':
	case '9':	goto yy45;
	case 'D':
	case 'E':
	case 'd':
	case 'e':	goto yy117;
	case 'F':
	case 'I':
	case 'f':
	case 'i':	goto yy118;
	case 'L':
	case 'U':
	case 'l':
	case 'u':	goto yy119;
	default:	goto yy44;
	}
yy47:
	++s;
	re2c_scanner_m_c = yycSTARTEXP;
#line 94 "re2c-scanner-m.re"
	{ return TOKEN_COLON; }
#line 428 "re2c-scanner-m.cc"
yy49:
	++s;
	re2c_scanner_m_c = yycSTARTEXP;
#line 96 "re2c-scanner-m.re"
	{ return TOKEN_SEMICOLON; }
#line 434 "re2c-scanner-m.cc"
yy51:
	yych = *++s;
	switch (yych) {
	case '=':	goto yy122;
	default:	goto yy52;
	}
yy52:
	re2c_scanner_m_c = yycSTARTEXP;
#line 81 "re2c-scanner-m.re"
	{ return TOKEN_LESS; }
#line 445 "re2c-scanner-m.cc"
yy53:
	yych = *++s;
	switch (yych) {
	case '=':	goto yy124;
	default:	goto yy54;
	}
yy54:
	re2c_scanner_m_c = yycSTARTEXP;
#line 79 "re2c-scanner-m.re"
	{ return TOKEN_EQUAL; }
#line 456 "re2c-scanner-m.cc"
yy55:
	yych = *++s;
	switch (yych) {
	case '=':	goto yy126;
	default:	goto yy56;
	}
yy56:
	re2c_scanner_m_c = yycSTARTEXP;
#line 82 "re2c-scanner-m.re"
	{ return TOKEN_GREATER; }
#line 467 "re2c-scanner-m.cc"
yy57:
	++s;
	re2c_scanner_m_c = yycSTARTEXP;
#line 93 "re2c-scanner-m.re"
	{ return TOKEN_QUESTION; }
#line 473 "re2c-scanner-m.cc"
yy59:
	++s;
	re2c_scanner_m_c = yycSTARTEXP;
#line 131 "re2c-scanner-m.re"
	{ return TOKEN_AT; }
#line 479 "re2c-scanner-m.cc"
yy61:
	yyaccept = 3;
	m = ++s;
	if (lim <= s) return false;
	yych = *s;
	switch (yych) {
	case '0':
	case '1':
	case '2':
	case '3':
	case '4':
	case '5':
	case '6':
	case '7':
	case '8':
	case '9':
	case 'A':
	case 'B':
	case 'C':
	case 'D':
	case 'E':
	case 'F':
	case 'G':
	case 'H':
	case 'I':
	case 'J':
	case 'K':
	case 'L':
	case 'M':
	case 'N':
	case 'O':
	case 'P':
	case 'Q':
	case 'R':
	case 'S':
	case 'T':
	case 'U':
	case 'V':
	case 'W':
	case 'X':
	case 'Y':
	case 'Z':
	case '_':
	case 'a':
	case 'b':
	case 'c':
	case 'd':
	case 'e':
	case 'f':
	case 'g':
	case 'h':
	case 'i':
	case 'j':
	case 'k':
	case 'l':
	case 'm':
	case 'n':
	case 'o':
	case 'p':
	case 'q':
	case 'r':
	case 's':
	case 't':
	case 'u':
	case 'v':
	case 'w':
	case 'x':
	case 'y':
	case 'z':	goto yy61;
	case 0xC0:
	case 0xC1:
	case 0xC2:
	case 0xC3:
	case 0xC4:
	case 0xC5:
	case 0xC6:
	case 0xC7:
	case 0xC8:
	case 0xC9:
	case 0xCA:
	case 0xCB:
	case 0xCC:
	case 0xCD:
	case 0xCE:
	case 0xCF:
	case 0xD0:
	case 0xD1:
	case 0xD2:
	case 0xD3:
	case 0xD4:
	case 0xD5:
	case 0xD6:
	case 0xD7:
	case 0xD8:
	case 0xD9:
	case 0xDA:
	case 0xDB:
	case 0xDC:
	case 0xDD:
	case 0xDE:
	case 0xDF:	goto yy128;
	case 0xE0:
	case 0xE1:
	case 0xE2:
	case 0xE3:
	case 0xE4:
	case 0xE5:
	case 0xE6:
	case 0xE7:
	case 0xE8:
	case 0xE9:
	case 0xEA:
	case 0xEB:
	case 0xEC:
	case 0xED:
	case 0xEE:
	case 0xEF:	goto yy129;
	case 0xF0:
	case 0xF1:
	case 0xF2:
	case 0xF3:
	case 0xF4:
	case 0xF5:
	case 0xF6:
	case 0xF7:	goto yy130;
	default:	goto yy63;
	}
yy63:
#line 139 "re2c-scanner-m.re"
	{ return TOKEN_IDENTIFIER; }
#line 610 "re2c-scanner-m.cc"
yy64:
	++s;
	re2c_scanner_m_c = yycSTARTEXP;
#line 76 "re2c-scanner-m.re"
	{ return TOKEN_L_BRACKET; }
#line 616 "re2c-scanner-m.cc"
yy66:
	yych = *++s;
	switch (yych) {
	case '=':	goto yy131;
	default:	goto yy67;
	}
yy67:
	re2c_scanner_m_c = yycSTARTEXP;
#line 109 "re2c-scanner-m.re"
	{ return TOKEN_BACKSLASH; }
#line 627 "re2c-scanner-m.cc"
yy68:
	++s;
#line 77 "re2c-scanner-m.re"
	{ return TOKEN_R_BRACKET; }
#line 632 "re2c-scanner-m.cc"
yy70:
	yych = *++s;
	switch (yych) {
	case '=':	goto yy133;
	default:	goto yy71;
	}
yy71:
	re2c_scanner_m_c = yycSTARTEXP;
#line 110 "re2c-scanner-m.re"
	{ return TOKEN_POW; }
#line 643 "re2c-scanner-m.cc"
yy72:
	++s;
	re2c_scanner_m_c = yycSTARTEXP;
#line 73 "re2c-scanner-m.re"
	{ return TOKEN_L_BRACE; }
#line 649 "re2c-scanner-m.cc"
yy74:
	yych = *++s;
	switch (yych) {
	case '|':	goto yy135;
	default:	goto yy75;
	}
yy75:
	re2c_scanner_m_c = yycSTARTEXP;
#line 101 "re2c-scanner-m.re"
	{ return TOKEN_OR; }
#line 660 "re2c-scanner-m.cc"
yy76:
	++s;
#line 74 "re2c-scanner-m.re"
	{ return TOKEN_R_BRACE; }
#line 665 "re2c-scanner-m.cc"
yy78:
	yych = *++s;
	switch (yych) {
	case '=':	goto yy137;
	default:	goto yy79;
	}
yy79:
	re2c_scanner_m_c = yycSTARTEXP;
#line 91 "re2c-scanner-m.re"
	{ return TOKEN_TILDE; }
#line 676 "re2c-scanner-m.cc"
yy80:
	yych = *++s;
	switch (yych) {
	case 0x80:
	case 0x81:
	case 0x82:
	case 0x83:
	case 0x84:
	case 0x85:
	case 0x86:
	case 0x87:
	case 0x88:
	case 0x89:
	case 0x8A:
	case 0x8B:
	case 0x8C:
	case 0x8D:
	case 0x8E:
	case 0x8F:
	case 0x90:
	case 0x91:
	case 0x92:
	case 0x93:
	case 0x94:
	case 0x95:
	case 0x96:
	case 0x97:
	case 0x98:
	case 0x99:
	case 0x9A:
	case 0x9B:
	case 0x9C:
	case 0x9D:
	case 0x9E:
	case 0x9F:
	case 0xA0:
	case 0xA1:
	case 0xA2:
	case 0xA3:
	case 0xA4:
	case 0xA5:
	case 0xA6:
	case 0xA7:
	case 0xA8:
	case 0xA9:
	case 0xAA:
	case 0xAB:
	case 0xAC:
	case 0xAD:
	case 0xAE:
	case 0xAF:
	case 0xB0:
	case 0xB1:
	case 0xB2:
	case 0xB3:
	case 0xB4:
	case 0xB5:
	case 0xB6:
	case 0xB7:
	case 0xB8:
	case 0xB9:
	case 0xBA:
	case 0xBB:
	case 0xBC:
	case 0xBD:
	case 0xBE:
	case 0xBF:	goto yy61;
	default:	goto yy6;
	}
yy81:
	yyaccept = 0;
	yych = *(m = ++s);
	switch (yych) {
	case 0x80:
	case 0x81:
	case 0x82:
	case 0x83:
	case 0x84:
	case 0x85:
	case 0x86:
	case 0x87:
	case 0x88:
	case 0x89:
	case 0x8A:
	case 0x8B:
	case 0x8C:
	case 0x8D:
	case 0x8E:
	case 0x8F:
	case 0x90:
	case 0x91:
	case 0x92:
	case 0x93:
	case 0x94:
	case 0x95:
	case 0x96:
	case 0x97:
	case 0x98:
	case 0x99:
	case 0x9A:
	case 0x9B:
	case 0x9C:
	case 0x9D:
	case 0x9E:
	case 0x9F:
	case 0xA0:
	case 0xA1:
	case 0xA2:
	case 0xA3:
	case 0xA4:
	case 0xA5:
	case 0xA6:
	case 0xA7:
	case 0xA8:
	case 0xA9:
	case 0xAA:
	case 0xAB:
	case 0xAC:
	case 0xAD:
	case 0xAE:
	case 0xAF:
	case 0xB0:
	case 0xB1:
	case 0xB2:
	case 0xB3:
	case 0xB4:
	case 0xB5:
	case 0xB6:
	case 0xB7:
	case 0xB8:
	case 0xB9:
	case 0xBA:
	case 0xBB:
	case 0xBC:
	case 0xBD:
	case 0xBE:
	case 0xBF:	goto yy128;
	default:	goto yy6;
	}
yy82:
	yyaccept = 0;
	yych = *(m = ++s);
	switch (yych) {
	case 0x80:
	case 0x81:
	case 0x82:
	case 0x83:
	case 0x84:
	case 0x85:
	case 0x86:
	case 0x87:
	case 0x88:
	case 0x89:
	case 0x8A:
	case 0x8B:
	case 0x8C:
	case 0x8D:
	case 0x8E:
	case 0x8F:
	case 0x90:
	case 0x91:
	case 0x92:
	case 0x93:
	case 0x94:
	case 0x95:
	case 0x96:
	case 0x97:
	case 0x98:
	case 0x99:
	case 0x9A:
	case 0x9B:
	case 0x9C:
	case 0x9D:
	case 0x9E:
	case 0x9F:
	case 0xA0:
	case 0xA1:
	case 0xA2:
	case 0xA3:
	case 0xA4:
	case 0xA5:
	case 0xA6:
	case 0xA7:
	case 0xA8:
	case 0xA9:
	case 0xAA:
	case 0xAB:
	case 0xAC:
	case 0xAD:
	case 0xAE:
	case 0xAF:
	case 0xB0:
	case 0xB1:
	case 0xB2:
	case 0xB3:
	case 0xB4:
	case 0xB5:
	case 0xB6:
	case 0xB7:
	case 0xB8:
	case 0xB9:
	case 0xBA:
	case 0xBB:
	case 0xBC:
	case 0xBD:
	case 0xBE:
	case 0xBF:	goto yy129;
	default:	goto yy6;
	}
yy83:
	++s;
	re2c_scanner_m_c = yycSTARTEXP;
#line 88 "re2c-scanner-m.re"
	{ return TOKEN_NOT_EQUAL; }
#line 891 "re2c-scanner-m.cc"
yy85:
	++s;
	if (lim <= s) return false;
	yych = *s;
yy86:
	switch (yych) {
	case 0x00:
	case '\n':	goto yy87;
	case '"':	goto yy88;
	case '\\':	goto yy90;
	default:	goto yy85;
	}
yy87:
	s = m;
	switch (yyaccept) {
	case 0: 	goto yy6;
	case 1: 	goto yy40;
	case 2: 	goto yy44;
	case 3: 	goto yy63;
	case 4: 	goto yy109;
	default:	goto yy89;
	}
yy88:
	++s;
yy89:
	re2c_scanner_m_c = yycSTARTEXP;
#line 65 "re2c-scanner-m.re"
	{ return TOKEN_STRING; }
#line 920 "re2c-scanner-m.cc"
yy90:
	++s;
	if (lim <= s) return false;
	yych = *s;
	switch (yych) {
	case 0x00:
	case '\n':	goto yy87;
	case '"':	goto yy139;
	case '\\':	goto yy90;
	default:	goto yy85;
	}
yy92:
	++s;
	re2c_scanner_m_c = yycSTARTEXP;
#line 100 "re2c-scanner-m.re"
	{ return TOKEN_DOUBLE_AND; }
#line 937 "re2c-scanner-m.cc"
yy94:
	++s;
	re2c_scanner_m_c = yycSTARTEXP;
#line 123 "re2c-scanner-m.re"
	{ return TOKEN_MULT_EQUAL; }
#line 943 "re2c-scanner-m.cc"
yy96:
	++s;
	re2c_scanner_m_c = yycSTARTEXP;
#line 119 "re2c-scanner-m.re"
	{ return TOKEN_PLUS_EQUAL; }
#line 949 "re2c-scanner-m.cc"
yy98:
	++s;
	re2c_scanner_m_c = yycSTARTEXP;
#line 120 "re2c-scanner-m.re"
	{ return TOKEN_MINUS_EQUAL; }
#line 955 "re2c-scanner-m.cc"
yy100:
	++s;
	re2c_scanner_m_c = yycSTARTEXP;
#line 117 "re2c-scanner-m.re"
	{ return TOKEN_DOTAPOS; }
#line 961 "re2c-scanner-m.cc"
yy102:
	yych = *++s;
	switch (yych) {
	case '=':	goto yy140;
	default:	goto yy103;
	}
yy103:
	re2c_scanner_m_c = yycSTARTEXP;
#line 113 "re2c-scanner-m.re"
	{ return TOKEN_DOTMULT; }
#line 972 "re2c-scanner-m.cc"
yy104:
	yych = *++s;
	switch (yych) {
	case '.':	goto yy142;
	default:	goto yy87;
	}
yy105:
	yych = *++s;
	switch (yych) {
	case '=':	goto yy145;
	default:	goto yy106;
	}
yy106:
	re2c_scanner_m_c = yycSTARTEXP;
#line 114 "re2c-scanner-m.re"
	{ return TOKEN_DOTDIV; }
#line 989 "re2c-scanner-m.cc"
yy107:
	yyaccept = 4;
	m = ++s;
	if ((lim - s) < 3) return false;
	yych = *s;
	switch (yych) {
	case '0':
	case '1':
	case '2':
	case '3':
	case '4':
	case '5':
	case '6':
	case '7':
	case '8':
	case '9':	goto yy107;
	case 'D':
	case 'E':
	case 'd':
	case 'e':	goto yy117;
	case 'F':
	case 'I':
	case 'L':
	case 'f':
	case 'i':
	case 'l':	goto yy118;
	default:	goto yy109;
	}
yy109:
#line 67 "re2c-scanner-m.re"
	{ return TOKEN_FLOAT; }
#line 1021 "re2c-scanner-m.cc"
yy110:
	yych = *++s;
	switch (yych) {
	case '=':	goto yy147;
	default:	goto yy111;
	}
yy111:
	re2c_scanner_m_c = yycSTARTEXP;
#line 115 "re2c-scanner-m.re"
	{ return TOKEN_DOTBACKSLASH; }
#line 1032 "re2c-scanner-m.cc"
yy112:
	yych = *++s;
	switch (yych) {
	case '=':	goto yy149;
	default:	goto yy113;
	}
yy113:
	re2c_scanner_m_c = yycSTARTEXP;
#line 116 "re2c-scanner-m.re"
	{ return TOKEN_DOTPOW; }
#line 1043 "re2c-scanner-m.cc"
yy114:
	++s;
	re2c_scanner_m_c = yycSTARTEXP;
#line 121 "re2c-scanner-m.re"
	{ return TOKEN_DIV_EQUAL; }
#line 1049 "re2c-scanner-m.cc"
yy116:
	yych = *++s;
	switch (yych) {
	case '*':
	case '.':
	case '/':
	case '\\':
	case '^':	goto yy87;
	case '0':
	case '1':
	case '2':
	case '3':
	case '4':
	case '5':
	case '6':
	case '7':
	case '8':
	case '9':	goto yy107;
	default:	goto yy151;
	}
yy117:
	yych = *++s;
	switch (yych) {
	case '+':
	case '-':	goto yy153;
	case '0':
	case '1':
	case '2':
	case '3':
	case '4':
	case '5':
	case '6':
	case '7':
	case '8':
	case '9':	goto yy154;
	default:	goto yy87;
	}
yy118:
	++s;
	goto yy109;
yy119:
	++s;
	if (lim <= s) return false;
	yych = *s;
	switch (yych) {
	case 'L':
	case 'U':
	case 'l':
	case 'u':	goto yy119;
	default:	goto yy44;
	}
yy121:
	yych = *++s;
	switch (yych) {
	case '0':
	case '1':
	case '2':
	case '3':
	case '4':
	case '5':
	case '6':
	case '7':
	case '8':
	case '9':	goto yy156;
	default:	goto yy87;
	}
yy122:
	++s;
	re2c_scanner_m_c = yycSTARTEXP;
#line 84 "re2c-scanner-m.re"
	{ return TOKEN_LE; }
#line 1121 "re2c-scanner-m.cc"
yy124:
	++s;
	re2c_scanner_m_c = yycSTARTEXP;
#line 87 "re2c-scanner-m.re"
	{ return TOKEN_DOUBLE_EQUAL; }
#line 1127 "re2c-scanner-m.cc"
yy126:
	++s;
	re2c_scanner_m_c = yycSTARTEXP;
#line 85 "re2c-scanner-m.re"
	{ return TOKEN_GE; }
#line 1133 "re2c-scanner-m.cc"
yy128:
	++s;
	if (lim <= s) return false;
	yych = *s;
	switch (yych) {
	case 0x80:
	case 0x81:
	case 0x82:
	case 0x83:
	case 0x84:
	case 0x85:
	case 0x86:
	case 0x87:
	case 0x88:
	case 0x89:
	case 0x8A:
	case 0x8B:
	case 0x8C:
	case 0x8D:
	case 0x8E:
	case 0x8F:
	case 0x90:
	case 0x91:
	case 0x92:
	case 0x93:
	case 0x94:
	case 0x95:
	case 0x96:
	case 0x97:
	case 0x98:
	case 0x99:
	case 0x9A:
	case 0x9B:
	case 0x9C:
	case 0x9D:
	case 0x9E:
	case 0x9F:
	case 0xA0:
	case 0xA1:
	case 0xA2:
	case 0xA3:
	case 0xA4:
	case 0xA5:
	case 0xA6:
	case 0xA7:
	case 0xA8:
	case 0xA9:
	case 0xAA:
	case 0xAB:
	case 0xAC:
	case 0xAD:
	case 0xAE:
	case 0xAF:
	case 0xB0:
	case 0xB1:
	case 0xB2:
	case 0xB3:
	case 0xB4:
	case 0xB5:
	case 0xB6:
	case 0xB7:
	case 0xB8:
	case 0xB9:
	case 0xBA:
	case 0xBB:
	case 0xBC:
	case 0xBD:
	case 0xBE:
	case 0xBF:	goto yy61;
	default:	goto yy87;
	}
yy129:
	++s;
	if (lim <= s) return false;
	yych = *s;
	switch (yych) {
	case 0x80:
	case 0x81:
	case 0x82:
	case 0x83:
	case 0x84:
	case 0x85:
	case 0x86:
	case 0x87:
	case 0x88:
	case 0x89:
	case 0x8A:
	case 0x8B:
	case 0x8C:
	case 0x8D:
	case 0x8E:
	case 0x8F:
	case 0x90:
	case 0x91:
	case 0x92:
	case 0x93:
	case 0x94:
	case 0x95:
	case 0x96:
	case 0x97:
	case 0x98:
	case 0x99:
	case 0x9A:
	case 0x9B:
	case 0x9C:
	case 0x9D:
	case 0x9E:
	case 0x9F:
	case 0xA0:
	case 0xA1:
	case 0xA2:
	case 0xA3:
	case 0xA4:
	case 0xA5:
	case 0xA6:
	case 0xA7:
	case 0xA8:
	case 0xA9:
	case 0xAA:
	case 0xAB:
	case 0xAC:
	case 0xAD:
	case 0xAE:
	case 0xAF:
	case 0xB0:
	case 0xB1:
	case 0xB2:
	case 0xB3:
	case 0xB4:
	case 0xB5:
	case 0xB6:
	case 0xB7:
	case 0xB8:
	case 0xB9:
	case 0xBA:
	case 0xBB:
	case 0xBC:
	case 0xBD:
	case 0xBE:
	case 0xBF:	goto yy128;
	default:	goto yy87;
	}
yy130:
	++s;
	if (lim <= s) return false;
	yych = *s;
	switch (yych) {
	case 0x80:
	case 0x81:
	case 0x82:
	case 0x83:
	case 0x84:
	case 0x85:
	case 0x86:
	case 0x87:
	case 0x88:
	case 0x89:
	case 0x8A:
	case 0x8B:
	case 0x8C:
	case 0x8D:
	case 0x8E:
	case 0x8F:
	case 0x90:
	case 0x91:
	case 0x92:
	case 0x93:
	case 0x94:
	case 0x95:
	case 0x96:
	case 0x97:
	case 0x98:
	case 0x99:
	case 0x9A:
	case 0x9B:
	case 0x9C:
	case 0x9D:
	case 0x9E:
	case 0x9F:
	case 0xA0:
	case 0xA1:
	case 0xA2:
	case 0xA3:
	case 0xA4:
	case 0xA5:
	case 0xA6:
	case 0xA7:
	case 0xA8:
	case 0xA9:
	case 0xAA:
	case 0xAB:
	case 0xAC:
	case 0xAD:
	case 0xAE:
	case 0xAF:
	case 0xB0:
	case 0xB1:
	case 0xB2:
	case 0xB3:
	case 0xB4:
	case 0xB5:
	case 0xB6:
	case 0xB7:
	case 0xB8:
	case 0xB9:
	case 0xBA:
	case 0xBB:
	case 0xBC:
	case 0xBD:
	case 0xBE:
	case 0xBF:	goto yy129;
	default:	goto yy87;
	}
yy131:
	++s;
	re2c_scanner_m_c = yycSTARTEXP;
#line 122 "re2c-scanner-m.re"
	{ return TOKEN_BACKSLASH_EQUAL; }
#line 1352 "re2c-scanner-m.cc"
yy133:
	++s;
	re2c_scanner_m_c = yycSTARTEXP;
#line 124 "re2c-scanner-m.re"
	{ return TOKEN_POW_EQUAL; }
#line 1358 "re2c-scanner-m.cc"
yy135:
	++s;
	re2c_scanner_m_c = yycSTARTEXP;
#line 102 "re2c-scanner-m.re"
	{ return TOKEN_DOUBLE_OR; }
#line 1364 "re2c-scanner-m.cc"
yy137:
	++s;
	re2c_scanner_m_c = yycSTARTEXP;
#line 89 "re2c-scanner-m.re"
	{ return TOKEN_NOT_EQUAL; }
#line 1370 "re2c-scanner-m.cc"
yy139:
	yyaccept = 5;
	m = ++s;
	if (lim <= s) return false;
	yych = *s;
	switch (yych) {
	case 0x00:
	case '\n':	goto yy89;
	case '"':	goto yy88;
	case '\\':	goto yy90;
	default:	goto yy85;
	}
yy140:
	++s;
	re2c_scanner_m_c = yycSTARTEXP;
#line 128 "re2c-scanner-m.re"
	{ return TOKEN_DOT_MULT_EQUAL; }
#line 1388 "re2c-scanner-m.cc"
yy142:
	++s;
	if (lim <= s) return false;
	yych = *s;
	switch (yych) {
	case '.':	goto yy142;
	default:	goto yy144;
	}
yy144:
	re2c_scanner_m_c = yycSTARTEXP;
#line 141 "re2c-scanner-m.re"
	{ return TOKEN_TRIPLE_DOT; }
#line 1401 "re2c-scanner-m.cc"
yy145:
	++s;
	re2c_scanner_m_c = yycSTARTEXP;
#line 126 "re2c-scanner-m.re"
	{ return TOKEN_DOT_DIV_EQUAL; }
#line 1407 "re2c-scanner-m.cc"
yy147:
	++s;
	re2c_scanner_m_c = yycSTARTEXP;
#line 127 "re2c-scanner-m.re"
	{ return TOKEN_DOT_BACKSLASH_EQUAL; }
#line 1413 "re2c-scanner-m.cc"
yy149:
	++s;
	re2c_scanner_m_c = yycSTARTEXP;
#line 129 "re2c-scanner-m.re"
	{ return TOKEN_DOT_POW_EQUAL; }
#line 1419 "re2c-scanner-m.cc"
yy151:
	++s;
	s -= 1;
#line 68 "re2c-scanner-m.re"
	{ return TOKEN_FLOAT; }
#line 1425 "re2c-scanner-m.cc"
yy153:
	yych = *++s;
	switch (yych) {
	case '0':
	case '1':
	case '2':
	case '3':
	case '4':
	case '5':
	case '6':
	case '7':
	case '8':
	case '9':	goto yy154;
	default:	goto yy87;
	}
yy154:
	++s;
	if (lim <= s) return false;
	yych = *s;
	switch (yych) {
	case '0':
	case '1':
	case '2':
	case '3':
	case '4':
	case '5':
	case '6':
	case '7':
	case '8':
	case '9':	goto yy154;
	case 'F':
	case 'I':
	case 'L':
	case 'f':
	case 'i':
	case 'l':	goto yy118;
	default:	goto yy109;
	}
yy156:
	++s;
	if (lim <= s) return false;
	yych = *s;
	switch (yych) {
	case '0':
	case '1':
	case '2':
	case '3':
	case '4':
	case '5':
	case '6':
	case '7':
	case '8':
	case '9':	goto yy156;
	case 'L':
	case 'U':
	case 'l':
	case 'u':	goto yy119;
	default:	goto yy44;
	}
/* *********************************** */
yyc_STARTEXP:
	if ((lim - s) < 4) return false;
	yych = *s;
	switch (yych) {
	case 0x00:	goto yy160;
	case '\t':	goto yy164;
	case '\n':	goto yy166;
	case '\r':	goto yy168;
	case ' ':	goto yy170;
	case '!':	goto yy173;
	case '"':	goto yy175;
	case '#':	goto yy176;
	case '%':	goto yy178;
	case '&':	goto yy180;
	case '\'':	goto yy182;
	case '(':	goto yy184;
	case ')':	goto yy186;
	case '*':	goto yy188;
	case '+':	goto yy190;
	case ',':	goto yy192;
	case '-':	goto yy194;
	case '.':	goto yy196;
	case '/':	goto yy198;
	case '0':	goto yy200;
	case '1':
	case '2':
	case '3':
	case '4':
	case '5':
	case '6':
	case '7':
	case '8':
	case '9':	goto yy202;
	case ':':	goto yy204;
	case ';':	goto yy206;
	case '<':	goto yy208;
	case '=':	goto yy210;
	case '>':	goto yy212;
	case '?':	goto yy214;
	case '@':	goto yy216;
	case 'A':
	case 'B':
	case 'C':
	case 'D':
	case 'E':
	case 'F':
	case 'G':
	case 'H':
	case 'I':
	case 'J':
	case 'K':
	case 'L':
	case 'M':
	case 'N':
	case 'O':
	case 'P':
	case 'Q':
	case 'R':
	case 'S':
	case 'T':
	case 'U':
	case 'V':
	case 'W':
	case 'X':
	case 'Y':
	case 'Z':
	case '_':
	case 'a':
	case 'b':
	case 'c':
	case 'd':
	case 'e':
	case 'f':
	case 'g':
	case 'h':
	case 'i':
	case 'j':
	case 'k':
	case 'l':
	case 'm':
	case 'n':
	case 'o':
	case 'p':
	case 'q':
	case 'r':
	case 's':
	case 't':
	case 'u':
	case 'v':
	case 'w':
	case 'x':
	case 'y':
	case 'z':	goto yy218;
	case '[':	goto yy221;
	case '\\':	goto yy223;
	case ']':	goto yy225;
	case '^':	goto yy227;
	case '{':	goto yy229;
	case '|':	goto yy231;
	case '}':	goto yy233;
	case '~':	goto yy235;
	case 0xC0:
	case 0xC1:
	case 0xC2:
	case 0xC3:
	case 0xC4:
	case 0xC5:
	case 0xC6:
	case 0xC7:
	case 0xC8:
	case 0xC9:
	case 0xCA:
	case 0xCB:
	case 0xCC:
	case 0xCD:
	case 0xCE:
	case 0xCF:
	case 0xD0:
	case 0xD1:
	case 0xD2:
	case 0xD3:
	case 0xD4:
	case 0xD5:
	case 0xD6:
	case 0xD7:
	case 0xD8:
	case 0xD9:
	case 0xDA:
	case 0xDB:
	case 0xDC:
	case 0xDD:
	case 0xDE:
	case 0xDF:	goto yy237;
	case 0xE0:
	case 0xE1:
	case 0xE2:
	case 0xE3:
	case 0xE4:
	case 0xE5:
	case 0xE6:
	case 0xE7:
	case 0xE8:
	case 0xE9:
	case 0xEA:
	case 0xEB:
	case 0xEC:
	case 0xED:
	case 0xEE:
	case 0xEF:	goto yy238;
	case 0xF0:
	case 0xF1:
	case 0xF2:
	case 0xF3:
	case 0xF4:
	case 0xF5:
	case 0xF6:
	case 0xF7:	goto yy239;
	default:	goto yy162;
	}
yy160:
	++s;
	re2c_scanner_m_c = yycINITIAL;
#line 143 "re2c-scanner-m.re"
	{ return TOKEN_EOF; }
#line 1650 "re2c-scanner-m.cc"
yy162:
	++s;
yy163:
	re2c_scanner_m_c = yycINITIAL;
#line 145 "re2c-scanner-m.re"
	{ return TOKEN_ILLEGAL_CHAR; }
#line 1657 "re2c-scanner-m.cc"
yy164:
	++s;
#line 137 "re2c-scanner-m.re"
	{ return TOKEN_TAB; }
#line 1662 "re2c-scanner-m.cc"
yy166:
	++s;
#line 136 "re2c-scanner-m.re"
	{ return TOKEN_NEWLINE; }
#line 1667 "re2c-scanner-m.cc"
yy168:
	++s;
#line 135 "re2c-scanner-m.re"
	{ return TOKEN_CRETURN; }
#line 1672 "re2c-scanner-m.cc"
yy170:
	++s;
	if (lim <= s) return false;
	yych = *s;
	switch (yych) {
	case ' ':	goto yy170;
	default:	goto yy172;
	}
yy172:
#line 138 "re2c-scanner-m.re"
	{ return TOKEN_SPACE; }
#line 1684 "re2c-scanner-m.cc"
yy173:
	yych = *++s;
	switch (yych) {
	case '=':	goto yy240;
	default:	goto yy174;
	}
yy174:
#line 92 "re2c-scanner-m.re"
	{ return TOKEN_EXCLAM; }
#line 1694 "re2c-scanner-m.cc"
yy175:
	yyaccept = 0;
	yych = *(m = ++s);
	switch (yych) {
	case 0x00:
	case '\n':	goto yy163;
	default:	goto yy243;
	}
yy176:
	++s;
	re2c_scanner_m_c = yycINITIAL;
#line 133 "re2c-scanner-m.re"
	{ return TOKEN_HASH; }
#line 1708 "re2c-scanner-m.cc"
yy178:
	++s;
#line 108 "re2c-scanner-m.re"
	{ return TOKEN_MOD; }
#line 1713 "re2c-scanner-m.cc"
yy180:
	yych = *++s;
	switch (yych) {
	case '&':	goto yy249;
	default:	goto yy181;
	}
yy181:
#line 99 "re2c-scanner-m.re"
	{ return TOKEN_AND; }
#line 1723 "re2c-scanner-m.cc"
yy182:
	yyaccept = 1;
	yych = *(m = ++s);
	switch (yych) {
	case 0x00:
	case '\n':	goto yy183;
	default:	goto yy252;
	}
yy183:
#line 111 "re2c-scanner-m.re"
	{ return TOKEN_APOS; }
#line 1735 "re2c-scanner-m.cc"
yy184:
	++s;
#line 70 "re2c-scanner-m.re"
	{ return TOKEN_L_PAREN; }
#line 1740 "re2c-scanner-m.cc"
yy186:
	++s;
	re2c_scanner_m_c = yycINITIAL;
#line 71 "re2c-scanner-m.re"
	{ return TOKEN_R_PAREN; }
#line 1746 "re2c-scanner-m.cc"
yy188:
	yych = *++s;
	switch (yych) {
	case '=':	goto yy255;
	default:	goto yy189;
	}
yy189:
#line 107 "re2c-scanner-m.re"
	{ return TOKEN_MULT; }
#line 1756 "re2c-scanner-m.cc"
yy190:
	yych = *++s;
	switch (yych) {
	case '=':	goto yy257;
	default:	goto yy191;
	}
yy191:
#line 104 "re2c-scanner-m.re"
	{ return TOKEN_PLUS; }
#line 1766 "re2c-scanner-m.cc"
yy192:
	++s;
#line 95 "re2c-scanner-m.re"
	{ return TOKEN_COMMA; }
#line 1771 "re2c-scanner-m.cc"
yy194:
	yych = *++s;
	switch (yych) {
	case '=':	goto yy259;
	default:	goto yy195;
	}
yy195:
#line 105 "re2c-scanner-m.re"
	{ return TOKEN_MINUS; }
#line 1781 "re2c-scanner-m.cc"
yy196:
	yyaccept = 2;
	yych = *(m = ++s);
	switch (yych) {
	case '\'':	goto yy261;
	case '*':	goto yy263;
	case '.':	goto yy265;
	case '/':	goto yy266;
	case '0':
	case '1':
	case '2':
	case '3':
	case '4':
	case '5':
	case '6':
	case '7':
	case '8':
	case '9':	goto yy268;
	case '\\':	goto yy271;
	case '^':	goto yy273;
	default:	goto yy197;
	}
yy197:
#line 97 "re2c-scanner-m.re"
	{ return TOKEN_FULL_STOP; }
#line 1807 "re2c-scanner-m.cc"
yy198:
	yych = *++s;
	switch (yych) {
	case '=':	goto yy275;
	default:	goto yy199;
	}
yy199:
#line 106 "re2c-scanner-m.re"
	{ return TOKEN_DIV; }
#line 1817 "re2c-scanner-m.cc"
yy200:
	yyaccept = 3;
	yych = *(m = ++s);
	switch (yych) {
	case 'x':	goto yy282;
	default:	goto yy203;
	}
yy201:
	re2c_scanner_m_c = yycINITIAL;
#line 64 "re2c-scanner-m.re"
	{ return TOKEN_INTEGER; }
#line 1829 "re2c-scanner-m.cc"
yy202:
	yyaccept = 3;
	m = ++s;
	if ((lim - s) < 3) return false;
	yych = *s;
yy203:
	switch (yych) {
	case '.':	goto yy277;
	case '0':
	case '1':
	case '2':
	case '3':
	case '4':
	case '5':
	case '6':
	case '7':
	case '8':
	case '9':	goto yy202;
	case 'D':
	case 'E':
	case 'd':
	case 'e':	goto yy278;
	case 'F':
	case 'I':
	case 'f':
	case 'i':	goto yy279;
	case 'L':
	case 'U':
	case 'l':
	case 'u':	goto yy280;
	default:	goto yy201;
	}
yy204:
	++s;
#line 94 "re2c-scanner-m.re"
	{ return TOKEN_COLON; }
#line 1866 "re2c-scanner-m.cc"
yy206:
	++s;
#line 96 "re2c-scanner-m.re"
	{ return TOKEN_SEMICOLON; }
#line 1871 "re2c-scanner-m.cc"
yy208:
	yych = *++s;
	switch (yych) {
	case '=':	goto yy283;
	default:	goto yy209;
	}
yy209:
#line 81 "re2c-scanner-m.re"
	{ return TOKEN_LESS; }
#line 1881 "re2c-scanner-m.cc"
yy210:
	yych = *++s;
	switch (yych) {
	case '=':	goto yy285;
	default:	goto yy211;
	}
yy211:
#line 79 "re2c-scanner-m.re"
	{ return TOKEN_EQUAL; }
#line 1891 "re2c-scanner-m.cc"
yy212:
	yych = *++s;
	switch (yych) {
	case '=':	goto yy287;
	default:	goto yy213;
	}
yy213:
#line 82 "re2c-scanner-m.re"
	{ return TOKEN_GREATER; }
#line 1901 "re2c-scanner-m.cc"
yy214:
	++s;
#line 93 "re2c-scanner-m.re"
	{ return TOKEN_QUESTION; }
#line 1906 "re2c-scanner-m.cc"
yy216:
	++s;
#line 131 "re2c-scanner-m.re"
	{ return TOKEN_AT; }
#line 1911 "re2c-scanner-m.cc"
yy218:
	yyaccept = 4;
	m = ++s;
	if (lim <= s) return false;
	yych = *s;
	switch (yych) {
	case '0':
	case '1':
	case '2':
	case '3':
	case '4':
	case '5':
	case '6':
	case '7':
	case '8':
	case '9':
	case 'A':
	case 'B':
	case 'C':
	case 'D':
	case 'E':
	case 'F':
	case 'G':
	case 'H':
	case 'I':
	case 'J':
	case 'K':
	case 'L':
	case 'M':
	case 'N':
	case 'O':
	case 'P':
	case 'Q':
	case 'R':
	case 'S':
	case 'T':
	case 'U':
	case 'V':
	case 'W':
	case 'X':
	case 'Y':
	case 'Z':
	case '_':
	case 'a':
	case 'b':
	case 'c':
	case 'd':
	case 'e':
	case 'f':
	case 'g':
	case 'h':
	case 'i':
	case 'j':
	case 'k':
	case 'l':
	case 'm':
	case 'n':
	case 'o':
	case 'p':
	case 'q':
	case 'r':
	case 's':
	case 't':
	case 'u':
	case 'v':
	case 'w':
	case 'x':
	case 'y':
	case 'z':	goto yy218;
	case 0xC0:
	case 0xC1:
	case 0xC2:
	case 0xC3:
	case 0xC4:
	case 0xC5:
	case 0xC6:
	case 0xC7:
	case 0xC8:
	case 0xC9:
	case 0xCA:
	case 0xCB:
	case 0xCC:
	case 0xCD:
	case 0xCE:
	case 0xCF:
	case 0xD0:
	case 0xD1:
	case 0xD2:
	case 0xD3:
	case 0xD4:
	case 0xD5:
	case 0xD6:
	case 0xD7:
	case 0xD8:
	case 0xD9:
	case 0xDA:
	case 0xDB:
	case 0xDC:
	case 0xDD:
	case 0xDE:
	case 0xDF:	goto yy289;
	case 0xE0:
	case 0xE1:
	case 0xE2:
	case 0xE3:
	case 0xE4:
	case 0xE5:
	case 0xE6:
	case 0xE7:
	case 0xE8:
	case 0xE9:
	case 0xEA:
	case 0xEB:
	case 0xEC:
	case 0xED:
	case 0xEE:
	case 0xEF:	goto yy290;
	case 0xF0:
	case 0xF1:
	case 0xF2:
	case 0xF3:
	case 0xF4:
	case 0xF5:
	case 0xF6:
	case 0xF7:	goto yy291;
	default:	goto yy220;
	}
yy220:
	re2c_scanner_m_c = yycINITIAL;
#line 139 "re2c-scanner-m.re"
	{ return TOKEN_IDENTIFIER; }
#line 2043 "re2c-scanner-m.cc"
yy221:
	++s;
#line 76 "re2c-scanner-m.re"
	{ return TOKEN_L_BRACKET; }
#line 2048 "re2c-scanner-m.cc"
yy223:
	yych = *++s;
	switch (yych) {
	case '=':	goto yy292;
	default:	goto yy224;
	}
yy224:
#line 109 "re2c-scanner-m.re"
	{ return TOKEN_BACKSLASH; }
#line 2058 "re2c-scanner-m.cc"
yy225:
	++s;
	re2c_scanner_m_c = yycINITIAL;
#line 77 "re2c-scanner-m.re"
	{ return TOKEN_R_BRACKET; }
#line 2064 "re2c-scanner-m.cc"
yy227:
	yych = *++s;
	switch (yych) {
	case '=':	goto yy294;
	default:	goto yy228;
	}
yy228:
#line 110 "re2c-scanner-m.re"
	{ return TOKEN_POW; }
#line 2074 "re2c-scanner-m.cc"
yy229:
	++s;
#line 73 "re2c-scanner-m.re"
	{ return TOKEN_L_BRACE; }
#line 2079 "re2c-scanner-m.cc"
yy231:
	yych = *++s;
	switch (yych) {
	case '|':	goto yy296;
	default:	goto yy232;
	}
yy232:
#line 101 "re2c-scanner-m.re"
	{ return TOKEN_OR; }
#line 2089 "re2c-scanner-m.cc"
yy233:
	++s;
	re2c_scanner_m_c = yycINITIAL;
#line 74 "re2c-scanner-m.re"
	{ return TOKEN_R_BRACE; }
#line 2095 "re2c-scanner-m.cc"
yy235:
	yych = *++s;
	switch (yych) {
	case '=':	goto yy298;
	default:	goto yy236;
	}
yy236:
#line 91 "re2c-scanner-m.re"
	{ return TOKEN_TILDE; }
#line 2105 "re2c-scanner-m.cc"
yy237:
	yych = *++s;
	switch (yych) {
	case 0x80:
	case 0x81:
	case 0x82:
	case 0x83:
	case 0x84:
	case 0x85:
	case 0x86:
	case 0x87:
	case 0x88:
	case 0x89:
	case 0x8A:
	case 0x8B:
	case 0x8C:
	case 0x8D:
	case 0x8E:
	case 0x8F:
	case 0x90:
	case 0x91:
	case 0x92:
	case 0x93:
	case 0x94:
	case 0x95:
	case 0x96:
	case 0x97:
	case 0x98:
	case 0x99:
	case 0x9A:
	case 0x9B:
	case 0x9C:
	case 0x9D:
	case 0x9E:
	case 0x9F:
	case 0xA0:
	case 0xA1:
	case 0xA2:
	case 0xA3:
	case 0xA4:
	case 0xA5:
	case 0xA6:
	case 0xA7:
	case 0xA8:
	case 0xA9:
	case 0xAA:
	case 0xAB:
	case 0xAC:
	case 0xAD:
	case 0xAE:
	case 0xAF:
	case 0xB0:
	case 0xB1:
	case 0xB2:
	case 0xB3:
	case 0xB4:
	case 0xB5:
	case 0xB6:
	case 0xB7:
	case 0xB8:
	case 0xB9:
	case 0xBA:
	case 0xBB:
	case 0xBC:
	case 0xBD:
	case 0xBE:
	case 0xBF:	goto yy218;
	default:	goto yy163;
	}
yy238:
	yyaccept = 0;
	yych = *(m = ++s);
	switch (yych) {
	case 0x80:
	case 0x81:
	case 0x82:
	case 0x83:
	case 0x84:
	case 0x85:
	case 0x86:
	case 0x87:
	case 0x88:
	case 0x89:
	case 0x8A:
	case 0x8B:
	case 0x8C:
	case 0x8D:
	case 0x8E:
	case 0x8F:
	case 0x90:
	case 0x91:
	case 0x92:
	case 0x93:
	case 0x94:
	case 0x95:
	case 0x96:
	case 0x97:
	case 0x98:
	case 0x99:
	case 0x9A:
	case 0x9B:
	case 0x9C:
	case 0x9D:
	case 0x9E:
	case 0x9F:
	case 0xA0:
	case 0xA1:
	case 0xA2:
	case 0xA3:
	case 0xA4:
	case 0xA5:
	case 0xA6:
	case 0xA7:
	case 0xA8:
	case 0xA9:
	case 0xAA:
	case 0xAB:
	case 0xAC:
	case 0xAD:
	case 0xAE:
	case 0xAF:
	case 0xB0:
	case 0xB1:
	case 0xB2:
	case 0xB3:
	case 0xB4:
	case 0xB5:
	case 0xB6:
	case 0xB7:
	case 0xB8:
	case 0xB9:
	case 0xBA:
	case 0xBB:
	case 0xBC:
	case 0xBD:
	case 0xBE:
	case 0xBF:	goto yy289;
	default:	goto yy163;
	}
yy239:
	yyaccept = 0;
	yych = *(m = ++s);
	switch (yych) {
	case 0x80:
	case 0x81:
	case 0x82:
	case 0x83:
	case 0x84:
	case 0x85:
	case 0x86:
	case 0x87:
	case 0x88:
	case 0x89:
	case 0x8A:
	case 0x8B:
	case 0x8C:
	case 0x8D:
	case 0x8E:
	case 0x8F:
	case 0x90:
	case 0x91:
	case 0x92:
	case 0x93:
	case 0x94:
	case 0x95:
	case 0x96:
	case 0x97:
	case 0x98:
	case 0x99:
	case 0x9A:
	case 0x9B:
	case 0x9C:
	case 0x9D:
	case 0x9E:
	case 0x9F:
	case 0xA0:
	case 0xA1:
	case 0xA2:
	case 0xA3:
	case 0xA4:
	case 0xA5:
	case 0xA6:
	case 0xA7:
	case 0xA8:
	case 0xA9:
	case 0xAA:
	case 0xAB:
	case 0xAC:
	case 0xAD:
	case 0xAE:
	case 0xAF:
	case 0xB0:
	case 0xB1:
	case 0xB2:
	case 0xB3:
	case 0xB4:
	case 0xB5:
	case 0xB6:
	case 0xB7:
	case 0xB8:
	case 0xB9:
	case 0xBA:
	case 0xBB:
	case 0xBC:
	case 0xBD:
	case 0xBE:
	case 0xBF:	goto yy290;
	default:	goto yy163;
	}
yy240:
	++s;
#line 88 "re2c-scanner-m.re"
	{ return TOKEN_NOT_EQUAL; }
#line 2319 "re2c-scanner-m.cc"
yy242:
	++s;
	if (lim <= s) return false;
	yych = *s;
yy243:
	switch (yych) {
	case 0x00:
	case '\n':	goto yy244;
	case '"':	goto yy245;
	case '\\':	goto yy247;
	default:	goto yy242;
	}
yy244:
	s = m;
	switch (yyaccept) {
	case 0: 	goto yy163;
	case 1: 	goto yy183;
	case 2: 	goto yy197;
	case 3: 	goto yy201;
	case 4: 	goto yy220;
	case 5: 	goto yy270;
	default:	goto yy246;
	}
yy245:
	++s;
yy246:
#line 65 "re2c-scanner-m.re"
	{ return TOKEN_STRING; }
#line 2348 "re2c-scanner-m.cc"
yy247:
	++s;
	if (lim <= s) return false;
	yych = *s;
	switch (yych) {
	case 0x00:
	case '\n':	goto yy244;
	case '"':	goto yy300;
	case '\\':	goto yy247;
	default:	goto yy242;
	}
yy249:
	++s;
#line 100 "re2c-scanner-m.re"
	{ return TOKEN_DOUBLE_AND; }
#line 2364 "re2c-scanner-m.cc"
yy251:
	++s;
	if (lim <= s) return false;
	yych = *s;
yy252:
	switch (yych) {
	case 0x00:
	case '\n':	goto yy244;
	case '\'':	goto yy253;
	default:	goto yy251;
	}
yy253:
	++s;
#line 66 "re2c-scanner-m.re"
	{ return TOKEN_STRING; }
#line 2380 "re2c-scanner-m.cc"
yy255:
	++s;
#line 123 "re2c-scanner-m.re"
	{ return TOKEN_MULT_EQUAL; }
#line 2385 "re2c-scanner-m.cc"
yy257:
	++s;
#line 119 "re2c-scanner-m.re"
	{ return TOKEN_PLUS_EQUAL; }
#line 2390 "re2c-scanner-m.cc"
yy259:
	++s;
#line 120 "re2c-scanner-m.re"
	{ return TOKEN_MINUS_EQUAL; }
#line 2395 "re2c-scanner-m.cc"
yy261:
	++s;
#line 117 "re2c-scanner-m.re"
	{ return TOKEN_DOTAPOS; }
#line 2400 "re2c-scanner-m.cc"
yy263:
	yych = *++s;
	switch (yych) {
	case '=':	goto yy301;
	default:	goto yy264;
	}
yy264:
#line 113 "re2c-scanner-m.re"
	{ return TOKEN_DOTMULT; }
#line 2410 "re2c-scanner-m.cc"
yy265:
	yych = *++s;
	switch (yych) {
	case '.':	goto yy303;
	default:	goto yy244;
	}
yy266:
	yych = *++s;
	switch (yych) {
	case '=':	goto yy306;
	default:	goto yy267;
	}
yy267:
#line 114 "re2c-scanner-m.re"
	{ return TOKEN_DOTDIV; }
#line 2426 "re2c-scanner-m.cc"
yy268:
	yyaccept = 5;
	m = ++s;
	if ((lim - s) < 3) return false;
	yych = *s;
	switch (yych) {
	case '0':
	case '1':
	case '2':
	case '3':
	case '4':
	case '5':
	case '6':
	case '7':
	case '8':
	case '9':	goto yy268;
	case 'D':
	case 'E':
	case 'd':
	case 'e':	goto yy278;
	case 'F':
	case 'I':
	case 'L':
	case 'f':
	case 'i':
	case 'l':	goto yy279;
	default:	goto yy270;
	}
yy270:
	re2c_scanner_m_c = yycINITIAL;
#line 67 "re2c-scanner-m.re"
	{ return TOKEN_FLOAT; }
#line 2459 "re2c-scanner-m.cc"
yy271:
	yych = *++s;
	switch (yych) {
	case '=':	goto yy308;
	default:	goto yy272;
	}
yy272:
#line 115 "re2c-scanner-m.re"
	{ return TOKEN_DOTBACKSLASH; }
#line 2469 "re2c-scanner-m.cc"
yy273:
	yych = *++s;
	switch (yych) {
	case '=':	goto yy310;
	default:	goto yy274;
	}
yy274:
#line 116 "re2c-scanner-m.re"
	{ return TOKEN_DOTPOW; }
#line 2479 "re2c-scanner-m.cc"
yy275:
	++s;
#line 121 "re2c-scanner-m.re"
	{ return TOKEN_DIV_EQUAL; }
#line 2484 "re2c-scanner-m.cc"
yy277:
	yych = *++s;
	switch (yych) {
	case '*':
	case '.':
	case '/':
	case '\\':
	case '^':	goto yy244;
	case '0':
	case '1':
	case '2':
	case '3':
	case '4':
	case '5':
	case '6':
	case '7':
	case '8':
	case '9':	goto yy268;
	default:	goto yy312;
	}
yy278:
	yych = *++s;
	switch (yych) {
	case '+':
	case '-':	goto yy314;
	case '0':
	case '1':
	case '2':
	case '3':
	case '4':
	case '5':
	case '6':
	case '7':
	case '8':
	case '9':	goto yy315;
	default:	goto yy244;
	}
yy279:
	++s;
	goto yy270;
yy280:
	++s;
	if (lim <= s) return false;
	yych = *s;
	switch (yych) {
	case 'L':
	case 'U':
	case 'l':
	case 'u':	goto yy280;
	default:	goto yy201;
	}
yy282:
	yych = *++s;
	switch (yych) {
	case '0':
	case '1':
	case '2':
	case '3':
	case '4':
	case '5':
	case '6':
	case '7':
	case '8':
	case '9':	goto yy317;
	default:	goto yy244;
	}
yy283:
	++s;
#line 84 "re2c-scanner-m.re"
	{ return TOKEN_LE; }
#line 2555 "re2c-scanner-m.cc"
yy285:
	++s;
#line 87 "re2c-scanner-m.re"
	{ return TOKEN_DOUBLE_EQUAL; }
#line 2560 "re2c-scanner-m.cc"
yy287:
	++s;
#line 85 "re2c-scanner-m.re"
	{ return TOKEN_GE; }
#line 2565 "re2c-scanner-m.cc"
yy289:
	++s;
	if (lim <= s) return false;
	yych = *s;
	switch (yych) {
	case 0x80:
	case 0x81:
	case 0x82:
	case 0x83:
	case 0x84:
	case 0x85:
	case 0x86:
	case 0x87:
	case 0x88:
	case 0x89:
	case 0x8A:
	case 0x8B:
	case 0x8C:
	case 0x8D:
	case 0x8E:
	case 0x8F:
	case 0x90:
	case 0x91:
	case 0x92:
	case 0x93:
	case 0x94:
	case 0x95:
	case 0x96:
	case 0x97:
	case 0x98:
	case 0x99:
	case 0x9A:
	case 0x9B:
	case 0x9C:
	case 0x9D:
	case 0x9E:
	case 0x9F:
	case 0xA0:
	case 0xA1:
	case 0xA2:
	case 0xA3:
	case 0xA4:
	case 0xA5:
	case 0xA6:
	case 0xA7:
	case 0xA8:
	case 0xA9:
	case 0xAA:
	case 0xAB:
	case 0xAC:
	case 0xAD:
	case 0xAE:
	case 0xAF:
	case 0xB0:
	case 0xB1:
	case 0xB2:
	case 0xB3:
	case 0xB4:
	case 0xB5:
	case 0xB6:
	case 0xB7:
	case 0xB8:
	case 0xB9:
	case 0xBA:
	case 0xBB:
	case 0xBC:
	case 0xBD:
	case 0xBE:
	case 0xBF:	goto yy218;
	default:	goto yy244;
	}
yy290:
	++s;
	if (lim <= s) return false;
	yych = *s;
	switch (yych) {
	case 0x80:
	case 0x81:
	case 0x82:
	case 0x83:
	case 0x84:
	case 0x85:
	case 0x86:
	case 0x87:
	case 0x88:
	case 0x89:
	case 0x8A:
	case 0x8B:
	case 0x8C:
	case 0x8D:
	case 0x8E:
	case 0x8F:
	case 0x90:
	case 0x91:
	case 0x92:
	case 0x93:
	case 0x94:
	case 0x95:
	case 0x96:
	case 0x97:
	case 0x98:
	case 0x99:
	case 0x9A:
	case 0x9B:
	case 0x9C:
	case 0x9D:
	case 0x9E:
	case 0x9F:
	case 0xA0:
	case 0xA1:
	case 0xA2:
	case 0xA3:
	case 0xA4:
	case 0xA5:
	case 0xA6:
	case 0xA7:
	case 0xA8:
	case 0xA9:
	case 0xAA:
	case 0xAB:
	case 0xAC:
	case 0xAD:
	case 0xAE:
	case 0xAF:
	case 0xB0:
	case 0xB1:
	case 0xB2:
	case 0xB3:
	case 0xB4:
	case 0xB5:
	case 0xB6:
	case 0xB7:
	case 0xB8:
	case 0xB9:
	case 0xBA:
	case 0xBB:
	case 0xBC:
	case 0xBD:
	case 0xBE:
	case 0xBF:	goto yy289;
	default:	goto yy244;
	}
yy291:
	++s;
	if (lim <= s) return false;
	yych = *s;
	switch (yych) {
	case 0x80:
	case 0x81:
	case 0x82:
	case 0x83:
	case 0x84:
	case 0x85:
	case 0x86:
	case 0x87:
	case 0x88:
	case 0x89:
	case 0x8A:
	case 0x8B:
	case 0x8C:
	case 0x8D:
	case 0x8E:
	case 0x8F:
	case 0x90:
	case 0x91:
	case 0x92:
	case 0x93:
	case 0x94:
	case 0x95:
	case 0x96:
	case 0x97:
	case 0x98:
	case 0x99:
	case 0x9A:
	case 0x9B:
	case 0x9C:
	case 0x9D:
	case 0x9E:
	case 0x9F:
	case 0xA0:
	case 0xA1:
	case 0xA2:
	case 0xA3:
	case 0xA4:
	case 0xA5:
	case 0xA6:
	case 0xA7:
	case 0xA8:
	case 0xA9:
	case 0xAA:
	case 0xAB:
	case 0xAC:
	case 0xAD:
	case 0xAE:
	case 0xAF:
	case 0xB0:
	case 0xB1:
	case 0xB2:
	case 0xB3:
	case 0xB4:
	case 0xB5:
	case 0xB6:
	case 0xB7:
	case 0xB8:
	case 0xB9:
	case 0xBA:
	case 0xBB:
	case 0xBC:
	case 0xBD:
	case 0xBE:
	case 0xBF:	goto yy290;
	default:	goto yy244;
	}
yy292:
	++s;
#line 122 "re2c-scanner-m.re"
	{ return TOKEN_BACKSLASH_EQUAL; }
#line 2783 "re2c-scanner-m.cc"
yy294:
	++s;
#line 124 "re2c-scanner-m.re"
	{ return TOKEN_POW_EQUAL; }
#line 2788 "re2c-scanner-m.cc"
yy296:
	++s;
#line 102 "re2c-scanner-m.re"
	{ return TOKEN_DOUBLE_OR; }
#line 2793 "re2c-scanner-m.cc"
yy298:
	++s;
#line 89 "re2c-scanner-m.re"
	{ return TOKEN_NOT_EQUAL; }
#line 2798 "re2c-scanner-m.cc"
yy300:
	yyaccept = 6;
	m = ++s;
	if (lim <= s) return false;
	yych = *s;
	switch (yych) {
	case 0x00:
	case '\n':	goto yy246;
	case '"':	goto yy245;
	case '\\':	goto yy247;
	default:	goto yy242;
	}
yy301:
	++s;
#line 128 "re2c-scanner-m.re"
	{ return TOKEN_DOT_MULT_EQUAL; }
#line 2815 "re2c-scanner-m.cc"
yy303:
	++s;
	if (lim <= s) return false;
	yych = *s;
	switch (yych) {
	case '.':	goto yy303;
	default:	goto yy305;
	}
yy305:
#line 141 "re2c-scanner-m.re"
	{ return TOKEN_TRIPLE_DOT; }
#line 2827 "re2c-scanner-m.cc"
yy306:
	++s;
#line 126 "re2c-scanner-m.re"
	{ return TOKEN_DOT_DIV_EQUAL; }
#line 2832 "re2c-scanner-m.cc"
yy308:
	++s;
#line 127 "re2c-scanner-m.re"
	{ return TOKEN_DOT_BACKSLASH_EQUAL; }
#line 2837 "re2c-scanner-m.cc"
yy310:
	++s;
#line 129 "re2c-scanner-m.re"
	{ return TOKEN_DOT_POW_EQUAL; }
#line 2842 "re2c-scanner-m.cc"
yy312:
	++s;
	s -= 1;
	re2c_scanner_m_c = yycINITIAL;
#line 68 "re2c-scanner-m.re"
	{ return TOKEN_FLOAT; }
#line 2849 "re2c-scanner-m.cc"
yy314:
	yych = *++s;
	switch (yych) {
	case '0':
	case '1':
	case '2':
	case '3':
	case '4':
	case '5':
	case '6':
	case '7':
	case '8':
	case '9':	goto yy315;
	default:	goto yy244;
	}
yy315:
	++s;
	if (lim <= s) return false;
	yych = *s;
	switch (yych) {
	case '0':
	case '1':
	case '2':
	case '3':
	case '4':
	case '5':
	case '6':
	case '7':
	case '8':
	case '9':	goto yy315;
	case 'F':
	case 'I':
	case 'L':
	case 'f':
	case 'i':
	case 'l':	goto yy279;
	default:	goto yy270;
	}
yy317:
	++s;
	if (lim <= s) return false;
	yych = *s;
	switch (yych) {
	case '0':
	case '1':
	case '2':
	case '3':
	case '4':
	case '5':
	case '6':
	case '7':
	case '8':
	case '9':	goto yy317;
	case 'L':
	case 'U':
	case 'l':
	case 'u':	goto yy280;
	default:	goto yy201;
	}
}
#line 147 "re2c-scanner-m.re"

}

/* Local Variables: */
/* mode: c */
/* coding: latin-1 */
/* End: */
