/* Generated by re2c 1.1.1 on Fri Nov 16 20:25:22 2018 */
#line 1 "re2c-scanner-r.re"
/*
This file is part of P2X.
Copyright © 2018 Johannes Willkomm
See the file p2x.cc for copying conditions.
*/

#include "token.ncd.enum.hh"
#include <string.h>

#define YYMAXFILL 4


typedef unsigned char uint8_t;

int re2c_scanner_r_lex(const uint8_t *&s, const uint8_t *&m, uint8_t const * lim)
{

  

  lim += YYMAXFILL;

    
#line 26 "re2c-scanner-r.cc"
{
	uint8_t yych;
	unsigned int yyaccept = 0;
	if ((lim - s) < 4) return false;
	yych = *s;
	switch (yych) {
	case 0x00:	goto yy2;
	case '\t':	goto yy6;
	case '\n':	goto yy8;
	case '\r':	goto yy10;
	case ' ':	goto yy12;
	case '!':	goto yy15;
	case '"':	goto yy17;
	case '#':	goto yy19;
	case '$':	goto yy21;
	case '%':	goto yy23;
	case '&':	goto yy25;
	case '\'':	goto yy27;
	case '(':	goto yy29;
	case ')':	goto yy31;
	case '*':	goto yy33;
	case '+':	goto yy35;
	case ',':	goto yy37;
	case '-':	goto yy39;
	case '.':	goto yy41;
	case '/':	goto yy43;
	case '0':	goto yy45;
	case '1':
	case '2':
	case '3':
	case '4':
	case '5':
	case '6':
	case '7':
	case '8':
	case '9':	goto yy47;
	case ':':	goto yy49;
	case ';':	goto yy51;
	case '<':	goto yy53;
	case '=':	goto yy55;
	case '>':	goto yy57;
	case '?':	goto yy59;
	case '@':	goto yy61;
	case 'A':
	case 'B':
	case 'C':
	case 'D':
	case 'E':
	case 'F':
	case 'G':
	case 'H':
	case 'I':
	case 'J':
	case 'K':
	case 'L':
	case 'M':
	case 'N':
	case 'O':
	case 'P':
	case 'Q':
	case 'R':
	case 'S':
	case 'T':
	case 'U':
	case 'V':
	case 'W':
	case 'X':
	case 'Y':
	case 'Z':
	case 'a':
	case 'b':
	case 'c':
	case 'd':
	case 'e':
	case 'f':
	case 'g':
	case 'h':
	case 'i':
	case 'j':
	case 'k':
	case 'l':
	case 'm':
	case 'n':
	case 'o':
	case 'p':
	case 'q':
	case 'r':
	case 's':
	case 't':
	case 'u':
	case 'v':
	case 'w':
	case 'x':
	case 'y':
	case 'z':	goto yy63;
	case '[':	goto yy66;
	case '\\':	goto yy68;
	case ']':	goto yy70;
	case '^':	goto yy72;
	case '_':	goto yy74;
	case '{':	goto yy76;
	case '|':	goto yy78;
	case '}':	goto yy80;
	case '~':	goto yy82;
	case 0xB0:	goto yy84;
	case 0xC0:
	case 0xC1:
	case 0xC2:
	case 0xC3:
	case 0xC4:
	case 0xC5:
	case 0xC6:
	case 0xC7:
	case 0xC8:
	case 0xC9:
	case 0xCA:
	case 0xCB:
	case 0xCC:
	case 0xCD:
	case 0xCE:
	case 0xCF:
	case 0xD0:
	case 0xD1:
	case 0xD2:
	case 0xD3:
	case 0xD4:
	case 0xD5:
	case 0xD6:
	case 0xD7:
	case 0xD8:
	case 0xD9:
	case 0xDA:
	case 0xDB:
	case 0xDC:
	case 0xDD:
	case 0xDE:
	case 0xDF:	goto yy86;
	case 0xE0:
	case 0xE1:
	case 0xE2:
	case 0xE3:
	case 0xE4:
	case 0xE5:
	case 0xE6:
	case 0xE7:
	case 0xE8:
	case 0xE9:
	case 0xEA:
	case 0xEB:
	case 0xEC:
	case 0xED:
	case 0xEE:
	case 0xEF:	goto yy87;
	case 0xF0:
	case 0xF1:
	case 0xF2:
	case 0xF3:
	case 0xF4:
	case 0xF5:
	case 0xF6:
	case 0xF7:	goto yy88;
	default:	goto yy4;
	}
yy2:
	++s;
#line 133 "re2c-scanner-r.re"
	{ return TOKEN_EOF; }
#line 194 "re2c-scanner-r.cc"
yy4:
	++s;
yy5:
#line 135 "re2c-scanner-r.re"
	{ return TOKEN_ILLEGAL_CHAR; }
#line 200 "re2c-scanner-r.cc"
yy6:
	++s;
#line 128 "re2c-scanner-r.re"
	{ return TOKEN_TAB; }
#line 205 "re2c-scanner-r.cc"
yy8:
	++s;
#line 127 "re2c-scanner-r.re"
	{ return TOKEN_NEWLINE; }
#line 210 "re2c-scanner-r.cc"
yy10:
	++s;
#line 126 "re2c-scanner-r.re"
	{ return TOKEN_CRETURN; }
#line 215 "re2c-scanner-r.cc"
yy12:
	++s;
	if (lim <= s) return false;
	yych = *s;
	switch (yych) {
	case ' ':	goto yy12;
	default:	goto yy14;
	}
yy14:
#line 129 "re2c-scanner-r.re"
	{ return TOKEN_SPACE; }
#line 227 "re2c-scanner-r.cc"
yy15:
	yych = *++s;
	switch (yych) {
	case '=':	goto yy89;
	default:	goto yy16;
	}
yy16:
#line 97 "re2c-scanner-r.re"
	{ return TOKEN_EXCLAM; }
#line 237 "re2c-scanner-r.cc"
yy17:
	yyaccept = 0;
	yych = *(m = ++s);
	switch (yych) {
	case 0x00:
	case '\n':	goto yy18;
	default:	goto yy92;
	}
yy18:
#line 123 "re2c-scanner-r.re"
	{ return TOKEN_QUOTE; }
#line 249 "re2c-scanner-r.cc"
yy19:
	++s;
#line 122 "re2c-scanner-r.re"
	{ return TOKEN_HASH; }
#line 254 "re2c-scanner-r.cc"
yy21:
	++s;
#line 120 "re2c-scanner-r.re"
	{ return TOKEN_DOLLAR; }
#line 259 "re2c-scanner-r.cc"
yy23:
	yyaccept = 1;
	yych = *(m = ++s);
	switch (yych) {
	case ' ':	goto yy24;
	default:	goto yy99;
	}
yy24:
#line 116 "re2c-scanner-r.re"
	{ return TOKEN_MOD; }
#line 270 "re2c-scanner-r.cc"
yy25:
	yych = *++s;
	switch (yych) {
	case '&':	goto yy102;
	default:	goto yy26;
	}
yy26:
#line 106 "re2c-scanner-r.re"
	{ return TOKEN_AND; }
#line 280 "re2c-scanner-r.cc"
yy27:
	yyaccept = 2;
	yych = *(m = ++s);
	switch (yych) {
	case 0x00:
	case '\n':	goto yy28;
	default:	goto yy105;
	}
yy28:
#line 124 "re2c-scanner-r.re"
	{ return TOKEN_APOS; }
#line 292 "re2c-scanner-r.cc"
yy29:
	++s;
#line 68 "re2c-scanner-r.re"
	{ return TOKEN_L_PAREN; }
#line 297 "re2c-scanner-r.cc"
yy31:
	++s;
#line 69 "re2c-scanner-r.re"
	{ return TOKEN_R_PAREN; }
#line 302 "re2c-scanner-r.cc"
yy33:
	++s;
#line 115 "re2c-scanner-r.re"
	{ return TOKEN_MULT; }
#line 307 "re2c-scanner-r.cc"
yy35:
	++s;
#line 111 "re2c-scanner-r.re"
	{ return TOKEN_PLUS; }
#line 312 "re2c-scanner-r.cc"
yy37:
	++s;
#line 102 "re2c-scanner-r.re"
	{ return TOKEN_COMMA; }
#line 317 "re2c-scanner-r.cc"
yy39:
	yych = *++s;
	switch (yych) {
	case '>':	goto yy108;
	default:	goto yy40;
	}
yy40:
#line 112 "re2c-scanner-r.re"
	{ return TOKEN_MINUS; }
#line 327 "re2c-scanner-r.cc"
yy41:
	yyaccept = 3;
	yych = *(m = ++s);
	switch (yych) {
	case '.':
	case 'A':
	case 'B':
	case 'C':
	case 'D':
	case 'E':
	case 'F':
	case 'G':
	case 'H':
	case 'I':
	case 'J':
	case 'K':
	case 'L':
	case 'M':
	case 'N':
	case 'O':
	case 'P':
	case 'Q':
	case 'R':
	case 'S':
	case 'T':
	case 'U':
	case 'V':
	case 'W':
	case 'X':
	case 'Y':
	case 'Z':
	case '_':
	case 'a':
	case 'b':
	case 'c':
	case 'd':
	case 'e':
	case 'f':
	case 'g':
	case 'h':
	case 'i':
	case 'j':
	case 'k':
	case 'l':
	case 'm':
	case 'n':
	case 'o':
	case 'p':
	case 'q':
	case 'r':
	case 's':
	case 't':
	case 'u':
	case 'v':
	case 'w':
	case 'x':
	case 'y':
	case 'z':
	case 0xC0:
	case 0xC1:
	case 0xC2:
	case 0xC3:
	case 0xC4:
	case 0xC5:
	case 0xC6:
	case 0xC7:
	case 0xC8:
	case 0xC9:
	case 0xCA:
	case 0xCB:
	case 0xCC:
	case 0xCD:
	case 0xCE:
	case 0xCF:
	case 0xD0:
	case 0xD1:
	case 0xD2:
	case 0xD3:
	case 0xD4:
	case 0xD5:
	case 0xD6:
	case 0xD7:
	case 0xD8:
	case 0xD9:
	case 0xDA:
	case 0xDB:
	case 0xDC:
	case 0xDD:
	case 0xDE:
	case 0xDF:
	case 0xE0:
	case 0xE1:
	case 0xE2:
	case 0xE3:
	case 0xE4:
	case 0xE5:
	case 0xE6:
	case 0xE7:
	case 0xE8:
	case 0xE9:
	case 0xEA:
	case 0xEB:
	case 0xEC:
	case 0xED:
	case 0xEE:
	case 0xEF:
	case 0xF0:
	case 0xF1:
	case 0xF2:
	case 0xF3:
	case 0xF4:
	case 0xF5:
	case 0xF6:
	case 0xF7:	goto yy64;
	case '0':
	case '1':
	case '2':
	case '3':
	case '4':
	case '5':
	case '6':
	case '7':
	case '8':
	case '9':	goto yy110;
	default:	goto yy42;
	}
yy42:
#line 104 "re2c-scanner-r.re"
	{ return TOKEN_FULL_STOP; }
#line 457 "re2c-scanner-r.cc"
yy43:
	++s;
#line 113 "re2c-scanner-r.re"
	{ return TOKEN_DIV; }
#line 462 "re2c-scanner-r.cc"
yy45:
	yyaccept = 4;
	yych = *(m = ++s);
	switch (yych) {
	case 'x':	goto yy122;
	default:	goto yy48;
	}
yy46:
#line 64 "re2c-scanner-r.re"
	{ return TOKEN_INTEGER; }
#line 473 "re2c-scanner-r.cc"
yy47:
	yyaccept = 4;
	m = ++s;
	if ((lim - s) < 3) return false;
	yych = *s;
yy48:
	switch (yych) {
	case '.':	goto yy116;
	case '0':
	case '1':
	case '2':
	case '3':
	case '4':
	case '5':
	case '6':
	case '7':
	case '8':
	case '9':	goto yy47;
	case 'D':
	case 'E':
	case 'd':
	case 'e':	goto yy118;
	case 'L':
	case 'U':
	case 'l':
	case 'u':	goto yy119;
	case 'i':	goto yy121;
	default:	goto yy46;
	}
yy49:
	yych = *++s;
	switch (yych) {
	case ':':	goto yy123;
	default:	goto yy50;
	}
yy50:
#line 99 "re2c-scanner-r.re"
	{ return TOKEN_COLON; }
#line 512 "re2c-scanner-r.cc"
yy51:
	++s;
#line 103 "re2c-scanner-r.re"
	{ return TOKEN_SEMICOLON; }
#line 517 "re2c-scanner-r.cc"
yy53:
	yyaccept = 5;
	yych = *(m = ++s);
	switch (yych) {
	case '-':	goto yy125;
	case '<':	goto yy127;
	case '=':	goto yy128;
	default:	goto yy54;
	}
yy54:
#line 87 "re2c-scanner-r.re"
	{ return TOKEN_LESS; }
#line 530 "re2c-scanner-r.cc"
yy55:
	yych = *++s;
	switch (yych) {
	case '=':	goto yy130;
	default:	goto yy56;
	}
yy56:
#line 80 "re2c-scanner-r.re"
	{ return TOKEN_EQUAL; }
#line 540 "re2c-scanner-r.cc"
yy57:
	yych = *++s;
	switch (yych) {
	case '=':	goto yy132;
	default:	goto yy58;
	}
yy58:
#line 88 "re2c-scanner-r.re"
	{ return TOKEN_GREATER; }
#line 550 "re2c-scanner-r.cc"
yy59:
	++s;
#line 98 "re2c-scanner-r.re"
	{ return TOKEN_QUESTION; }
#line 555 "re2c-scanner-r.cc"
yy61:
	++s;
#line 105 "re2c-scanner-r.re"
	{ return TOKEN_AT; }
#line 560 "re2c-scanner-r.cc"
yy63:
	yyaccept = 6;
	m = ++s;
	if (lim <= s) return false;
	yych = *s;
yy64:
	switch (yych) {
	case '.':
	case '0':
	case '1':
	case '2':
	case '3':
	case '4':
	case '5':
	case '6':
	case '7':
	case '8':
	case '9':
	case 'A':
	case 'B':
	case 'C':
	case 'D':
	case 'E':
	case 'F':
	case 'G':
	case 'H':
	case 'I':
	case 'J':
	case 'K':
	case 'L':
	case 'M':
	case 'N':
	case 'O':
	case 'P':
	case 'Q':
	case 'R':
	case 'S':
	case 'T':
	case 'U':
	case 'V':
	case 'W':
	case 'X':
	case 'Y':
	case 'Z':
	case '_':
	case 'a':
	case 'b':
	case 'c':
	case 'd':
	case 'e':
	case 'f':
	case 'g':
	case 'h':
	case 'i':
	case 'j':
	case 'k':
	case 'l':
	case 'm':
	case 'n':
	case 'o':
	case 'p':
	case 'q':
	case 'r':
	case 's':
	case 't':
	case 'u':
	case 'v':
	case 'w':
	case 'x':
	case 'y':
	case 'z':	goto yy63;
	case 0xC0:
	case 0xC1:
	case 0xC2:
	case 0xC3:
	case 0xC4:
	case 0xC5:
	case 0xC6:
	case 0xC7:
	case 0xC8:
	case 0xC9:
	case 0xCA:
	case 0xCB:
	case 0xCC:
	case 0xCD:
	case 0xCE:
	case 0xCF:
	case 0xD0:
	case 0xD1:
	case 0xD2:
	case 0xD3:
	case 0xD4:
	case 0xD5:
	case 0xD6:
	case 0xD7:
	case 0xD8:
	case 0xD9:
	case 0xDA:
	case 0xDB:
	case 0xDC:
	case 0xDD:
	case 0xDE:
	case 0xDF:	goto yy113;
	case 0xE0:
	case 0xE1:
	case 0xE2:
	case 0xE3:
	case 0xE4:
	case 0xE5:
	case 0xE6:
	case 0xE7:
	case 0xE8:
	case 0xE9:
	case 0xEA:
	case 0xEB:
	case 0xEC:
	case 0xED:
	case 0xEE:
	case 0xEF:	goto yy114;
	case 0xF0:
	case 0xF1:
	case 0xF2:
	case 0xF3:
	case 0xF4:
	case 0xF5:
	case 0xF6:
	case 0xF7:	goto yy115;
	default:	goto yy65;
	}
yy65:
#line 130 "re2c-scanner-r.re"
	{ return TOKEN_IDENTIFIER; }
#line 693 "re2c-scanner-r.cc"
yy66:
	yych = *++s;
	switch (yych) {
	case '[':	goto yy134;
	default:	goto yy67;
	}
yy67:
#line 74 "re2c-scanner-r.re"
	{ return TOKEN_L_BRACKET; }
#line 703 "re2c-scanner-r.cc"
yy68:
	++s;
#line 114 "re2c-scanner-r.re"
	{ return TOKEN_BACKSLASH; }
#line 708 "re2c-scanner-r.cc"
yy70:
	yych = *++s;
	switch (yych) {
	case ']':	goto yy136;
	default:	goto yy71;
	}
yy71:
#line 75 "re2c-scanner-r.re"
	{ return TOKEN_R_BRACKET; }
#line 718 "re2c-scanner-r.cc"
yy72:
	++s;
#line 118 "re2c-scanner-r.re"
	{ return TOKEN_POW; }
#line 723 "re2c-scanner-r.cc"
yy74:
	++s;
#line 119 "re2c-scanner-r.re"
	{ return TOKEN_UNDERSCORE; }
#line 728 "re2c-scanner-r.cc"
yy76:
	++s;
#line 71 "re2c-scanner-r.re"
	{ return TOKEN_L_BRACE; }
#line 733 "re2c-scanner-r.cc"
yy78:
	yych = *++s;
	switch (yych) {
	case '|':	goto yy138;
	default:	goto yy79;
	}
yy79:
#line 108 "re2c-scanner-r.re"
	{ return TOKEN_OR; }
#line 743 "re2c-scanner-r.cc"
yy80:
	++s;
#line 72 "re2c-scanner-r.re"
	{ return TOKEN_R_BRACE; }
#line 748 "re2c-scanner-r.cc"
yy82:
	++s;
#line 96 "re2c-scanner-r.re"
	{ return TOKEN_TILDE; }
#line 753 "re2c-scanner-r.cc"
yy84:
	++s;
#line 121 "re2c-scanner-r.re"
	{ return TOKEN_CIRC; }
#line 758 "re2c-scanner-r.cc"
yy86:
	yych = *++s;
	switch (yych) {
	case 0x80:
	case 0x81:
	case 0x82:
	case 0x83:
	case 0x84:
	case 0x85:
	case 0x86:
	case 0x87:
	case 0x88:
	case 0x89:
	case 0x8A:
	case 0x8B:
	case 0x8C:
	case 0x8D:
	case 0x8E:
	case 0x8F:
	case 0x90:
	case 0x91:
	case 0x92:
	case 0x93:
	case 0x94:
	case 0x95:
	case 0x96:
	case 0x97:
	case 0x98:
	case 0x99:
	case 0x9A:
	case 0x9B:
	case 0x9C:
	case 0x9D:
	case 0x9E:
	case 0x9F:
	case 0xA0:
	case 0xA1:
	case 0xA2:
	case 0xA3:
	case 0xA4:
	case 0xA5:
	case 0xA6:
	case 0xA7:
	case 0xA8:
	case 0xA9:
	case 0xAA:
	case 0xAB:
	case 0xAC:
	case 0xAD:
	case 0xAE:
	case 0xAF:
	case 0xB0:
	case 0xB1:
	case 0xB2:
	case 0xB3:
	case 0xB4:
	case 0xB5:
	case 0xB6:
	case 0xB7:
	case 0xB8:
	case 0xB9:
	case 0xBA:
	case 0xBB:
	case 0xBC:
	case 0xBD:
	case 0xBE:
	case 0xBF:	goto yy63;
	default:	goto yy5;
	}
yy87:
	yyaccept = 7;
	yych = *(m = ++s);
	switch (yych) {
	case 0x80:
	case 0x81:
	case 0x82:
	case 0x83:
	case 0x84:
	case 0x85:
	case 0x86:
	case 0x87:
	case 0x88:
	case 0x89:
	case 0x8A:
	case 0x8B:
	case 0x8C:
	case 0x8D:
	case 0x8E:
	case 0x8F:
	case 0x90:
	case 0x91:
	case 0x92:
	case 0x93:
	case 0x94:
	case 0x95:
	case 0x96:
	case 0x97:
	case 0x98:
	case 0x99:
	case 0x9A:
	case 0x9B:
	case 0x9C:
	case 0x9D:
	case 0x9E:
	case 0x9F:
	case 0xA0:
	case 0xA1:
	case 0xA2:
	case 0xA3:
	case 0xA4:
	case 0xA5:
	case 0xA6:
	case 0xA7:
	case 0xA8:
	case 0xA9:
	case 0xAA:
	case 0xAB:
	case 0xAC:
	case 0xAD:
	case 0xAE:
	case 0xAF:
	case 0xB0:
	case 0xB1:
	case 0xB2:
	case 0xB3:
	case 0xB4:
	case 0xB5:
	case 0xB6:
	case 0xB7:
	case 0xB8:
	case 0xB9:
	case 0xBA:
	case 0xBB:
	case 0xBC:
	case 0xBD:
	case 0xBE:
	case 0xBF:	goto yy113;
	default:	goto yy5;
	}
yy88:
	yyaccept = 7;
	yych = *(m = ++s);
	switch (yych) {
	case 0x80:
	case 0x81:
	case 0x82:
	case 0x83:
	case 0x84:
	case 0x85:
	case 0x86:
	case 0x87:
	case 0x88:
	case 0x89:
	case 0x8A:
	case 0x8B:
	case 0x8C:
	case 0x8D:
	case 0x8E:
	case 0x8F:
	case 0x90:
	case 0x91:
	case 0x92:
	case 0x93:
	case 0x94:
	case 0x95:
	case 0x96:
	case 0x97:
	case 0x98:
	case 0x99:
	case 0x9A:
	case 0x9B:
	case 0x9C:
	case 0x9D:
	case 0x9E:
	case 0x9F:
	case 0xA0:
	case 0xA1:
	case 0xA2:
	case 0xA3:
	case 0xA4:
	case 0xA5:
	case 0xA6:
	case 0xA7:
	case 0xA8:
	case 0xA9:
	case 0xAA:
	case 0xAB:
	case 0xAC:
	case 0xAD:
	case 0xAE:
	case 0xAF:
	case 0xB0:
	case 0xB1:
	case 0xB2:
	case 0xB3:
	case 0xB4:
	case 0xB5:
	case 0xB6:
	case 0xB7:
	case 0xB8:
	case 0xB9:
	case 0xBA:
	case 0xBB:
	case 0xBC:
	case 0xBD:
	case 0xBE:
	case 0xBF:	goto yy114;
	default:	goto yy5;
	}
yy89:
	++s;
#line 94 "re2c-scanner-r.re"
	{ return TOKEN_NOT_EQUAL; }
#line 972 "re2c-scanner-r.cc"
yy91:
	++s;
	if (lim <= s) return false;
	yych = *s;
yy92:
	switch (yych) {
	case 0x00:
	case '\n':	goto yy93;
	case '"':	goto yy94;
	case '\\':	goto yy96;
	default:	goto yy91;
	}
yy93:
	s = m;
	switch (yyaccept) {
	case 0: 	goto yy18;
	case 1: 	goto yy24;
	case 2: 	goto yy28;
	case 3: 	goto yy42;
	case 4: 	goto yy46;
	case 5: 	goto yy54;
	case 6: 	goto yy65;
	case 7: 	goto yy5;
	case 8: 	goto yy112;
	default:	goto yy95;
	}
yy94:
	++s;
yy95:
#line 65 "re2c-scanner-r.re"
	{ return TOKEN_STRING; }
#line 1004 "re2c-scanner-r.cc"
yy96:
	++s;
	if (lim <= s) return false;
	yych = *s;
	switch (yych) {
	case 0x00:
	case '\n':	goto yy93;
	case '"':	goto yy140;
	case '\\':	goto yy96;
	default:	goto yy91;
	}
yy98:
	++s;
	if (lim <= s) return false;
	yych = *s;
yy99:
	switch (yych) {
	case ' ':	goto yy93;
	case '%':	goto yy100;
	default:	goto yy98;
	}
yy100:
	++s;
#line 117 "re2c-scanner-r.re"
	{ return TOKEN_OPERATOR; }
#line 1030 "re2c-scanner-r.cc"
yy102:
	++s;
#line 107 "re2c-scanner-r.re"
	{ return TOKEN_DOUBLE_AND; }
#line 1035 "re2c-scanner-r.cc"
yy104:
	++s;
	if (lim <= s) return false;
	yych = *s;
yy105:
	switch (yych) {
	case 0x00:
	case '\n':	goto yy93;
	case '\'':	goto yy94;
	case '\\':	goto yy106;
	default:	goto yy104;
	}
yy106:
	++s;
	if (lim <= s) return false;
	yych = *s;
	switch (yych) {
	case 0x00:
	case '\n':	goto yy93;
	case '\'':	goto yy141;
	case '\\':	goto yy106;
	default:	goto yy104;
	}
yy108:
	yych = *++s;
	switch (yych) {
	case '>':	goto yy142;
	default:	goto yy109;
	}
yy109:
#line 84 "re2c-scanner-r.re"
	{ return TOKEN_RIGHT_ARROW; }
#line 1068 "re2c-scanner-r.cc"
yy110:
	yyaccept = 8;
	m = ++s;
	if ((lim - s) < 3) return false;
	yych = *s;
	switch (yych) {
	case '.':
	case 'A':
	case 'B':
	case 'C':
	case 'F':
	case 'G':
	case 'H':
	case 'I':
	case 'J':
	case 'K':
	case 'L':
	case 'M':
	case 'N':
	case 'O':
	case 'P':
	case 'Q':
	case 'R':
	case 'S':
	case 'T':
	case 'U':
	case 'V':
	case 'W':
	case 'X':
	case 'Y':
	case 'Z':
	case '_':
	case 'a':
	case 'b':
	case 'c':
	case 'f':
	case 'g':
	case 'h':
	case 'j':
	case 'k':
	case 'l':
	case 'm':
	case 'n':
	case 'o':
	case 'p':
	case 'q':
	case 'r':
	case 's':
	case 't':
	case 'u':
	case 'v':
	case 'w':
	case 'x':
	case 'y':
	case 'z':	goto yy63;
	case '0':
	case '1':
	case '2':
	case '3':
	case '4':
	case '5':
	case '6':
	case '7':
	case '8':
	case '9':	goto yy110;
	case 'D':
	case 'E':
	case 'd':
	case 'e':	goto yy144;
	case 'i':	goto yy145;
	case 0xC0:
	case 0xC1:
	case 0xC2:
	case 0xC3:
	case 0xC4:
	case 0xC5:
	case 0xC6:
	case 0xC7:
	case 0xC8:
	case 0xC9:
	case 0xCA:
	case 0xCB:
	case 0xCC:
	case 0xCD:
	case 0xCE:
	case 0xCF:
	case 0xD0:
	case 0xD1:
	case 0xD2:
	case 0xD3:
	case 0xD4:
	case 0xD5:
	case 0xD6:
	case 0xD7:
	case 0xD8:
	case 0xD9:
	case 0xDA:
	case 0xDB:
	case 0xDC:
	case 0xDD:
	case 0xDE:
	case 0xDF:	goto yy113;
	case 0xE0:
	case 0xE1:
	case 0xE2:
	case 0xE3:
	case 0xE4:
	case 0xE5:
	case 0xE6:
	case 0xE7:
	case 0xE8:
	case 0xE9:
	case 0xEA:
	case 0xEB:
	case 0xEC:
	case 0xED:
	case 0xEE:
	case 0xEF:	goto yy114;
	case 0xF0:
	case 0xF1:
	case 0xF2:
	case 0xF3:
	case 0xF4:
	case 0xF5:
	case 0xF6:
	case 0xF7:	goto yy115;
	default:	goto yy112;
	}
yy112:
#line 66 "re2c-scanner-r.re"
	{ return TOKEN_FLOAT; }
#line 1200 "re2c-scanner-r.cc"
yy113:
	++s;
	if (lim <= s) return false;
	yych = *s;
	switch (yych) {
	case 0x80:
	case 0x81:
	case 0x82:
	case 0x83:
	case 0x84:
	case 0x85:
	case 0x86:
	case 0x87:
	case 0x88:
	case 0x89:
	case 0x8A:
	case 0x8B:
	case 0x8C:
	case 0x8D:
	case 0x8E:
	case 0x8F:
	case 0x90:
	case 0x91:
	case 0x92:
	case 0x93:
	case 0x94:
	case 0x95:
	case 0x96:
	case 0x97:
	case 0x98:
	case 0x99:
	case 0x9A:
	case 0x9B:
	case 0x9C:
	case 0x9D:
	case 0x9E:
	case 0x9F:
	case 0xA0:
	case 0xA1:
	case 0xA2:
	case 0xA3:
	case 0xA4:
	case 0xA5:
	case 0xA6:
	case 0xA7:
	case 0xA8:
	case 0xA9:
	case 0xAA:
	case 0xAB:
	case 0xAC:
	case 0xAD:
	case 0xAE:
	case 0xAF:
	case 0xB0:
	case 0xB1:
	case 0xB2:
	case 0xB3:
	case 0xB4:
	case 0xB5:
	case 0xB6:
	case 0xB7:
	case 0xB8:
	case 0xB9:
	case 0xBA:
	case 0xBB:
	case 0xBC:
	case 0xBD:
	case 0xBE:
	case 0xBF:	goto yy63;
	default:	goto yy93;
	}
yy114:
	++s;
	if (lim <= s) return false;
	yych = *s;
	switch (yych) {
	case 0x80:
	case 0x81:
	case 0x82:
	case 0x83:
	case 0x84:
	case 0x85:
	case 0x86:
	case 0x87:
	case 0x88:
	case 0x89:
	case 0x8A:
	case 0x8B:
	case 0x8C:
	case 0x8D:
	case 0x8E:
	case 0x8F:
	case 0x90:
	case 0x91:
	case 0x92:
	case 0x93:
	case 0x94:
	case 0x95:
	case 0x96:
	case 0x97:
	case 0x98:
	case 0x99:
	case 0x9A:
	case 0x9B:
	case 0x9C:
	case 0x9D:
	case 0x9E:
	case 0x9F:
	case 0xA0:
	case 0xA1:
	case 0xA2:
	case 0xA3:
	case 0xA4:
	case 0xA5:
	case 0xA6:
	case 0xA7:
	case 0xA8:
	case 0xA9:
	case 0xAA:
	case 0xAB:
	case 0xAC:
	case 0xAD:
	case 0xAE:
	case 0xAF:
	case 0xB0:
	case 0xB1:
	case 0xB2:
	case 0xB3:
	case 0xB4:
	case 0xB5:
	case 0xB6:
	case 0xB7:
	case 0xB8:
	case 0xB9:
	case 0xBA:
	case 0xBB:
	case 0xBC:
	case 0xBD:
	case 0xBE:
	case 0xBF:	goto yy113;
	default:	goto yy93;
	}
yy115:
	++s;
	if (lim <= s) return false;
	yych = *s;
	switch (yych) {
	case 0x80:
	case 0x81:
	case 0x82:
	case 0x83:
	case 0x84:
	case 0x85:
	case 0x86:
	case 0x87:
	case 0x88:
	case 0x89:
	case 0x8A:
	case 0x8B:
	case 0x8C:
	case 0x8D:
	case 0x8E:
	case 0x8F:
	case 0x90:
	case 0x91:
	case 0x92:
	case 0x93:
	case 0x94:
	case 0x95:
	case 0x96:
	case 0x97:
	case 0x98:
	case 0x99:
	case 0x9A:
	case 0x9B:
	case 0x9C:
	case 0x9D:
	case 0x9E:
	case 0x9F:
	case 0xA0:
	case 0xA1:
	case 0xA2:
	case 0xA3:
	case 0xA4:
	case 0xA5:
	case 0xA6:
	case 0xA7:
	case 0xA8:
	case 0xA9:
	case 0xAA:
	case 0xAB:
	case 0xAC:
	case 0xAD:
	case 0xAE:
	case 0xAF:
	case 0xB0:
	case 0xB1:
	case 0xB2:
	case 0xB3:
	case 0xB4:
	case 0xB5:
	case 0xB6:
	case 0xB7:
	case 0xB8:
	case 0xB9:
	case 0xBA:
	case 0xBB:
	case 0xBC:
	case 0xBD:
	case 0xBE:
	case 0xBF:	goto yy114;
	default:	goto yy93;
	}
yy116:
	yyaccept = 8;
	m = ++s;
	if ((lim - s) < 3) return false;
	yych = *s;
	switch (yych) {
	case '0':
	case '1':
	case '2':
	case '3':
	case '4':
	case '5':
	case '6':
	case '7':
	case '8':
	case '9':	goto yy116;
	case 'D':
	case 'E':
	case 'd':
	case 'e':	goto yy118;
	case 'i':	goto yy121;
	default:	goto yy112;
	}
yy118:
	yych = *++s;
	switch (yych) {
	case '+':
	case '-':	goto yy146;
	case '0':
	case '1':
	case '2':
	case '3':
	case '4':
	case '5':
	case '6':
	case '7':
	case '8':
	case '9':	goto yy147;
	default:	goto yy93;
	}
yy119:
	++s;
	if (lim <= s) return false;
	yych = *s;
	switch (yych) {
	case 'L':
	case 'U':
	case 'l':
	case 'u':	goto yy119;
	default:	goto yy46;
	}
yy121:
	++s;
	goto yy112;
yy122:
	yych = *++s;
	switch (yych) {
	case '0':
	case '1':
	case '2':
	case '3':
	case '4':
	case '5':
	case '6':
	case '7':
	case '8':
	case '9':	goto yy149;
	default:	goto yy93;
	}
yy123:
	yych = *++s;
	switch (yych) {
	case ':':	goto yy151;
	default:	goto yy124;
	}
yy124:
#line 100 "re2c-scanner-r.re"
	{ return TOKEN_DOUBLE_COLON; }
#line 1492 "re2c-scanner-r.cc"
yy125:
	++s;
#line 82 "re2c-scanner-r.re"
	{ return TOKEN_LEFT_ARROW; }
#line 1497 "re2c-scanner-r.cc"
yy127:
	yych = *++s;
	switch (yych) {
	case '-':	goto yy153;
	default:	goto yy93;
	}
yy128:
	++s;
#line 90 "re2c-scanner-r.re"
	{ return TOKEN_LE; }
#line 1508 "re2c-scanner-r.cc"
yy130:
	++s;
#line 93 "re2c-scanner-r.re"
	{ return TOKEN_DOUBLE_EQUAL; }
#line 1513 "re2c-scanner-r.cc"
yy132:
	++s;
#line 91 "re2c-scanner-r.re"
	{ return TOKEN_GE; }
#line 1518 "re2c-scanner-r.cc"
yy134:
	++s;
#line 77 "re2c-scanner-r.re"
	{ return TOKEN_DOUBLE_L_BRACKET; }
#line 1523 "re2c-scanner-r.cc"
yy136:
	++s;
#line 78 "re2c-scanner-r.re"
	{ return TOKEN_DOUBLE_R_BRACKET; }
#line 1528 "re2c-scanner-r.cc"
yy138:
	++s;
#line 109 "re2c-scanner-r.re"
	{ return TOKEN_DOUBLE_OR; }
#line 1533 "re2c-scanner-r.cc"
yy140:
	yyaccept = 9;
	m = ++s;
	if (lim <= s) return false;
	yych = *s;
	switch (yych) {
	case 0x00:
	case '\n':	goto yy95;
	case '"':	goto yy94;
	case '\\':	goto yy96;
	default:	goto yy91;
	}
yy141:
	yyaccept = 9;
	m = ++s;
	if (lim <= s) return false;
	yych = *s;
	switch (yych) {
	case 0x00:
	case '\n':	goto yy95;
	case '\'':	goto yy94;
	case '\\':	goto yy106;
	default:	goto yy104;
	}
yy142:
	++s;
#line 85 "re2c-scanner-r.re"
	{ return TOKEN_DOUBLE_RIGHT_ARROW; }
#line 1562 "re2c-scanner-r.cc"
yy144:
	yyaccept = 6;
	yych = *(m = ++s);
	switch (yych) {
	case '+':
	case '-':	goto yy146;
	case '0':
	case '1':
	case '2':
	case '3':
	case '4':
	case '5':
	case '6':
	case '7':
	case '8':
	case '9':	goto yy155;
	default:	goto yy64;
	}
yy145:
	yyaccept = 8;
	yych = *(m = ++s);
	switch (yych) {
	case '.':
	case '0':
	case '1':
	case '2':
	case '3':
	case '4':
	case '5':
	case '6':
	case '7':
	case '8':
	case '9':
	case 'A':
	case 'B':
	case 'C':
	case 'D':
	case 'E':
	case 'F':
	case 'G':
	case 'H':
	case 'I':
	case 'J':
	case 'K':
	case 'L':
	case 'M':
	case 'N':
	case 'O':
	case 'P':
	case 'Q':
	case 'R':
	case 'S':
	case 'T':
	case 'U':
	case 'V':
	case 'W':
	case 'X':
	case 'Y':
	case 'Z':
	case '_':
	case 'a':
	case 'b':
	case 'c':
	case 'd':
	case 'e':
	case 'f':
	case 'g':
	case 'h':
	case 'i':
	case 'j':
	case 'k':
	case 'l':
	case 'm':
	case 'n':
	case 'o':
	case 'p':
	case 'q':
	case 'r':
	case 's':
	case 't':
	case 'u':
	case 'v':
	case 'w':
	case 'x':
	case 'y':
	case 'z':
	case 0xC0:
	case 0xC1:
	case 0xC2:
	case 0xC3:
	case 0xC4:
	case 0xC5:
	case 0xC6:
	case 0xC7:
	case 0xC8:
	case 0xC9:
	case 0xCA:
	case 0xCB:
	case 0xCC:
	case 0xCD:
	case 0xCE:
	case 0xCF:
	case 0xD0:
	case 0xD1:
	case 0xD2:
	case 0xD3:
	case 0xD4:
	case 0xD5:
	case 0xD6:
	case 0xD7:
	case 0xD8:
	case 0xD9:
	case 0xDA:
	case 0xDB:
	case 0xDC:
	case 0xDD:
	case 0xDE:
	case 0xDF:
	case 0xE0:
	case 0xE1:
	case 0xE2:
	case 0xE3:
	case 0xE4:
	case 0xE5:
	case 0xE6:
	case 0xE7:
	case 0xE8:
	case 0xE9:
	case 0xEA:
	case 0xEB:
	case 0xEC:
	case 0xED:
	case 0xEE:
	case 0xEF:
	case 0xF0:
	case 0xF1:
	case 0xF2:
	case 0xF3:
	case 0xF4:
	case 0xF5:
	case 0xF6:
	case 0xF7:	goto yy64;
	default:	goto yy112;
	}
yy146:
	yych = *++s;
	switch (yych) {
	case '0':
	case '1':
	case '2':
	case '3':
	case '4':
	case '5':
	case '6':
	case '7':
	case '8':
	case '9':	goto yy147;
	default:	goto yy93;
	}
yy147:
	++s;
	if (lim <= s) return false;
	yych = *s;
	switch (yych) {
	case '0':
	case '1':
	case '2':
	case '3':
	case '4':
	case '5':
	case '6':
	case '7':
	case '8':
	case '9':	goto yy147;
	case 'i':	goto yy121;
	default:	goto yy112;
	}
yy149:
	++s;
	if (lim <= s) return false;
	yych = *s;
	switch (yych) {
	case '0':
	case '1':
	case '2':
	case '3':
	case '4':
	case '5':
	case '6':
	case '7':
	case '8':
	case '9':	goto yy149;
	case 'L':
	case 'U':
	case 'l':
	case 'u':	goto yy119;
	default:	goto yy46;
	}
yy151:
	++s;
#line 101 "re2c-scanner-r.re"
	{ return TOKEN_TRIPLE_COLON; }
#line 1765 "re2c-scanner-r.cc"
yy153:
	++s;
#line 83 "re2c-scanner-r.re"
	{ return TOKEN_DOUBLE_LEFT_ARROW; }
#line 1770 "re2c-scanner-r.cc"
yy155:
	yyaccept = 8;
	m = ++s;
	if ((lim - s) < 2) return false;
	yych = *s;
	switch (yych) {
	case '.':
	case 'A':
	case 'B':
	case 'C':
	case 'D':
	case 'E':
	case 'F':
	case 'G':
	case 'H':
	case 'I':
	case 'J':
	case 'K':
	case 'L':
	case 'M':
	case 'N':
	case 'O':
	case 'P':
	case 'Q':
	case 'R':
	case 'S':
	case 'T':
	case 'U':
	case 'V':
	case 'W':
	case 'X':
	case 'Y':
	case 'Z':
	case '_':
	case 'a':
	case 'b':
	case 'c':
	case 'd':
	case 'e':
	case 'f':
	case 'g':
	case 'h':
	case 'j':
	case 'k':
	case 'l':
	case 'm':
	case 'n':
	case 'o':
	case 'p':
	case 'q':
	case 'r':
	case 's':
	case 't':
	case 'u':
	case 'v':
	case 'w':
	case 'x':
	case 'y':
	case 'z':	goto yy63;
	case '0':
	case '1':
	case '2':
	case '3':
	case '4':
	case '5':
	case '6':
	case '7':
	case '8':
	case '9':	goto yy155;
	case 'i':	goto yy145;
	case 0xC0:
	case 0xC1:
	case 0xC2:
	case 0xC3:
	case 0xC4:
	case 0xC5:
	case 0xC6:
	case 0xC7:
	case 0xC8:
	case 0xC9:
	case 0xCA:
	case 0xCB:
	case 0xCC:
	case 0xCD:
	case 0xCE:
	case 0xCF:
	case 0xD0:
	case 0xD1:
	case 0xD2:
	case 0xD3:
	case 0xD4:
	case 0xD5:
	case 0xD6:
	case 0xD7:
	case 0xD8:
	case 0xD9:
	case 0xDA:
	case 0xDB:
	case 0xDC:
	case 0xDD:
	case 0xDE:
	case 0xDF:	goto yy113;
	case 0xE0:
	case 0xE1:
	case 0xE2:
	case 0xE3:
	case 0xE4:
	case 0xE5:
	case 0xE6:
	case 0xE7:
	case 0xE8:
	case 0xE9:
	case 0xEA:
	case 0xEB:
	case 0xEC:
	case 0xED:
	case 0xEE:
	case 0xEF:	goto yy114;
	case 0xF0:
	case 0xF1:
	case 0xF2:
	case 0xF3:
	case 0xF4:
	case 0xF5:
	case 0xF6:
	case 0xF7:	goto yy115;
	default:	goto yy112;
	}
}
#line 137 "re2c-scanner-r.re"

}

/* Local Variables: */
/* mode: c */
/* coding: latin-1 */
/* End: */
