/* Generated by re2c 3.1 on Mon May 20 14:19:24 2024 */
#line 1 "re2c-scanner-m.re"
/*
This file is part of P2X.
Copyright © 2018 Johannes Willkomm
See the file p2x.cc for copying conditions.
*/

#include "token.ncd.enum.hh"

#line 12 "re2c-scanner-m.cc"
#define YYMAXFILL 4
#line 9 "re2c-scanner-m.re"


#line 17 "re2c-scanner-m.cc"
enum YYCONDTYPE {
	yycINITIAL,
	yycSTARTEXP
};
#line 11 "re2c-scanner-m.re"


typedef unsigned char uint8_t;

static int re2c_scanner_m_c = yycINITIAL;

int re2c_scanner_m_lex(const uint8_t *&s, const uint8_t *&m, uint8_t const * lim)
{

  
#line 33 "re2c-scanner-m.cc"
#line 20 "re2c-scanner-m.re"


    lim += YYMAXFILL;

    
#line 40 "re2c-scanner-m.cc"
{
	uint8_t yych;
	unsigned int yyaccept = 0;
	switch (re2c_scanner_m_c) {
		case yycINITIAL: goto yyc_INITIAL;
		case yycSTARTEXP: goto yyc_STARTEXP;
	}
/* *********************************** */
yyc_INITIAL:
	if ((lim - s) < 4) return false;
	yych = *s;
	switch (yych) {
		case 0x00: goto yy1;
		case '\t': goto yy4;
		case '\n': goto yy5;
		case '\r': goto yy6;
		case ' ': goto yy7;
		case '!': goto yy9;
		case '"': goto yy11;
		case '#': goto yy12;
		case '%': goto yy13;
		case '&': goto yy14;
		case '\'': goto yy16;
		case '(': goto yy17;
		case ')': goto yy18;
		case '*': goto yy19;
		case '+': goto yy21;
		case ',': goto yy23;
		case '-': goto yy24;
		case '.': goto yy26;
		case '/': goto yy28;
		case '0': goto yy30;
		case '1':
		case '2':
		case '3':
		case '4':
		case '5':
		case '6':
		case '7':
		case '8':
		case '9': goto yy32;
		case ':': goto yy34;
		case ';': goto yy35;
		case '<': goto yy36;
		case '=': goto yy38;
		case '>': goto yy40;
		case '?': goto yy42;
		case '@': goto yy43;
		case 'A':
		case 'B':
		case 'C':
		case 'D':
		case 'E':
		case 'F':
		case 'G':
		case 'H':
		case 'I':
		case 'J':
		case 'K':
		case 'L':
		case 'M':
		case 'N':
		case 'O':
		case 'P':
		case 'Q':
		case 'R':
		case 'S':
		case 'T':
		case 'U':
		case 'V':
		case 'W':
		case 'X':
		case 'Y':
		case 'Z':
		case '_':
		case 'a':
		case 'b':
		case 'c':
		case 'd':
		case 'e':
		case 'f':
		case 'g':
		case 'h':
		case 'i':
		case 'j':
		case 'k':
		case 'l':
		case 'm':
		case 'n':
		case 'o':
		case 'p':
		case 'q':
		case 'r':
		case 's':
		case 't':
		case 'u':
		case 'v':
		case 'w':
		case 'x':
		case 'y':
		case 'z': goto yy44;
		case '[': goto yy46;
		case '\\': goto yy47;
		case ']': goto yy49;
		case '^': goto yy50;
		case '{': goto yy52;
		case '|': goto yy53;
		case '}': goto yy55;
		case '~': goto yy56;
		case 0xC0:
		case 0xC1:
		case 0xC2:
		case 0xC3:
		case 0xC4:
		case 0xC5:
		case 0xC6:
		case 0xC7:
		case 0xC8:
		case 0xC9:
		case 0xCA:
		case 0xCB:
		case 0xCC:
		case 0xCD:
		case 0xCE:
		case 0xCF:
		case 0xD0:
		case 0xD1:
		case 0xD2:
		case 0xD3:
		case 0xD4:
		case 0xD5:
		case 0xD6:
		case 0xD7:
		case 0xD8:
		case 0xD9:
		case 0xDA:
		case 0xDB:
		case 0xDC:
		case 0xDD:
		case 0xDE:
		case 0xDF: goto yy58;
		case 0xE0:
		case 0xE1:
		case 0xE2:
		case 0xE3:
		case 0xE4:
		case 0xE5:
		case 0xE6:
		case 0xE7:
		case 0xE8:
		case 0xE9:
		case 0xEA:
		case 0xEB:
		case 0xEC:
		case 0xED:
		case 0xEE:
		case 0xEF: goto yy59;
		case 0xF0:
		case 0xF1:
		case 0xF2:
		case 0xF3:
		case 0xF4:
		case 0xF5:
		case 0xF6:
		case 0xF7: goto yy60;
		default: goto yy2;
	}
yy1:
	++s;
#line 143 "re2c-scanner-m.re"
	{ return TOKEN_EOF; }
#line 212 "re2c-scanner-m.cc"
yy2:
	++s;
yy3:
#line 145 "re2c-scanner-m.re"
	{ return TOKEN_ILLEGAL_CHAR; }
#line 218 "re2c-scanner-m.cc"
yy4:
	++s;
	re2c_scanner_m_c = yycSTARTEXP;
#line 137 "re2c-scanner-m.re"
	{ return TOKEN_TAB; }
#line 224 "re2c-scanner-m.cc"
yy5:
	++s;
	re2c_scanner_m_c = yycSTARTEXP;
#line 136 "re2c-scanner-m.re"
	{ return TOKEN_NEWLINE; }
#line 230 "re2c-scanner-m.cc"
yy6:
	++s;
	re2c_scanner_m_c = yycSTARTEXP;
#line 135 "re2c-scanner-m.re"
	{ return TOKEN_CRETURN; }
#line 236 "re2c-scanner-m.cc"
yy7:
	++s;
	if (lim <= s) return false;
	yych = *s;
	switch (yych) {
		case ' ': goto yy7;
		default: goto yy8;
	}
yy8:
	re2c_scanner_m_c = yycSTARTEXP;
#line 138 "re2c-scanner-m.re"
	{ return TOKEN_SPACE; }
#line 249 "re2c-scanner-m.cc"
yy9:
	yych = *++s;
	switch (yych) {
		case '=': goto yy61;
		default: goto yy10;
	}
yy10:
	re2c_scanner_m_c = yycSTARTEXP;
#line 92 "re2c-scanner-m.re"
	{ return TOKEN_EXCLAM; }
#line 260 "re2c-scanner-m.cc"
yy11:
	yyaccept = 0;
	yych = *(m = ++s);
	switch (yych) {
		case 0x00:
		case '\n': goto yy3;
		default: goto yy63;
	}
yy12:
	++s;
#line 133 "re2c-scanner-m.re"
	{ return TOKEN_HASH; }
#line 273 "re2c-scanner-m.cc"
yy13:
	++s;
	re2c_scanner_m_c = yycSTARTEXP;
#line 108 "re2c-scanner-m.re"
	{ return TOKEN_MOD; }
#line 279 "re2c-scanner-m.cc"
yy14:
	yych = *++s;
	switch (yych) {
		case '&': goto yy68;
		default: goto yy15;
	}
yy15:
	re2c_scanner_m_c = yycSTARTEXP;
#line 99 "re2c-scanner-m.re"
	{ return TOKEN_AND; }
#line 290 "re2c-scanner-m.cc"
yy16:
	++s;
	re2c_scanner_m_c = yycSTARTEXP;
#line 111 "re2c-scanner-m.re"
	{ return TOKEN_APOS; }
#line 296 "re2c-scanner-m.cc"
yy17:
	++s;
	re2c_scanner_m_c = yycSTARTEXP;
#line 70 "re2c-scanner-m.re"
	{ return TOKEN_L_PAREN; }
#line 302 "re2c-scanner-m.cc"
yy18:
	++s;
#line 71 "re2c-scanner-m.re"
	{ return TOKEN_R_PAREN; }
#line 307 "re2c-scanner-m.cc"
yy19:
	yych = *++s;
	switch (yych) {
		case '=': goto yy69;
		default: goto yy20;
	}
yy20:
	re2c_scanner_m_c = yycSTARTEXP;
#line 107 "re2c-scanner-m.re"
	{ return TOKEN_MULT; }
#line 318 "re2c-scanner-m.cc"
yy21:
	yych = *++s;
	switch (yych) {
		case '=': goto yy70;
		default: goto yy22;
	}
yy22:
	re2c_scanner_m_c = yycSTARTEXP;
#line 104 "re2c-scanner-m.re"
	{ return TOKEN_PLUS; }
#line 329 "re2c-scanner-m.cc"
yy23:
	++s;
	re2c_scanner_m_c = yycSTARTEXP;
#line 95 "re2c-scanner-m.re"
	{ return TOKEN_COMMA; }
#line 335 "re2c-scanner-m.cc"
yy24:
	yych = *++s;
	switch (yych) {
		case '=': goto yy71;
		default: goto yy25;
	}
yy25:
	re2c_scanner_m_c = yycSTARTEXP;
#line 105 "re2c-scanner-m.re"
	{ return TOKEN_MINUS; }
#line 346 "re2c-scanner-m.cc"
yy26:
	yyaccept = 1;
	yych = *(m = ++s);
	switch (yych) {
		case '\'': goto yy72;
		case '*': goto yy73;
		case '.': goto yy75;
		case '/': goto yy76;
		case '0':
		case '1':
		case '2':
		case '3':
		case '4':
		case '5':
		case '6':
		case '7':
		case '8':
		case '9': goto yy78;
		case '\\': goto yy80;
		case '^': goto yy82;
		default: goto yy27;
	}
yy27:
	re2c_scanner_m_c = yycSTARTEXP;
#line 97 "re2c-scanner-m.re"
	{ return TOKEN_FULL_STOP; }
#line 373 "re2c-scanner-m.cc"
yy28:
	yych = *++s;
	switch (yych) {
		case '=': goto yy84;
		default: goto yy29;
	}
yy29:
	re2c_scanner_m_c = yycSTARTEXP;
#line 106 "re2c-scanner-m.re"
	{ return TOKEN_DIV; }
#line 384 "re2c-scanner-m.cc"
yy30:
	yyaccept = 2;
	yych = *(m = ++s);
	switch (yych) {
		case 'x': goto yy89;
		default: goto yy33;
	}
yy31:
#line 64 "re2c-scanner-m.re"
	{ return TOKEN_INTEGER; }
#line 395 "re2c-scanner-m.cc"
yy32:
	yyaccept = 2;
	m = ++s;
	if ((lim - s) < 3) return false;
	yych = *s;
yy33:
	switch (yych) {
		case '.': goto yy85;
		case '0':
		case '1':
		case '2':
		case '3':
		case '4':
		case '5':
		case '6':
		case '7':
		case '8':
		case '9': goto yy32;
		case 'D':
		case 'E':
		case 'd':
		case 'e': goto yy86;
		case 'F':
		case 'I':
		case 'f':
		case 'i': goto yy87;
		case 'L':
		case 'U':
		case 'l':
		case 'u': goto yy88;
		default: goto yy31;
	}
yy34:
	++s;
	re2c_scanner_m_c = yycSTARTEXP;
#line 94 "re2c-scanner-m.re"
	{ return TOKEN_COLON; }
#line 433 "re2c-scanner-m.cc"
yy35:
	++s;
	re2c_scanner_m_c = yycSTARTEXP;
#line 96 "re2c-scanner-m.re"
	{ return TOKEN_SEMICOLON; }
#line 439 "re2c-scanner-m.cc"
yy36:
	yych = *++s;
	switch (yych) {
		case '=': goto yy90;
		default: goto yy37;
	}
yy37:
	re2c_scanner_m_c = yycSTARTEXP;
#line 81 "re2c-scanner-m.re"
	{ return TOKEN_LESS; }
#line 450 "re2c-scanner-m.cc"
yy38:
	yych = *++s;
	switch (yych) {
		case '=': goto yy91;
		default: goto yy39;
	}
yy39:
	re2c_scanner_m_c = yycSTARTEXP;
#line 79 "re2c-scanner-m.re"
	{ return TOKEN_EQUAL; }
#line 461 "re2c-scanner-m.cc"
yy40:
	yych = *++s;
	switch (yych) {
		case '=': goto yy92;
		default: goto yy41;
	}
yy41:
	re2c_scanner_m_c = yycSTARTEXP;
#line 82 "re2c-scanner-m.re"
	{ return TOKEN_GREATER; }
#line 472 "re2c-scanner-m.cc"
yy42:
	++s;
	re2c_scanner_m_c = yycSTARTEXP;
#line 93 "re2c-scanner-m.re"
	{ return TOKEN_QUESTION; }
#line 478 "re2c-scanner-m.cc"
yy43:
	++s;
	re2c_scanner_m_c = yycSTARTEXP;
#line 131 "re2c-scanner-m.re"
	{ return TOKEN_AT; }
#line 484 "re2c-scanner-m.cc"
yy44:
	yyaccept = 3;
	m = ++s;
	if (lim <= s) return false;
	yych = *s;
	switch (yych) {
		case '0':
		case '1':
		case '2':
		case '3':
		case '4':
		case '5':
		case '6':
		case '7':
		case '8':
		case '9':
		case 'A':
		case 'B':
		case 'C':
		case 'D':
		case 'E':
		case 'F':
		case 'G':
		case 'H':
		case 'I':
		case 'J':
		case 'K':
		case 'L':
		case 'M':
		case 'N':
		case 'O':
		case 'P':
		case 'Q':
		case 'R':
		case 'S':
		case 'T':
		case 'U':
		case 'V':
		case 'W':
		case 'X':
		case 'Y':
		case 'Z':
		case '_':
		case 'a':
		case 'b':
		case 'c':
		case 'd':
		case 'e':
		case 'f':
		case 'g':
		case 'h':
		case 'i':
		case 'j':
		case 'k':
		case 'l':
		case 'm':
		case 'n':
		case 'o':
		case 'p':
		case 'q':
		case 'r':
		case 's':
		case 't':
		case 'u':
		case 'v':
		case 'w':
		case 'x':
		case 'y':
		case 'z': goto yy44;
		case 0xC0:
		case 0xC1:
		case 0xC2:
		case 0xC3:
		case 0xC4:
		case 0xC5:
		case 0xC6:
		case 0xC7:
		case 0xC8:
		case 0xC9:
		case 0xCA:
		case 0xCB:
		case 0xCC:
		case 0xCD:
		case 0xCE:
		case 0xCF:
		case 0xD0:
		case 0xD1:
		case 0xD2:
		case 0xD3:
		case 0xD4:
		case 0xD5:
		case 0xD6:
		case 0xD7:
		case 0xD8:
		case 0xD9:
		case 0xDA:
		case 0xDB:
		case 0xDC:
		case 0xDD:
		case 0xDE:
		case 0xDF: goto yy93;
		case 0xE0:
		case 0xE1:
		case 0xE2:
		case 0xE3:
		case 0xE4:
		case 0xE5:
		case 0xE6:
		case 0xE7:
		case 0xE8:
		case 0xE9:
		case 0xEA:
		case 0xEB:
		case 0xEC:
		case 0xED:
		case 0xEE:
		case 0xEF: goto yy94;
		case 0xF0:
		case 0xF1:
		case 0xF2:
		case 0xF3:
		case 0xF4:
		case 0xF5:
		case 0xF6:
		case 0xF7: goto yy95;
		default: goto yy45;
	}
yy45:
#line 139 "re2c-scanner-m.re"
	{ return TOKEN_IDENTIFIER; }
#line 615 "re2c-scanner-m.cc"
yy46:
	++s;
	re2c_scanner_m_c = yycSTARTEXP;
#line 76 "re2c-scanner-m.re"
	{ return TOKEN_L_BRACKET; }
#line 621 "re2c-scanner-m.cc"
yy47:
	yych = *++s;
	switch (yych) {
		case '=': goto yy96;
		default: goto yy48;
	}
yy48:
	re2c_scanner_m_c = yycSTARTEXP;
#line 109 "re2c-scanner-m.re"
	{ return TOKEN_BACKSLASH; }
#line 632 "re2c-scanner-m.cc"
yy49:
	++s;
#line 77 "re2c-scanner-m.re"
	{ return TOKEN_R_BRACKET; }
#line 637 "re2c-scanner-m.cc"
yy50:
	yych = *++s;
	switch (yych) {
		case '=': goto yy97;
		default: goto yy51;
	}
yy51:
	re2c_scanner_m_c = yycSTARTEXP;
#line 110 "re2c-scanner-m.re"
	{ return TOKEN_POW; }
#line 648 "re2c-scanner-m.cc"
yy52:
	++s;
	re2c_scanner_m_c = yycSTARTEXP;
#line 73 "re2c-scanner-m.re"
	{ return TOKEN_L_BRACE; }
#line 654 "re2c-scanner-m.cc"
yy53:
	yych = *++s;
	switch (yych) {
		case '|': goto yy98;
		default: goto yy54;
	}
yy54:
	re2c_scanner_m_c = yycSTARTEXP;
#line 101 "re2c-scanner-m.re"
	{ return TOKEN_OR; }
#line 665 "re2c-scanner-m.cc"
yy55:
	++s;
#line 74 "re2c-scanner-m.re"
	{ return TOKEN_R_BRACE; }
#line 670 "re2c-scanner-m.cc"
yy56:
	yych = *++s;
	switch (yych) {
		case '=': goto yy99;
		default: goto yy57;
	}
yy57:
	re2c_scanner_m_c = yycSTARTEXP;
#line 91 "re2c-scanner-m.re"
	{ return TOKEN_TILDE; }
#line 681 "re2c-scanner-m.cc"
yy58:
	yych = *++s;
	switch (yych) {
		case 0x80:
		case 0x81:
		case 0x82:
		case 0x83:
		case 0x84:
		case 0x85:
		case 0x86:
		case 0x87:
		case 0x88:
		case 0x89:
		case 0x8A:
		case 0x8B:
		case 0x8C:
		case 0x8D:
		case 0x8E:
		case 0x8F:
		case 0x90:
		case 0x91:
		case 0x92:
		case 0x93:
		case 0x94:
		case 0x95:
		case 0x96:
		case 0x97:
		case 0x98:
		case 0x99:
		case 0x9A:
		case 0x9B:
		case 0x9C:
		case 0x9D:
		case 0x9E:
		case 0x9F:
		case 0xA0:
		case 0xA1:
		case 0xA2:
		case 0xA3:
		case 0xA4:
		case 0xA5:
		case 0xA6:
		case 0xA7:
		case 0xA8:
		case 0xA9:
		case 0xAA:
		case 0xAB:
		case 0xAC:
		case 0xAD:
		case 0xAE:
		case 0xAF:
		case 0xB0:
		case 0xB1:
		case 0xB2:
		case 0xB3:
		case 0xB4:
		case 0xB5:
		case 0xB6:
		case 0xB7:
		case 0xB8:
		case 0xB9:
		case 0xBA:
		case 0xBB:
		case 0xBC:
		case 0xBD:
		case 0xBE:
		case 0xBF: goto yy44;
		default: goto yy3;
	}
yy59:
	yyaccept = 0;
	yych = *(m = ++s);
	switch (yych) {
		case 0x80:
		case 0x81:
		case 0x82:
		case 0x83:
		case 0x84:
		case 0x85:
		case 0x86:
		case 0x87:
		case 0x88:
		case 0x89:
		case 0x8A:
		case 0x8B:
		case 0x8C:
		case 0x8D:
		case 0x8E:
		case 0x8F:
		case 0x90:
		case 0x91:
		case 0x92:
		case 0x93:
		case 0x94:
		case 0x95:
		case 0x96:
		case 0x97:
		case 0x98:
		case 0x99:
		case 0x9A:
		case 0x9B:
		case 0x9C:
		case 0x9D:
		case 0x9E:
		case 0x9F:
		case 0xA0:
		case 0xA1:
		case 0xA2:
		case 0xA3:
		case 0xA4:
		case 0xA5:
		case 0xA6:
		case 0xA7:
		case 0xA8:
		case 0xA9:
		case 0xAA:
		case 0xAB:
		case 0xAC:
		case 0xAD:
		case 0xAE:
		case 0xAF:
		case 0xB0:
		case 0xB1:
		case 0xB2:
		case 0xB3:
		case 0xB4:
		case 0xB5:
		case 0xB6:
		case 0xB7:
		case 0xB8:
		case 0xB9:
		case 0xBA:
		case 0xBB:
		case 0xBC:
		case 0xBD:
		case 0xBE:
		case 0xBF: goto yy93;
		default: goto yy3;
	}
yy60:
	yyaccept = 0;
	yych = *(m = ++s);
	switch (yych) {
		case 0x80:
		case 0x81:
		case 0x82:
		case 0x83:
		case 0x84:
		case 0x85:
		case 0x86:
		case 0x87:
		case 0x88:
		case 0x89:
		case 0x8A:
		case 0x8B:
		case 0x8C:
		case 0x8D:
		case 0x8E:
		case 0x8F:
		case 0x90:
		case 0x91:
		case 0x92:
		case 0x93:
		case 0x94:
		case 0x95:
		case 0x96:
		case 0x97:
		case 0x98:
		case 0x99:
		case 0x9A:
		case 0x9B:
		case 0x9C:
		case 0x9D:
		case 0x9E:
		case 0x9F:
		case 0xA0:
		case 0xA1:
		case 0xA2:
		case 0xA3:
		case 0xA4:
		case 0xA5:
		case 0xA6:
		case 0xA7:
		case 0xA8:
		case 0xA9:
		case 0xAA:
		case 0xAB:
		case 0xAC:
		case 0xAD:
		case 0xAE:
		case 0xAF:
		case 0xB0:
		case 0xB1:
		case 0xB2:
		case 0xB3:
		case 0xB4:
		case 0xB5:
		case 0xB6:
		case 0xB7:
		case 0xB8:
		case 0xB9:
		case 0xBA:
		case 0xBB:
		case 0xBC:
		case 0xBD:
		case 0xBE:
		case 0xBF: goto yy94;
		default: goto yy3;
	}
yy61:
	++s;
	re2c_scanner_m_c = yycSTARTEXP;
#line 88 "re2c-scanner-m.re"
	{ return TOKEN_NOT_EQUAL; }
#line 896 "re2c-scanner-m.cc"
yy62:
	++s;
	if (lim <= s) return false;
	yych = *s;
yy63:
	switch (yych) {
		case 0x00:
		case '\n': goto yy64;
		case '"': goto yy65;
		case '\\': goto yy67;
		default: goto yy62;
	}
yy64:
	s = m;
	switch (yyaccept) {
		case 0: goto yy3;
		case 1: goto yy27;
		case 2: goto yy31;
		case 3: goto yy45;
		case 4: goto yy79;
		default: goto yy66;
	}
yy65:
	++s;
yy66:
	re2c_scanner_m_c = yycSTARTEXP;
#line 65 "re2c-scanner-m.re"
	{ return TOKEN_STRING; }
#line 925 "re2c-scanner-m.cc"
yy67:
	++s;
	if (lim <= s) return false;
	yych = *s;
	switch (yych) {
		case 0x00:
		case '\n': goto yy64;
		case '"': goto yy100;
		case '\\': goto yy67;
		default: goto yy62;
	}
yy68:
	++s;
	re2c_scanner_m_c = yycSTARTEXP;
#line 100 "re2c-scanner-m.re"
	{ return TOKEN_DOUBLE_AND; }
#line 942 "re2c-scanner-m.cc"
yy69:
	++s;
	re2c_scanner_m_c = yycSTARTEXP;
#line 123 "re2c-scanner-m.re"
	{ return TOKEN_MULT_EQUAL; }
#line 948 "re2c-scanner-m.cc"
yy70:
	++s;
	re2c_scanner_m_c = yycSTARTEXP;
#line 119 "re2c-scanner-m.re"
	{ return TOKEN_PLUS_EQUAL; }
#line 954 "re2c-scanner-m.cc"
yy71:
	++s;
	re2c_scanner_m_c = yycSTARTEXP;
#line 120 "re2c-scanner-m.re"
	{ return TOKEN_MINUS_EQUAL; }
#line 960 "re2c-scanner-m.cc"
yy72:
	++s;
	re2c_scanner_m_c = yycSTARTEXP;
#line 117 "re2c-scanner-m.re"
	{ return TOKEN_DOTAPOS; }
#line 966 "re2c-scanner-m.cc"
yy73:
	yych = *++s;
	switch (yych) {
		case '=': goto yy101;
		default: goto yy74;
	}
yy74:
	re2c_scanner_m_c = yycSTARTEXP;
#line 113 "re2c-scanner-m.re"
	{ return TOKEN_DOTMULT; }
#line 977 "re2c-scanner-m.cc"
yy75:
	yych = *++s;
	switch (yych) {
		case '.': goto yy102;
		default: goto yy64;
	}
yy76:
	yych = *++s;
	switch (yych) {
		case '=': goto yy104;
		default: goto yy77;
	}
yy77:
	re2c_scanner_m_c = yycSTARTEXP;
#line 114 "re2c-scanner-m.re"
	{ return TOKEN_DOTDIV; }
#line 994 "re2c-scanner-m.cc"
yy78:
	yyaccept = 4;
	m = ++s;
	if ((lim - s) < 3) return false;
	yych = *s;
	switch (yych) {
		case '0':
		case '1':
		case '2':
		case '3':
		case '4':
		case '5':
		case '6':
		case '7':
		case '8':
		case '9': goto yy78;
		case 'D':
		case 'E':
		case 'd':
		case 'e': goto yy86;
		case 'F':
		case 'I':
		case 'L':
		case 'f':
		case 'i':
		case 'l': goto yy87;
		default: goto yy79;
	}
yy79:
#line 67 "re2c-scanner-m.re"
	{ return TOKEN_FLOAT; }
#line 1026 "re2c-scanner-m.cc"
yy80:
	yych = *++s;
	switch (yych) {
		case '=': goto yy105;
		default: goto yy81;
	}
yy81:
	re2c_scanner_m_c = yycSTARTEXP;
#line 115 "re2c-scanner-m.re"
	{ return TOKEN_DOTBACKSLASH; }
#line 1037 "re2c-scanner-m.cc"
yy82:
	yych = *++s;
	switch (yych) {
		case '=': goto yy106;
		default: goto yy83;
	}
yy83:
	re2c_scanner_m_c = yycSTARTEXP;
#line 116 "re2c-scanner-m.re"
	{ return TOKEN_DOTPOW; }
#line 1048 "re2c-scanner-m.cc"
yy84:
	++s;
	re2c_scanner_m_c = yycSTARTEXP;
#line 121 "re2c-scanner-m.re"
	{ return TOKEN_DIV_EQUAL; }
#line 1054 "re2c-scanner-m.cc"
yy85:
	yych = *++s;
	switch (yych) {
		case '*':
		case '.':
		case '/':
		case '\\':
		case '^': goto yy64;
		case '0':
		case '1':
		case '2':
		case '3':
		case '4':
		case '5':
		case '6':
		case '7':
		case '8':
		case '9': goto yy78;
		default: goto yy107;
	}
yy86:
	yych = *++s;
	switch (yych) {
		case '+':
		case '-': goto yy108;
		case '0':
		case '1':
		case '2':
		case '3':
		case '4':
		case '5':
		case '6':
		case '7':
		case '8':
		case '9': goto yy109;
		default: goto yy64;
	}
yy87:
	++s;
	goto yy79;
yy88:
	++s;
	if (lim <= s) return false;
	yych = *s;
	switch (yych) {
		case 'L':
		case 'U':
		case 'l':
		case 'u': goto yy88;
		default: goto yy31;
	}
yy89:
	yych = *++s;
	switch (yych) {
		case '0':
		case '1':
		case '2':
		case '3':
		case '4':
		case '5':
		case '6':
		case '7':
		case '8':
		case '9': goto yy110;
		default: goto yy64;
	}
yy90:
	++s;
	re2c_scanner_m_c = yycSTARTEXP;
#line 84 "re2c-scanner-m.re"
	{ return TOKEN_LE; }
#line 1126 "re2c-scanner-m.cc"
yy91:
	++s;
	re2c_scanner_m_c = yycSTARTEXP;
#line 87 "re2c-scanner-m.re"
	{ return TOKEN_DOUBLE_EQUAL; }
#line 1132 "re2c-scanner-m.cc"
yy92:
	++s;
	re2c_scanner_m_c = yycSTARTEXP;
#line 85 "re2c-scanner-m.re"
	{ return TOKEN_GE; }
#line 1138 "re2c-scanner-m.cc"
yy93:
	++s;
	if (lim <= s) return false;
	yych = *s;
	switch (yych) {
		case 0x80:
		case 0x81:
		case 0x82:
		case 0x83:
		case 0x84:
		case 0x85:
		case 0x86:
		case 0x87:
		case 0x88:
		case 0x89:
		case 0x8A:
		case 0x8B:
		case 0x8C:
		case 0x8D:
		case 0x8E:
		case 0x8F:
		case 0x90:
		case 0x91:
		case 0x92:
		case 0x93:
		case 0x94:
		case 0x95:
		case 0x96:
		case 0x97:
		case 0x98:
		case 0x99:
		case 0x9A:
		case 0x9B:
		case 0x9C:
		case 0x9D:
		case 0x9E:
		case 0x9F:
		case 0xA0:
		case 0xA1:
		case 0xA2:
		case 0xA3:
		case 0xA4:
		case 0xA5:
		case 0xA6:
		case 0xA7:
		case 0xA8:
		case 0xA9:
		case 0xAA:
		case 0xAB:
		case 0xAC:
		case 0xAD:
		case 0xAE:
		case 0xAF:
		case 0xB0:
		case 0xB1:
		case 0xB2:
		case 0xB3:
		case 0xB4:
		case 0xB5:
		case 0xB6:
		case 0xB7:
		case 0xB8:
		case 0xB9:
		case 0xBA:
		case 0xBB:
		case 0xBC:
		case 0xBD:
		case 0xBE:
		case 0xBF: goto yy44;
		default: goto yy64;
	}
yy94:
	++s;
	if (lim <= s) return false;
	yych = *s;
	switch (yych) {
		case 0x80:
		case 0x81:
		case 0x82:
		case 0x83:
		case 0x84:
		case 0x85:
		case 0x86:
		case 0x87:
		case 0x88:
		case 0x89:
		case 0x8A:
		case 0x8B:
		case 0x8C:
		case 0x8D:
		case 0x8E:
		case 0x8F:
		case 0x90:
		case 0x91:
		case 0x92:
		case 0x93:
		case 0x94:
		case 0x95:
		case 0x96:
		case 0x97:
		case 0x98:
		case 0x99:
		case 0x9A:
		case 0x9B:
		case 0x9C:
		case 0x9D:
		case 0x9E:
		case 0x9F:
		case 0xA0:
		case 0xA1:
		case 0xA2:
		case 0xA3:
		case 0xA4:
		case 0xA5:
		case 0xA6:
		case 0xA7:
		case 0xA8:
		case 0xA9:
		case 0xAA:
		case 0xAB:
		case 0xAC:
		case 0xAD:
		case 0xAE:
		case 0xAF:
		case 0xB0:
		case 0xB1:
		case 0xB2:
		case 0xB3:
		case 0xB4:
		case 0xB5:
		case 0xB6:
		case 0xB7:
		case 0xB8:
		case 0xB9:
		case 0xBA:
		case 0xBB:
		case 0xBC:
		case 0xBD:
		case 0xBE:
		case 0xBF: goto yy93;
		default: goto yy64;
	}
yy95:
	++s;
	if (lim <= s) return false;
	yych = *s;
	switch (yych) {
		case 0x80:
		case 0x81:
		case 0x82:
		case 0x83:
		case 0x84:
		case 0x85:
		case 0x86:
		case 0x87:
		case 0x88:
		case 0x89:
		case 0x8A:
		case 0x8B:
		case 0x8C:
		case 0x8D:
		case 0x8E:
		case 0x8F:
		case 0x90:
		case 0x91:
		case 0x92:
		case 0x93:
		case 0x94:
		case 0x95:
		case 0x96:
		case 0x97:
		case 0x98:
		case 0x99:
		case 0x9A:
		case 0x9B:
		case 0x9C:
		case 0x9D:
		case 0x9E:
		case 0x9F:
		case 0xA0:
		case 0xA1:
		case 0xA2:
		case 0xA3:
		case 0xA4:
		case 0xA5:
		case 0xA6:
		case 0xA7:
		case 0xA8:
		case 0xA9:
		case 0xAA:
		case 0xAB:
		case 0xAC:
		case 0xAD:
		case 0xAE:
		case 0xAF:
		case 0xB0:
		case 0xB1:
		case 0xB2:
		case 0xB3:
		case 0xB4:
		case 0xB5:
		case 0xB6:
		case 0xB7:
		case 0xB8:
		case 0xB9:
		case 0xBA:
		case 0xBB:
		case 0xBC:
		case 0xBD:
		case 0xBE:
		case 0xBF: goto yy94;
		default: goto yy64;
	}
yy96:
	++s;
	re2c_scanner_m_c = yycSTARTEXP;
#line 122 "re2c-scanner-m.re"
	{ return TOKEN_BACKSLASH_EQUAL; }
#line 1357 "re2c-scanner-m.cc"
yy97:
	++s;
	re2c_scanner_m_c = yycSTARTEXP;
#line 124 "re2c-scanner-m.re"
	{ return TOKEN_POW_EQUAL; }
#line 1363 "re2c-scanner-m.cc"
yy98:
	++s;
	re2c_scanner_m_c = yycSTARTEXP;
#line 102 "re2c-scanner-m.re"
	{ return TOKEN_DOUBLE_OR; }
#line 1369 "re2c-scanner-m.cc"
yy99:
	++s;
	re2c_scanner_m_c = yycSTARTEXP;
#line 89 "re2c-scanner-m.re"
	{ return TOKEN_NOT_EQUAL; }
#line 1375 "re2c-scanner-m.cc"
yy100:
	yyaccept = 5;
	m = ++s;
	if (lim <= s) return false;
	yych = *s;
	switch (yych) {
		case 0x00:
		case '\n': goto yy66;
		case '"': goto yy65;
		case '\\': goto yy67;
		default: goto yy62;
	}
yy101:
	++s;
	re2c_scanner_m_c = yycSTARTEXP;
#line 128 "re2c-scanner-m.re"
	{ return TOKEN_DOT_MULT_EQUAL; }
#line 1393 "re2c-scanner-m.cc"
yy102:
	++s;
	if (lim <= s) return false;
	yych = *s;
	switch (yych) {
		case '.': goto yy102;
		default: goto yy103;
	}
yy103:
	re2c_scanner_m_c = yycSTARTEXP;
#line 141 "re2c-scanner-m.re"
	{ return TOKEN_TRIPLE_DOT; }
#line 1406 "re2c-scanner-m.cc"
yy104:
	++s;
	re2c_scanner_m_c = yycSTARTEXP;
#line 126 "re2c-scanner-m.re"
	{ return TOKEN_DOT_DIV_EQUAL; }
#line 1412 "re2c-scanner-m.cc"
yy105:
	++s;
	re2c_scanner_m_c = yycSTARTEXP;
#line 127 "re2c-scanner-m.re"
	{ return TOKEN_DOT_BACKSLASH_EQUAL; }
#line 1418 "re2c-scanner-m.cc"
yy106:
	++s;
	re2c_scanner_m_c = yycSTARTEXP;
#line 129 "re2c-scanner-m.re"
	{ return TOKEN_DOT_POW_EQUAL; }
#line 1424 "re2c-scanner-m.cc"
yy107:
	++s;
	s -= 1;
#line 68 "re2c-scanner-m.re"
	{ return TOKEN_FLOAT; }
#line 1430 "re2c-scanner-m.cc"
yy108:
	yych = *++s;
	switch (yych) {
		case '0':
		case '1':
		case '2':
		case '3':
		case '4':
		case '5':
		case '6':
		case '7':
		case '8':
		case '9': goto yy109;
		default: goto yy64;
	}
yy109:
	++s;
	if (lim <= s) return false;
	yych = *s;
	switch (yych) {
		case '0':
		case '1':
		case '2':
		case '3':
		case '4':
		case '5':
		case '6':
		case '7':
		case '8':
		case '9': goto yy109;
		case 'F':
		case 'I':
		case 'L':
		case 'f':
		case 'i':
		case 'l': goto yy87;
		default: goto yy79;
	}
yy110:
	++s;
	if (lim <= s) return false;
	yych = *s;
	switch (yych) {
		case '0':
		case '1':
		case '2':
		case '3':
		case '4':
		case '5':
		case '6':
		case '7':
		case '8':
		case '9': goto yy110;
		case 'L':
		case 'U':
		case 'l':
		case 'u': goto yy88;
		default: goto yy31;
	}
/* *********************************** */
yyc_STARTEXP:
	if ((lim - s) < 4) return false;
	yych = *s;
	switch (yych) {
		case 0x00: goto yy112;
		case '\t': goto yy115;
		case '\n': goto yy116;
		case '\r': goto yy117;
		case ' ': goto yy118;
		case '!': goto yy120;
		case '"': goto yy122;
		case '#': goto yy123;
		case '%': goto yy124;
		case '&': goto yy125;
		case '\'': goto yy127;
		case '(': goto yy129;
		case ')': goto yy130;
		case '*': goto yy131;
		case '+': goto yy133;
		case ',': goto yy135;
		case '-': goto yy136;
		case '.': goto yy138;
		case '/': goto yy140;
		case '0': goto yy142;
		case '1':
		case '2':
		case '3':
		case '4':
		case '5':
		case '6':
		case '7':
		case '8':
		case '9': goto yy144;
		case ':': goto yy146;
		case ';': goto yy147;
		case '<': goto yy148;
		case '=': goto yy150;
		case '>': goto yy152;
		case '?': goto yy154;
		case '@': goto yy155;
		case 'A':
		case 'B':
		case 'C':
		case 'D':
		case 'E':
		case 'F':
		case 'G':
		case 'H':
		case 'I':
		case 'J':
		case 'K':
		case 'L':
		case 'M':
		case 'N':
		case 'O':
		case 'P':
		case 'Q':
		case 'R':
		case 'S':
		case 'T':
		case 'U':
		case 'V':
		case 'W':
		case 'X':
		case 'Y':
		case 'Z':
		case '_':
		case 'a':
		case 'b':
		case 'c':
		case 'd':
		case 'e':
		case 'f':
		case 'g':
		case 'h':
		case 'i':
		case 'j':
		case 'k':
		case 'l':
		case 'm':
		case 'n':
		case 'o':
		case 'p':
		case 'q':
		case 'r':
		case 's':
		case 't':
		case 'u':
		case 'v':
		case 'w':
		case 'x':
		case 'y':
		case 'z': goto yy156;
		case '[': goto yy158;
		case '\\': goto yy159;
		case ']': goto yy161;
		case '^': goto yy162;
		case '{': goto yy164;
		case '|': goto yy165;
		case '}': goto yy167;
		case '~': goto yy168;
		case 0xC0:
		case 0xC1:
		case 0xC2:
		case 0xC3:
		case 0xC4:
		case 0xC5:
		case 0xC6:
		case 0xC7:
		case 0xC8:
		case 0xC9:
		case 0xCA:
		case 0xCB:
		case 0xCC:
		case 0xCD:
		case 0xCE:
		case 0xCF:
		case 0xD0:
		case 0xD1:
		case 0xD2:
		case 0xD3:
		case 0xD4:
		case 0xD5:
		case 0xD6:
		case 0xD7:
		case 0xD8:
		case 0xD9:
		case 0xDA:
		case 0xDB:
		case 0xDC:
		case 0xDD:
		case 0xDE:
		case 0xDF: goto yy170;
		case 0xE0:
		case 0xE1:
		case 0xE2:
		case 0xE3:
		case 0xE4:
		case 0xE5:
		case 0xE6:
		case 0xE7:
		case 0xE8:
		case 0xE9:
		case 0xEA:
		case 0xEB:
		case 0xEC:
		case 0xED:
		case 0xEE:
		case 0xEF: goto yy171;
		case 0xF0:
		case 0xF1:
		case 0xF2:
		case 0xF3:
		case 0xF4:
		case 0xF5:
		case 0xF6:
		case 0xF7: goto yy172;
		default: goto yy113;
	}
yy112:
	++s;
	re2c_scanner_m_c = yycINITIAL;
#line 143 "re2c-scanner-m.re"
	{ return TOKEN_EOF; }
#line 1655 "re2c-scanner-m.cc"
yy113:
	++s;
yy114:
	re2c_scanner_m_c = yycINITIAL;
#line 145 "re2c-scanner-m.re"
	{ return TOKEN_ILLEGAL_CHAR; }
#line 1662 "re2c-scanner-m.cc"
yy115:
	++s;
#line 137 "re2c-scanner-m.re"
	{ return TOKEN_TAB; }
#line 1667 "re2c-scanner-m.cc"
yy116:
	++s;
#line 136 "re2c-scanner-m.re"
	{ return TOKEN_NEWLINE; }
#line 1672 "re2c-scanner-m.cc"
yy117:
	++s;
#line 135 "re2c-scanner-m.re"
	{ return TOKEN_CRETURN; }
#line 1677 "re2c-scanner-m.cc"
yy118:
	++s;
	if (lim <= s) return false;
	yych = *s;
	switch (yych) {
		case ' ': goto yy118;
		default: goto yy119;
	}
yy119:
#line 138 "re2c-scanner-m.re"
	{ return TOKEN_SPACE; }
#line 1689 "re2c-scanner-m.cc"
yy120:
	yych = *++s;
	switch (yych) {
		case '=': goto yy173;
		default: goto yy121;
	}
yy121:
#line 92 "re2c-scanner-m.re"
	{ return TOKEN_EXCLAM; }
#line 1699 "re2c-scanner-m.cc"
yy122:
	yyaccept = 0;
	yych = *(m = ++s);
	switch (yych) {
		case 0x00:
		case '\n': goto yy114;
		default: goto yy175;
	}
yy123:
	++s;
	re2c_scanner_m_c = yycINITIAL;
#line 133 "re2c-scanner-m.re"
	{ return TOKEN_HASH; }
#line 1713 "re2c-scanner-m.cc"
yy124:
	++s;
#line 108 "re2c-scanner-m.re"
	{ return TOKEN_MOD; }
#line 1718 "re2c-scanner-m.cc"
yy125:
	yych = *++s;
	switch (yych) {
		case '&': goto yy180;
		default: goto yy126;
	}
yy126:
#line 99 "re2c-scanner-m.re"
	{ return TOKEN_AND; }
#line 1728 "re2c-scanner-m.cc"
yy127:
	yyaccept = 1;
	yych = *(m = ++s);
	switch (yych) {
		case 0x00:
		case '\n': goto yy128;
		default: goto yy182;
	}
yy128:
#line 111 "re2c-scanner-m.re"
	{ return TOKEN_APOS; }
#line 1740 "re2c-scanner-m.cc"
yy129:
	++s;
#line 70 "re2c-scanner-m.re"
	{ return TOKEN_L_PAREN; }
#line 1745 "re2c-scanner-m.cc"
yy130:
	++s;
	re2c_scanner_m_c = yycINITIAL;
#line 71 "re2c-scanner-m.re"
	{ return TOKEN_R_PAREN; }
#line 1751 "re2c-scanner-m.cc"
yy131:
	yych = *++s;
	switch (yych) {
		case '=': goto yy184;
		default: goto yy132;
	}
yy132:
#line 107 "re2c-scanner-m.re"
	{ return TOKEN_MULT; }
#line 1761 "re2c-scanner-m.cc"
yy133:
	yych = *++s;
	switch (yych) {
		case '=': goto yy185;
		default: goto yy134;
	}
yy134:
#line 104 "re2c-scanner-m.re"
	{ return TOKEN_PLUS; }
#line 1771 "re2c-scanner-m.cc"
yy135:
	++s;
#line 95 "re2c-scanner-m.re"
	{ return TOKEN_COMMA; }
#line 1776 "re2c-scanner-m.cc"
yy136:
	yych = *++s;
	switch (yych) {
		case '=': goto yy186;
		default: goto yy137;
	}
yy137:
#line 105 "re2c-scanner-m.re"
	{ return TOKEN_MINUS; }
#line 1786 "re2c-scanner-m.cc"
yy138:
	yyaccept = 2;
	yych = *(m = ++s);
	switch (yych) {
		case '\'': goto yy187;
		case '*': goto yy188;
		case '.': goto yy190;
		case '/': goto yy191;
		case '0':
		case '1':
		case '2':
		case '3':
		case '4':
		case '5':
		case '6':
		case '7':
		case '8':
		case '9': goto yy193;
		case '\\': goto yy195;
		case '^': goto yy197;
		default: goto yy139;
	}
yy139:
#line 97 "re2c-scanner-m.re"
	{ return TOKEN_FULL_STOP; }
#line 1812 "re2c-scanner-m.cc"
yy140:
	yych = *++s;
	switch (yych) {
		case '=': goto yy199;
		default: goto yy141;
	}
yy141:
#line 106 "re2c-scanner-m.re"
	{ return TOKEN_DIV; }
#line 1822 "re2c-scanner-m.cc"
yy142:
	yyaccept = 3;
	yych = *(m = ++s);
	switch (yych) {
		case 'x': goto yy204;
		default: goto yy145;
	}
yy143:
	re2c_scanner_m_c = yycINITIAL;
#line 64 "re2c-scanner-m.re"
	{ return TOKEN_INTEGER; }
#line 1834 "re2c-scanner-m.cc"
yy144:
	yyaccept = 3;
	m = ++s;
	if ((lim - s) < 3) return false;
	yych = *s;
yy145:
	switch (yych) {
		case '.': goto yy200;
		case '0':
		case '1':
		case '2':
		case '3':
		case '4':
		case '5':
		case '6':
		case '7':
		case '8':
		case '9': goto yy144;
		case 'D':
		case 'E':
		case 'd':
		case 'e': goto yy201;
		case 'F':
		case 'I':
		case 'f':
		case 'i': goto yy202;
		case 'L':
		case 'U':
		case 'l':
		case 'u': goto yy203;
		default: goto yy143;
	}
yy146:
	++s;
#line 94 "re2c-scanner-m.re"
	{ return TOKEN_COLON; }
#line 1871 "re2c-scanner-m.cc"
yy147:
	++s;
#line 96 "re2c-scanner-m.re"
	{ return TOKEN_SEMICOLON; }
#line 1876 "re2c-scanner-m.cc"
yy148:
	yych = *++s;
	switch (yych) {
		case '=': goto yy205;
		default: goto yy149;
	}
yy149:
#line 81 "re2c-scanner-m.re"
	{ return TOKEN_LESS; }
#line 1886 "re2c-scanner-m.cc"
yy150:
	yych = *++s;
	switch (yych) {
		case '=': goto yy206;
		default: goto yy151;
	}
yy151:
#line 79 "re2c-scanner-m.re"
	{ return TOKEN_EQUAL; }
#line 1896 "re2c-scanner-m.cc"
yy152:
	yych = *++s;
	switch (yych) {
		case '=': goto yy207;
		default: goto yy153;
	}
yy153:
#line 82 "re2c-scanner-m.re"
	{ return TOKEN_GREATER; }
#line 1906 "re2c-scanner-m.cc"
yy154:
	++s;
#line 93 "re2c-scanner-m.re"
	{ return TOKEN_QUESTION; }
#line 1911 "re2c-scanner-m.cc"
yy155:
	++s;
#line 131 "re2c-scanner-m.re"
	{ return TOKEN_AT; }
#line 1916 "re2c-scanner-m.cc"
yy156:
	yyaccept = 4;
	m = ++s;
	if (lim <= s) return false;
	yych = *s;
	switch (yych) {
		case '0':
		case '1':
		case '2':
		case '3':
		case '4':
		case '5':
		case '6':
		case '7':
		case '8':
		case '9':
		case 'A':
		case 'B':
		case 'C':
		case 'D':
		case 'E':
		case 'F':
		case 'G':
		case 'H':
		case 'I':
		case 'J':
		case 'K':
		case 'L':
		case 'M':
		case 'N':
		case 'O':
		case 'P':
		case 'Q':
		case 'R':
		case 'S':
		case 'T':
		case 'U':
		case 'V':
		case 'W':
		case 'X':
		case 'Y':
		case 'Z':
		case '_':
		case 'a':
		case 'b':
		case 'c':
		case 'd':
		case 'e':
		case 'f':
		case 'g':
		case 'h':
		case 'i':
		case 'j':
		case 'k':
		case 'l':
		case 'm':
		case 'n':
		case 'o':
		case 'p':
		case 'q':
		case 'r':
		case 's':
		case 't':
		case 'u':
		case 'v':
		case 'w':
		case 'x':
		case 'y':
		case 'z': goto yy156;
		case 0xC0:
		case 0xC1:
		case 0xC2:
		case 0xC3:
		case 0xC4:
		case 0xC5:
		case 0xC6:
		case 0xC7:
		case 0xC8:
		case 0xC9:
		case 0xCA:
		case 0xCB:
		case 0xCC:
		case 0xCD:
		case 0xCE:
		case 0xCF:
		case 0xD0:
		case 0xD1:
		case 0xD2:
		case 0xD3:
		case 0xD4:
		case 0xD5:
		case 0xD6:
		case 0xD7:
		case 0xD8:
		case 0xD9:
		case 0xDA:
		case 0xDB:
		case 0xDC:
		case 0xDD:
		case 0xDE:
		case 0xDF: goto yy208;
		case 0xE0:
		case 0xE1:
		case 0xE2:
		case 0xE3:
		case 0xE4:
		case 0xE5:
		case 0xE6:
		case 0xE7:
		case 0xE8:
		case 0xE9:
		case 0xEA:
		case 0xEB:
		case 0xEC:
		case 0xED:
		case 0xEE:
		case 0xEF: goto yy209;
		case 0xF0:
		case 0xF1:
		case 0xF2:
		case 0xF3:
		case 0xF4:
		case 0xF5:
		case 0xF6:
		case 0xF7: goto yy210;
		default: goto yy157;
	}
yy157:
	re2c_scanner_m_c = yycINITIAL;
#line 139 "re2c-scanner-m.re"
	{ return TOKEN_IDENTIFIER; }
#line 2048 "re2c-scanner-m.cc"
yy158:
	++s;
#line 76 "re2c-scanner-m.re"
	{ return TOKEN_L_BRACKET; }
#line 2053 "re2c-scanner-m.cc"
yy159:
	yych = *++s;
	switch (yych) {
		case '=': goto yy211;
		default: goto yy160;
	}
yy160:
#line 109 "re2c-scanner-m.re"
	{ return TOKEN_BACKSLASH; }
#line 2063 "re2c-scanner-m.cc"
yy161:
	++s;
	re2c_scanner_m_c = yycINITIAL;
#line 77 "re2c-scanner-m.re"
	{ return TOKEN_R_BRACKET; }
#line 2069 "re2c-scanner-m.cc"
yy162:
	yych = *++s;
	switch (yych) {
		case '=': goto yy212;
		default: goto yy163;
	}
yy163:
#line 110 "re2c-scanner-m.re"
	{ return TOKEN_POW; }
#line 2079 "re2c-scanner-m.cc"
yy164:
	++s;
#line 73 "re2c-scanner-m.re"
	{ return TOKEN_L_BRACE; }
#line 2084 "re2c-scanner-m.cc"
yy165:
	yych = *++s;
	switch (yych) {
		case '|': goto yy213;
		default: goto yy166;
	}
yy166:
#line 101 "re2c-scanner-m.re"
	{ return TOKEN_OR; }
#line 2094 "re2c-scanner-m.cc"
yy167:
	++s;
	re2c_scanner_m_c = yycINITIAL;
#line 74 "re2c-scanner-m.re"
	{ return TOKEN_R_BRACE; }
#line 2100 "re2c-scanner-m.cc"
yy168:
	yych = *++s;
	switch (yych) {
		case '=': goto yy214;
		default: goto yy169;
	}
yy169:
#line 91 "re2c-scanner-m.re"
	{ return TOKEN_TILDE; }
#line 2110 "re2c-scanner-m.cc"
yy170:
	yych = *++s;
	switch (yych) {
		case 0x80:
		case 0x81:
		case 0x82:
		case 0x83:
		case 0x84:
		case 0x85:
		case 0x86:
		case 0x87:
		case 0x88:
		case 0x89:
		case 0x8A:
		case 0x8B:
		case 0x8C:
		case 0x8D:
		case 0x8E:
		case 0x8F:
		case 0x90:
		case 0x91:
		case 0x92:
		case 0x93:
		case 0x94:
		case 0x95:
		case 0x96:
		case 0x97:
		case 0x98:
		case 0x99:
		case 0x9A:
		case 0x9B:
		case 0x9C:
		case 0x9D:
		case 0x9E:
		case 0x9F:
		case 0xA0:
		case 0xA1:
		case 0xA2:
		case 0xA3:
		case 0xA4:
		case 0xA5:
		case 0xA6:
		case 0xA7:
		case 0xA8:
		case 0xA9:
		case 0xAA:
		case 0xAB:
		case 0xAC:
		case 0xAD:
		case 0xAE:
		case 0xAF:
		case 0xB0:
		case 0xB1:
		case 0xB2:
		case 0xB3:
		case 0xB4:
		case 0xB5:
		case 0xB6:
		case 0xB7:
		case 0xB8:
		case 0xB9:
		case 0xBA:
		case 0xBB:
		case 0xBC:
		case 0xBD:
		case 0xBE:
		case 0xBF: goto yy156;
		default: goto yy114;
	}
yy171:
	yyaccept = 0;
	yych = *(m = ++s);
	switch (yych) {
		case 0x80:
		case 0x81:
		case 0x82:
		case 0x83:
		case 0x84:
		case 0x85:
		case 0x86:
		case 0x87:
		case 0x88:
		case 0x89:
		case 0x8A:
		case 0x8B:
		case 0x8C:
		case 0x8D:
		case 0x8E:
		case 0x8F:
		case 0x90:
		case 0x91:
		case 0x92:
		case 0x93:
		case 0x94:
		case 0x95:
		case 0x96:
		case 0x97:
		case 0x98:
		case 0x99:
		case 0x9A:
		case 0x9B:
		case 0x9C:
		case 0x9D:
		case 0x9E:
		case 0x9F:
		case 0xA0:
		case 0xA1:
		case 0xA2:
		case 0xA3:
		case 0xA4:
		case 0xA5:
		case 0xA6:
		case 0xA7:
		case 0xA8:
		case 0xA9:
		case 0xAA:
		case 0xAB:
		case 0xAC:
		case 0xAD:
		case 0xAE:
		case 0xAF:
		case 0xB0:
		case 0xB1:
		case 0xB2:
		case 0xB3:
		case 0xB4:
		case 0xB5:
		case 0xB6:
		case 0xB7:
		case 0xB8:
		case 0xB9:
		case 0xBA:
		case 0xBB:
		case 0xBC:
		case 0xBD:
		case 0xBE:
		case 0xBF: goto yy208;
		default: goto yy114;
	}
yy172:
	yyaccept = 0;
	yych = *(m = ++s);
	switch (yych) {
		case 0x80:
		case 0x81:
		case 0x82:
		case 0x83:
		case 0x84:
		case 0x85:
		case 0x86:
		case 0x87:
		case 0x88:
		case 0x89:
		case 0x8A:
		case 0x8B:
		case 0x8C:
		case 0x8D:
		case 0x8E:
		case 0x8F:
		case 0x90:
		case 0x91:
		case 0x92:
		case 0x93:
		case 0x94:
		case 0x95:
		case 0x96:
		case 0x97:
		case 0x98:
		case 0x99:
		case 0x9A:
		case 0x9B:
		case 0x9C:
		case 0x9D:
		case 0x9E:
		case 0x9F:
		case 0xA0:
		case 0xA1:
		case 0xA2:
		case 0xA3:
		case 0xA4:
		case 0xA5:
		case 0xA6:
		case 0xA7:
		case 0xA8:
		case 0xA9:
		case 0xAA:
		case 0xAB:
		case 0xAC:
		case 0xAD:
		case 0xAE:
		case 0xAF:
		case 0xB0:
		case 0xB1:
		case 0xB2:
		case 0xB3:
		case 0xB4:
		case 0xB5:
		case 0xB6:
		case 0xB7:
		case 0xB8:
		case 0xB9:
		case 0xBA:
		case 0xBB:
		case 0xBC:
		case 0xBD:
		case 0xBE:
		case 0xBF: goto yy209;
		default: goto yy114;
	}
yy173:
	++s;
#line 88 "re2c-scanner-m.re"
	{ return TOKEN_NOT_EQUAL; }
#line 2324 "re2c-scanner-m.cc"
yy174:
	++s;
	if (lim <= s) return false;
	yych = *s;
yy175:
	switch (yych) {
		case 0x00:
		case '\n': goto yy176;
		case '"': goto yy177;
		case '\\': goto yy179;
		default: goto yy174;
	}
yy176:
	s = m;
	switch (yyaccept) {
		case 0: goto yy114;
		case 1: goto yy128;
		case 2: goto yy139;
		case 3: goto yy143;
		case 4: goto yy157;
		case 5: goto yy194;
		default: goto yy178;
	}
yy177:
	++s;
yy178:
#line 65 "re2c-scanner-m.re"
	{ return TOKEN_STRING; }
#line 2353 "re2c-scanner-m.cc"
yy179:
	++s;
	if (lim <= s) return false;
	yych = *s;
	switch (yych) {
		case 0x00:
		case '\n': goto yy176;
		case '"': goto yy215;
		case '\\': goto yy179;
		default: goto yy174;
	}
yy180:
	++s;
#line 100 "re2c-scanner-m.re"
	{ return TOKEN_DOUBLE_AND; }
#line 2369 "re2c-scanner-m.cc"
yy181:
	++s;
	if (lim <= s) return false;
	yych = *s;
yy182:
	switch (yych) {
		case 0x00:
		case '\n': goto yy176;
		case '\'': goto yy183;
		default: goto yy181;
	}
yy183:
	++s;
#line 66 "re2c-scanner-m.re"
	{ return TOKEN_STRING; }
#line 2385 "re2c-scanner-m.cc"
yy184:
	++s;
#line 123 "re2c-scanner-m.re"
	{ return TOKEN_MULT_EQUAL; }
#line 2390 "re2c-scanner-m.cc"
yy185:
	++s;
#line 119 "re2c-scanner-m.re"
	{ return TOKEN_PLUS_EQUAL; }
#line 2395 "re2c-scanner-m.cc"
yy186:
	++s;
#line 120 "re2c-scanner-m.re"
	{ return TOKEN_MINUS_EQUAL; }
#line 2400 "re2c-scanner-m.cc"
yy187:
	++s;
#line 117 "re2c-scanner-m.re"
	{ return TOKEN_DOTAPOS; }
#line 2405 "re2c-scanner-m.cc"
yy188:
	yych = *++s;
	switch (yych) {
		case '=': goto yy216;
		default: goto yy189;
	}
yy189:
#line 113 "re2c-scanner-m.re"
	{ return TOKEN_DOTMULT; }
#line 2415 "re2c-scanner-m.cc"
yy190:
	yych = *++s;
	switch (yych) {
		case '.': goto yy217;
		default: goto yy176;
	}
yy191:
	yych = *++s;
	switch (yych) {
		case '=': goto yy219;
		default: goto yy192;
	}
yy192:
#line 114 "re2c-scanner-m.re"
	{ return TOKEN_DOTDIV; }
#line 2431 "re2c-scanner-m.cc"
yy193:
	yyaccept = 5;
	m = ++s;
	if ((lim - s) < 3) return false;
	yych = *s;
	switch (yych) {
		case '0':
		case '1':
		case '2':
		case '3':
		case '4':
		case '5':
		case '6':
		case '7':
		case '8':
		case '9': goto yy193;
		case 'D':
		case 'E':
		case 'd':
		case 'e': goto yy201;
		case 'F':
		case 'I':
		case 'L':
		case 'f':
		case 'i':
		case 'l': goto yy202;
		default: goto yy194;
	}
yy194:
	re2c_scanner_m_c = yycINITIAL;
#line 67 "re2c-scanner-m.re"
	{ return TOKEN_FLOAT; }
#line 2464 "re2c-scanner-m.cc"
yy195:
	yych = *++s;
	switch (yych) {
		case '=': goto yy220;
		default: goto yy196;
	}
yy196:
#line 115 "re2c-scanner-m.re"
	{ return TOKEN_DOTBACKSLASH; }
#line 2474 "re2c-scanner-m.cc"
yy197:
	yych = *++s;
	switch (yych) {
		case '=': goto yy221;
		default: goto yy198;
	}
yy198:
#line 116 "re2c-scanner-m.re"
	{ return TOKEN_DOTPOW; }
#line 2484 "re2c-scanner-m.cc"
yy199:
	++s;
#line 121 "re2c-scanner-m.re"
	{ return TOKEN_DIV_EQUAL; }
#line 2489 "re2c-scanner-m.cc"
yy200:
	yych = *++s;
	switch (yych) {
		case '*':
		case '.':
		case '/':
		case '\\':
		case '^': goto yy176;
		case '0':
		case '1':
		case '2':
		case '3':
		case '4':
		case '5':
		case '6':
		case '7':
		case '8':
		case '9': goto yy193;
		default: goto yy222;
	}
yy201:
	yych = *++s;
	switch (yych) {
		case '+':
		case '-': goto yy223;
		case '0':
		case '1':
		case '2':
		case '3':
		case '4':
		case '5':
		case '6':
		case '7':
		case '8':
		case '9': goto yy224;
		default: goto yy176;
	}
yy202:
	++s;
	goto yy194;
yy203:
	++s;
	if (lim <= s) return false;
	yych = *s;
	switch (yych) {
		case 'L':
		case 'U':
		case 'l':
		case 'u': goto yy203;
		default: goto yy143;
	}
yy204:
	yych = *++s;
	switch (yych) {
		case '0':
		case '1':
		case '2':
		case '3':
		case '4':
		case '5':
		case '6':
		case '7':
		case '8':
		case '9': goto yy225;
		default: goto yy176;
	}
yy205:
	++s;
#line 84 "re2c-scanner-m.re"
	{ return TOKEN_LE; }
#line 2560 "re2c-scanner-m.cc"
yy206:
	++s;
#line 87 "re2c-scanner-m.re"
	{ return TOKEN_DOUBLE_EQUAL; }
#line 2565 "re2c-scanner-m.cc"
yy207:
	++s;
#line 85 "re2c-scanner-m.re"
	{ return TOKEN_GE; }
#line 2570 "re2c-scanner-m.cc"
yy208:
	++s;
	if (lim <= s) return false;
	yych = *s;
	switch (yych) {
		case 0x80:
		case 0x81:
		case 0x82:
		case 0x83:
		case 0x84:
		case 0x85:
		case 0x86:
		case 0x87:
		case 0x88:
		case 0x89:
		case 0x8A:
		case 0x8B:
		case 0x8C:
		case 0x8D:
		case 0x8E:
		case 0x8F:
		case 0x90:
		case 0x91:
		case 0x92:
		case 0x93:
		case 0x94:
		case 0x95:
		case 0x96:
		case 0x97:
		case 0x98:
		case 0x99:
		case 0x9A:
		case 0x9B:
		case 0x9C:
		case 0x9D:
		case 0x9E:
		case 0x9F:
		case 0xA0:
		case 0xA1:
		case 0xA2:
		case 0xA3:
		case 0xA4:
		case 0xA5:
		case 0xA6:
		case 0xA7:
		case 0xA8:
		case 0xA9:
		case 0xAA:
		case 0xAB:
		case 0xAC:
		case 0xAD:
		case 0xAE:
		case 0xAF:
		case 0xB0:
		case 0xB1:
		case 0xB2:
		case 0xB3:
		case 0xB4:
		case 0xB5:
		case 0xB6:
		case 0xB7:
		case 0xB8:
		case 0xB9:
		case 0xBA:
		case 0xBB:
		case 0xBC:
		case 0xBD:
		case 0xBE:
		case 0xBF: goto yy156;
		default: goto yy176;
	}
yy209:
	++s;
	if (lim <= s) return false;
	yych = *s;
	switch (yych) {
		case 0x80:
		case 0x81:
		case 0x82:
		case 0x83:
		case 0x84:
		case 0x85:
		case 0x86:
		case 0x87:
		case 0x88:
		case 0x89:
		case 0x8A:
		case 0x8B:
		case 0x8C:
		case 0x8D:
		case 0x8E:
		case 0x8F:
		case 0x90:
		case 0x91:
		case 0x92:
		case 0x93:
		case 0x94:
		case 0x95:
		case 0x96:
		case 0x97:
		case 0x98:
		case 0x99:
		case 0x9A:
		case 0x9B:
		case 0x9C:
		case 0x9D:
		case 0x9E:
		case 0x9F:
		case 0xA0:
		case 0xA1:
		case 0xA2:
		case 0xA3:
		case 0xA4:
		case 0xA5:
		case 0xA6:
		case 0xA7:
		case 0xA8:
		case 0xA9:
		case 0xAA:
		case 0xAB:
		case 0xAC:
		case 0xAD:
		case 0xAE:
		case 0xAF:
		case 0xB0:
		case 0xB1:
		case 0xB2:
		case 0xB3:
		case 0xB4:
		case 0xB5:
		case 0xB6:
		case 0xB7:
		case 0xB8:
		case 0xB9:
		case 0xBA:
		case 0xBB:
		case 0xBC:
		case 0xBD:
		case 0xBE:
		case 0xBF: goto yy208;
		default: goto yy176;
	}
yy210:
	++s;
	if (lim <= s) return false;
	yych = *s;
	switch (yych) {
		case 0x80:
		case 0x81:
		case 0x82:
		case 0x83:
		case 0x84:
		case 0x85:
		case 0x86:
		case 0x87:
		case 0x88:
		case 0x89:
		case 0x8A:
		case 0x8B:
		case 0x8C:
		case 0x8D:
		case 0x8E:
		case 0x8F:
		case 0x90:
		case 0x91:
		case 0x92:
		case 0x93:
		case 0x94:
		case 0x95:
		case 0x96:
		case 0x97:
		case 0x98:
		case 0x99:
		case 0x9A:
		case 0x9B:
		case 0x9C:
		case 0x9D:
		case 0x9E:
		case 0x9F:
		case 0xA0:
		case 0xA1:
		case 0xA2:
		case 0xA3:
		case 0xA4:
		case 0xA5:
		case 0xA6:
		case 0xA7:
		case 0xA8:
		case 0xA9:
		case 0xAA:
		case 0xAB:
		case 0xAC:
		case 0xAD:
		case 0xAE:
		case 0xAF:
		case 0xB0:
		case 0xB1:
		case 0xB2:
		case 0xB3:
		case 0xB4:
		case 0xB5:
		case 0xB6:
		case 0xB7:
		case 0xB8:
		case 0xB9:
		case 0xBA:
		case 0xBB:
		case 0xBC:
		case 0xBD:
		case 0xBE:
		case 0xBF: goto yy209;
		default: goto yy176;
	}
yy211:
	++s;
#line 122 "re2c-scanner-m.re"
	{ return TOKEN_BACKSLASH_EQUAL; }
#line 2788 "re2c-scanner-m.cc"
yy212:
	++s;
#line 124 "re2c-scanner-m.re"
	{ return TOKEN_POW_EQUAL; }
#line 2793 "re2c-scanner-m.cc"
yy213:
	++s;
#line 102 "re2c-scanner-m.re"
	{ return TOKEN_DOUBLE_OR; }
#line 2798 "re2c-scanner-m.cc"
yy214:
	++s;
#line 89 "re2c-scanner-m.re"
	{ return TOKEN_NOT_EQUAL; }
#line 2803 "re2c-scanner-m.cc"
yy215:
	yyaccept = 6;
	m = ++s;
	if (lim <= s) return false;
	yych = *s;
	switch (yych) {
		case 0x00:
		case '\n': goto yy178;
		case '"': goto yy177;
		case '\\': goto yy179;
		default: goto yy174;
	}
yy216:
	++s;
#line 128 "re2c-scanner-m.re"
	{ return TOKEN_DOT_MULT_EQUAL; }
#line 2820 "re2c-scanner-m.cc"
yy217:
	++s;
	if (lim <= s) return false;
	yych = *s;
	switch (yych) {
		case '.': goto yy217;
		default: goto yy218;
	}
yy218:
#line 141 "re2c-scanner-m.re"
	{ return TOKEN_TRIPLE_DOT; }
#line 2832 "re2c-scanner-m.cc"
yy219:
	++s;
#line 126 "re2c-scanner-m.re"
	{ return TOKEN_DOT_DIV_EQUAL; }
#line 2837 "re2c-scanner-m.cc"
yy220:
	++s;
#line 127 "re2c-scanner-m.re"
	{ return TOKEN_DOT_BACKSLASH_EQUAL; }
#line 2842 "re2c-scanner-m.cc"
yy221:
	++s;
#line 129 "re2c-scanner-m.re"
	{ return TOKEN_DOT_POW_EQUAL; }
#line 2847 "re2c-scanner-m.cc"
yy222:
	++s;
	s -= 1;
	re2c_scanner_m_c = yycINITIAL;
#line 68 "re2c-scanner-m.re"
	{ return TOKEN_FLOAT; }
#line 2854 "re2c-scanner-m.cc"
yy223:
	yych = *++s;
	switch (yych) {
		case '0':
		case '1':
		case '2':
		case '3':
		case '4':
		case '5':
		case '6':
		case '7':
		case '8':
		case '9': goto yy224;
		default: goto yy176;
	}
yy224:
	++s;
	if (lim <= s) return false;
	yych = *s;
	switch (yych) {
		case '0':
		case '1':
		case '2':
		case '3':
		case '4':
		case '5':
		case '6':
		case '7':
		case '8':
		case '9': goto yy224;
		case 'F':
		case 'I':
		case 'L':
		case 'f':
		case 'i':
		case 'l': goto yy202;
		default: goto yy194;
	}
yy225:
	++s;
	if (lim <= s) return false;
	yych = *s;
	switch (yych) {
		case '0':
		case '1':
		case '2':
		case '3':
		case '4':
		case '5':
		case '6':
		case '7':
		case '8':
		case '9': goto yy225;
		case 'L':
		case 'U':
		case 'l':
		case 'u': goto yy203;
		default: goto yy143;
	}
}
#line 147 "re2c-scanner-m.re"

}

/* Local Variables: */
/* mode: c */
/* coding: latin-1 */
/* End: */
