/* Generated by re2c 1.1.1 on Fri Nov 16 20:12:58 2018 */
#line 1 "re2c-scanner-strings.re"
/*
This file is part of P2X.
Copyright © 2018 Johannes Willkomm
See the file p2x.cc for copying conditions.
*/

#include "token.ncd.enum.hh"
#include <string.h>

#define YYMAXFILL 4


typedef unsigned char uint8_t;

int re2c_scanner_strings_lex(const uint8_t *&s, const uint8_t *&m, uint8_t const * lim)
{

  

  lim += YYMAXFILL;

    
#line 26 "re2c-scanner-strings.cc"
{
	uint8_t yych;
	unsigned int yyaccept = 0;
	if ((lim - s) < 4) return false;
	yych = *s;
	switch (yych) {
	case 0x00:	goto yy2;
	case '\t':	goto yy6;
	case '\n':	goto yy8;
	case '\r':	goto yy10;
	case ' ':	goto yy12;
	case '!':	goto yy15;
	case '"':	goto yy17;
	case '#':	goto yy19;
	case '$':	goto yy21;
	case '%':	goto yy23;
	case '&':	goto yy25;
	case '\'':	goto yy27;
	case '(':	goto yy29;
	case ')':	goto yy31;
	case '*':	goto yy33;
	case '+':	goto yy35;
	case ',':	goto yy37;
	case '-':	goto yy39;
	case '.':	goto yy41;
	case '/':	goto yy43;
	case '0':	goto yy45;
	case '1':
	case '2':
	case '3':
	case '4':
	case '5':
	case '6':
	case '7':
	case '8':
	case '9':	goto yy47;
	case ':':	goto yy49;
	case ';':	goto yy51;
	case '<':	goto yy53;
	case '=':	goto yy55;
	case '>':	goto yy57;
	case '?':	goto yy59;
	case '@':	goto yy61;
	case 'A':
	case 'B':
	case 'C':
	case 'D':
	case 'E':
	case 'F':
	case 'G':
	case 'H':
	case 'I':
	case 'J':
	case 'K':
	case 'L':
	case 'M':
	case 'N':
	case 'O':
	case 'P':
	case 'Q':
	case 'R':
	case 'S':
	case 'T':
	case 'U':
	case 'V':
	case 'W':
	case 'X':
	case 'Y':
	case 'Z':
	case '_':
	case 'a':
	case 'b':
	case 'c':
	case 'd':
	case 'e':
	case 'f':
	case 'g':
	case 'h':
	case 'i':
	case 'j':
	case 'k':
	case 'l':
	case 'm':
	case 'n':
	case 'o':
	case 'p':
	case 'q':
	case 'r':
	case 's':
	case 't':
	case 'u':
	case 'v':
	case 'w':
	case 'x':
	case 'y':
	case 'z':	goto yy63;
	case '[':	goto yy66;
	case '\\':	goto yy68;
	case ']':	goto yy70;
	case '^':	goto yy72;
	case '{':	goto yy74;
	case '|':	goto yy76;
	case '}':	goto yy78;
	case '~':	goto yy80;
	case 0xB0:	goto yy82;
	case 0xC0:
	case 0xC1:
	case 0xC2:
	case 0xC3:
	case 0xC4:
	case 0xC5:
	case 0xC6:
	case 0xC7:
	case 0xC8:
	case 0xC9:
	case 0xCA:
	case 0xCB:
	case 0xCC:
	case 0xCD:
	case 0xCE:
	case 0xCF:
	case 0xD0:
	case 0xD1:
	case 0xD2:
	case 0xD3:
	case 0xD4:
	case 0xD5:
	case 0xD6:
	case 0xD7:
	case 0xD8:
	case 0xD9:
	case 0xDA:
	case 0xDB:
	case 0xDC:
	case 0xDD:
	case 0xDE:
	case 0xDF:	goto yy84;
	case 0xE0:
	case 0xE1:
	case 0xE2:
	case 0xE3:
	case 0xE4:
	case 0xE5:
	case 0xE6:
	case 0xE7:
	case 0xE8:
	case 0xE9:
	case 0xEA:
	case 0xEB:
	case 0xEC:
	case 0xED:
	case 0xEE:
	case 0xEF:	goto yy85;
	case 0xF0:
	case 0xF1:
	case 0xF2:
	case 0xF3:
	case 0xF4:
	case 0xF5:
	case 0xF6:
	case 0xF7:	goto yy86;
	default:	goto yy4;
	}
yy2:
	++s;
#line 100 "re2c-scanner-strings.re"
	{ return TOKEN_EOF; }
#line 194 "re2c-scanner-strings.cc"
yy4:
	++s;
yy5:
#line 102 "re2c-scanner-strings.re"
	{ return TOKEN_ILLEGAL_CHAR; }
#line 200 "re2c-scanner-strings.cc"
yy6:
	++s;
#line 56 "re2c-scanner-strings.re"
	{ return TOKEN_TAB; }
#line 205 "re2c-scanner-strings.cc"
yy8:
	++s;
#line 55 "re2c-scanner-strings.re"
	{ return TOKEN_NEWLINE; }
#line 210 "re2c-scanner-strings.cc"
yy10:
	++s;
#line 57 "re2c-scanner-strings.re"
	{ return TOKEN_CRETURN; }
#line 215 "re2c-scanner-strings.cc"
yy12:
	++s;
	if (lim <= s) return false;
	yych = *s;
	switch (yych) {
	case ' ':	goto yy12;
	default:	goto yy14;
	}
yy14:
#line 54 "re2c-scanner-strings.re"
	{ return TOKEN_SPACE; }
#line 227 "re2c-scanner-strings.cc"
yy15:
	++s;
#line 72 "re2c-scanner-strings.re"
	{ return TOKEN_EXCLAM; }
#line 232 "re2c-scanner-strings.cc"
yy17:
	yyaccept = 0;
	yych = *(m = ++s);
	switch (yych) {
	case 0x00:
	case '\n':	goto yy18;
	default:	goto yy88;
	}
yy18:
#line 93 "re2c-scanner-strings.re"
	{ return TOKEN_QUOTE; }
#line 244 "re2c-scanner-strings.cc"
yy19:
	++s;
#line 92 "re2c-scanner-strings.re"
	{ return TOKEN_HASH; }
#line 249 "re2c-scanner-strings.cc"
yy21:
	++s;
#line 90 "re2c-scanner-strings.re"
	{ return TOKEN_DOLLAR; }
#line 254 "re2c-scanner-strings.cc"
yy23:
	++s;
#line 87 "re2c-scanner-strings.re"
	{ return TOKEN_MOD; }
#line 259 "re2c-scanner-strings.cc"
yy25:
	++s;
#line 79 "re2c-scanner-strings.re"
	{ return TOKEN_AND; }
#line 264 "re2c-scanner-strings.cc"
yy27:
	yyaccept = 1;
	yych = *(m = ++s);
	switch (yych) {
	case 0x00:
	case '\n':	goto yy28;
	default:	goto yy93;
	}
yy28:
#line 94 "re2c-scanner-strings.re"
	{ return TOKEN_APOS; }
#line 276 "re2c-scanner-strings.cc"
yy29:
	++s;
#line 59 "re2c-scanner-strings.re"
	{ return TOKEN_L_PAREN; }
#line 281 "re2c-scanner-strings.cc"
yy31:
	++s;
#line 60 "re2c-scanner-strings.re"
	{ return TOKEN_R_PAREN; }
#line 286 "re2c-scanner-strings.cc"
yy33:
	yych = *++s;
	switch (yych) {
	case '/':	goto yy94;
	default:	goto yy34;
	}
yy34:
#line 86 "re2c-scanner-strings.re"
	{ return TOKEN_MULT; }
#line 296 "re2c-scanner-strings.cc"
yy35:
	++s;
#line 82 "re2c-scanner-strings.re"
	{ return TOKEN_PLUS; }
#line 301 "re2c-scanner-strings.cc"
yy37:
	++s;
#line 75 "re2c-scanner-strings.re"
	{ return TOKEN_COMMA; }
#line 306 "re2c-scanner-strings.cc"
yy39:
	++s;
#line 83 "re2c-scanner-strings.re"
	{ return TOKEN_MINUS; }
#line 311 "re2c-scanner-strings.cc"
yy41:
	yych = *++s;
	switch (yych) {
	case '0':
	case '1':
	case '2':
	case '3':
	case '4':
	case '5':
	case '6':
	case '7':
	case '8':
	case '9':	goto yy96;
	default:	goto yy42;
	}
yy42:
#line 77 "re2c-scanner-strings.re"
	{ return TOKEN_FULL_STOP; }
#line 330 "re2c-scanner-strings.cc"
yy43:
	yych = *++s;
	switch (yych) {
	case '*':	goto yy99;
	case '/':	goto yy101;
	default:	goto yy44;
	}
yy44:
#line 84 "re2c-scanner-strings.re"
	{ return TOKEN_DIV; }
#line 341 "re2c-scanner-strings.cc"
yy45:
	yyaccept = 2;
	yych = *(m = ++s);
	switch (yych) {
	case '.':	goto yy96;
	case '0':
	case '1':
	case '2':
	case '3':
	case '4':
	case '5':
	case '6':
	case '7':
	case '8':
	case '9':	goto yy47;
	case 'D':
	case 'E':
	case 'F':
	case 'd':
	case 'e':
	case 'f':	goto yy97;
	case 'L':
	case 'U':
	case 'l':
	case 'u':	goto yy105;
	case 'x':	goto yy107;
	default:	goto yy46;
	}
yy46:
#line 50 "re2c-scanner-strings.re"
	{ return TOKEN_INTEGER; }
#line 373 "re2c-scanner-strings.cc"
yy47:
	yyaccept = 2;
	m = ++s;
	if ((lim - s) < 3) return false;
	yych = *s;
	switch (yych) {
	case '.':	goto yy96;
	case '0':
	case '1':
	case '2':
	case '3':
	case '4':
	case '5':
	case '6':
	case '7':
	case '8':
	case '9':	goto yy47;
	case 'D':
	case 'E':
	case 'd':
	case 'e':	goto yy103;
	case 'F':
	case 'f':	goto yy104;
	case 'L':
	case 'U':
	case 'l':
	case 'u':	goto yy105;
	default:	goto yy46;
	}
yy49:
	++s;
#line 74 "re2c-scanner-strings.re"
	{ return TOKEN_COLON; }
#line 407 "re2c-scanner-strings.cc"
yy51:
	++s;
#line 76 "re2c-scanner-strings.re"
	{ return TOKEN_SEMICOLON; }
#line 412 "re2c-scanner-strings.cc"
yy53:
	++s;
#line 69 "re2c-scanner-strings.re"
	{ return TOKEN_LESS; }
#line 417 "re2c-scanner-strings.cc"
yy55:
	++s;
#line 68 "re2c-scanner-strings.re"
	{ return TOKEN_EQUAL; }
#line 422 "re2c-scanner-strings.cc"
yy57:
	++s;
#line 70 "re2c-scanner-strings.re"
	{ return TOKEN_GREATER; }
#line 427 "re2c-scanner-strings.cc"
yy59:
	++s;
#line 73 "re2c-scanner-strings.re"
	{ return TOKEN_QUESTION; }
#line 432 "re2c-scanner-strings.cc"
yy61:
	++s;
#line 78 "re2c-scanner-strings.re"
	{ return TOKEN_AT; }
#line 437 "re2c-scanner-strings.cc"
yy63:
	yyaccept = 3;
	m = ++s;
	if (lim <= s) return false;
	yych = *s;
	switch (yych) {
	case '0':
	case '1':
	case '2':
	case '3':
	case '4':
	case '5':
	case '6':
	case '7':
	case '8':
	case '9':
	case 'A':
	case 'B':
	case 'C':
	case 'D':
	case 'E':
	case 'F':
	case 'G':
	case 'H':
	case 'I':
	case 'J':
	case 'K':
	case 'L':
	case 'M':
	case 'N':
	case 'O':
	case 'P':
	case 'Q':
	case 'R':
	case 'S':
	case 'T':
	case 'U':
	case 'V':
	case 'W':
	case 'X':
	case 'Y':
	case 'Z':
	case '_':
	case 'a':
	case 'b':
	case 'c':
	case 'd':
	case 'e':
	case 'f':
	case 'g':
	case 'h':
	case 'i':
	case 'j':
	case 'k':
	case 'l':
	case 'm':
	case 'n':
	case 'o':
	case 'p':
	case 'q':
	case 'r':
	case 's':
	case 't':
	case 'u':
	case 'v':
	case 'w':
	case 'x':
	case 'y':
	case 'z':	goto yy63;
	case 0xC0:
	case 0xC1:
	case 0xC2:
	case 0xC3:
	case 0xC4:
	case 0xC5:
	case 0xC6:
	case 0xC7:
	case 0xC8:
	case 0xC9:
	case 0xCA:
	case 0xCB:
	case 0xCC:
	case 0xCD:
	case 0xCE:
	case 0xCF:
	case 0xD0:
	case 0xD1:
	case 0xD2:
	case 0xD3:
	case 0xD4:
	case 0xD5:
	case 0xD6:
	case 0xD7:
	case 0xD8:
	case 0xD9:
	case 0xDA:
	case 0xDB:
	case 0xDC:
	case 0xDD:
	case 0xDE:
	case 0xDF:	goto yy108;
	case 0xE0:
	case 0xE1:
	case 0xE2:
	case 0xE3:
	case 0xE4:
	case 0xE5:
	case 0xE6:
	case 0xE7:
	case 0xE8:
	case 0xE9:
	case 0xEA:
	case 0xEB:
	case 0xEC:
	case 0xED:
	case 0xEE:
	case 0xEF:	goto yy109;
	case 0xF0:
	case 0xF1:
	case 0xF2:
	case 0xF3:
	case 0xF4:
	case 0xF5:
	case 0xF6:
	case 0xF7:	goto yy110;
	default:	goto yy65;
	}
yy65:
#line 49 "re2c-scanner-strings.re"
	{ return TOKEN_IDENTIFIER; }
#line 568 "re2c-scanner-strings.cc"
yy66:
	++s;
#line 65 "re2c-scanner-strings.re"
	{ return TOKEN_L_BRACKET; }
#line 573 "re2c-scanner-strings.cc"
yy68:
	++s;
#line 85 "re2c-scanner-strings.re"
	{ return TOKEN_BACKSLASH; }
#line 578 "re2c-scanner-strings.cc"
yy70:
	++s;
#line 66 "re2c-scanner-strings.re"
	{ return TOKEN_R_BRACKET; }
#line 583 "re2c-scanner-strings.cc"
yy72:
	++s;
#line 88 "re2c-scanner-strings.re"
	{ return TOKEN_POW; }
#line 588 "re2c-scanner-strings.cc"
yy74:
	++s;
#line 62 "re2c-scanner-strings.re"
	{ return TOKEN_L_BRACE; }
#line 593 "re2c-scanner-strings.cc"
yy76:
	++s;
#line 80 "re2c-scanner-strings.re"
	{ return TOKEN_OR; }
#line 598 "re2c-scanner-strings.cc"
yy78:
	++s;
#line 63 "re2c-scanner-strings.re"
	{ return TOKEN_R_BRACE; }
#line 603 "re2c-scanner-strings.cc"
yy80:
	++s;
#line 71 "re2c-scanner-strings.re"
	{ return TOKEN_TILDE; }
#line 608 "re2c-scanner-strings.cc"
yy82:
	++s;
#line 91 "re2c-scanner-strings.re"
	{ return TOKEN_CIRC; }
#line 613 "re2c-scanner-strings.cc"
yy84:
	yych = *++s;
	switch (yych) {
	case 0x80:
	case 0x81:
	case 0x82:
	case 0x83:
	case 0x84:
	case 0x85:
	case 0x86:
	case 0x87:
	case 0x88:
	case 0x89:
	case 0x8A:
	case 0x8B:
	case 0x8C:
	case 0x8D:
	case 0x8E:
	case 0x8F:
	case 0x90:
	case 0x91:
	case 0x92:
	case 0x93:
	case 0x94:
	case 0x95:
	case 0x96:
	case 0x97:
	case 0x98:
	case 0x99:
	case 0x9A:
	case 0x9B:
	case 0x9C:
	case 0x9D:
	case 0x9E:
	case 0x9F:
	case 0xA0:
	case 0xA1:
	case 0xA2:
	case 0xA3:
	case 0xA4:
	case 0xA5:
	case 0xA6:
	case 0xA7:
	case 0xA8:
	case 0xA9:
	case 0xAA:
	case 0xAB:
	case 0xAC:
	case 0xAD:
	case 0xAE:
	case 0xAF:
	case 0xB0:
	case 0xB1:
	case 0xB2:
	case 0xB3:
	case 0xB4:
	case 0xB5:
	case 0xB6:
	case 0xB7:
	case 0xB8:
	case 0xB9:
	case 0xBA:
	case 0xBB:
	case 0xBC:
	case 0xBD:
	case 0xBE:
	case 0xBF:	goto yy63;
	default:	goto yy5;
	}
yy85:
	yyaccept = 4;
	yych = *(m = ++s);
	switch (yych) {
	case 0x80:
	case 0x81:
	case 0x82:
	case 0x83:
	case 0x84:
	case 0x85:
	case 0x86:
	case 0x87:
	case 0x88:
	case 0x89:
	case 0x8A:
	case 0x8B:
	case 0x8C:
	case 0x8D:
	case 0x8E:
	case 0x8F:
	case 0x90:
	case 0x91:
	case 0x92:
	case 0x93:
	case 0x94:
	case 0x95:
	case 0x96:
	case 0x97:
	case 0x98:
	case 0x99:
	case 0x9A:
	case 0x9B:
	case 0x9C:
	case 0x9D:
	case 0x9E:
	case 0x9F:
	case 0xA0:
	case 0xA1:
	case 0xA2:
	case 0xA3:
	case 0xA4:
	case 0xA5:
	case 0xA6:
	case 0xA7:
	case 0xA8:
	case 0xA9:
	case 0xAA:
	case 0xAB:
	case 0xAC:
	case 0xAD:
	case 0xAE:
	case 0xAF:
	case 0xB0:
	case 0xB1:
	case 0xB2:
	case 0xB3:
	case 0xB4:
	case 0xB5:
	case 0xB6:
	case 0xB7:
	case 0xB8:
	case 0xB9:
	case 0xBA:
	case 0xBB:
	case 0xBC:
	case 0xBD:
	case 0xBE:
	case 0xBF:	goto yy108;
	default:	goto yy5;
	}
yy86:
	yyaccept = 4;
	yych = *(m = ++s);
	switch (yych) {
	case 0x80:
	case 0x81:
	case 0x82:
	case 0x83:
	case 0x84:
	case 0x85:
	case 0x86:
	case 0x87:
	case 0x88:
	case 0x89:
	case 0x8A:
	case 0x8B:
	case 0x8C:
	case 0x8D:
	case 0x8E:
	case 0x8F:
	case 0x90:
	case 0x91:
	case 0x92:
	case 0x93:
	case 0x94:
	case 0x95:
	case 0x96:
	case 0x97:
	case 0x98:
	case 0x99:
	case 0x9A:
	case 0x9B:
	case 0x9C:
	case 0x9D:
	case 0x9E:
	case 0x9F:
	case 0xA0:
	case 0xA1:
	case 0xA2:
	case 0xA3:
	case 0xA4:
	case 0xA5:
	case 0xA6:
	case 0xA7:
	case 0xA8:
	case 0xA9:
	case 0xAA:
	case 0xAB:
	case 0xAC:
	case 0xAD:
	case 0xAE:
	case 0xAF:
	case 0xB0:
	case 0xB1:
	case 0xB2:
	case 0xB3:
	case 0xB4:
	case 0xB5:
	case 0xB6:
	case 0xB7:
	case 0xB8:
	case 0xB9:
	case 0xBA:
	case 0xBB:
	case 0xBC:
	case 0xBD:
	case 0xBE:
	case 0xBF:	goto yy109;
	default:	goto yy5;
	}
yy87:
	++s;
	if (lim <= s) return false;
	yych = *s;
yy88:
	switch (yych) {
	case 0x00:
	case '\n':	goto yy89;
	case '"':	goto yy90;
	default:	goto yy87;
	}
yy89:
	s = m;
	switch (yyaccept) {
	case 0: 	goto yy18;
	case 1: 	goto yy28;
	case 2: 	goto yy46;
	case 3: 	goto yy65;
	case 4: 	goto yy5;
	default:	goto yy98;
	}
yy90:
	++s;
#line 52 "re2c-scanner-strings.re"
	{ return TOKEN_STRING; }
#line 848 "re2c-scanner-strings.cc"
yy92:
	++s;
	if (lim <= s) return false;
	yych = *s;
yy93:
	switch (yych) {
	case 0x00:
	case '\n':	goto yy89;
	case '\'':	goto yy90;
	default:	goto yy92;
	}
yy94:
	++s;
#line 98 "re2c-scanner-strings.re"
	{ return TOKEN_C_COMMENT_END; }
#line 864 "re2c-scanner-strings.cc"
yy96:
	yyaccept = 5;
	m = ++s;
	if ((lim - s) < 3) return false;
	yych = *s;
yy97:
	switch (yych) {
	case '0':
	case '1':
	case '2':
	case '3':
	case '4':
	case '5':
	case '6':
	case '7':
	case '8':
	case '9':	goto yy96;
	case 'D':
	case 'E':
	case 'd':
	case 'e':	goto yy103;
	case 'F':
	case 'L':
	case 'f':
	case 'l':	goto yy104;
	default:	goto yy98;
	}
yy98:
#line 51 "re2c-scanner-strings.re"
	{ return TOKEN_FLOAT; }
#line 895 "re2c-scanner-strings.cc"
yy99:
	++s;
#line 97 "re2c-scanner-strings.re"
	{ return TOKEN_C_COMMENT_START; }
#line 900 "re2c-scanner-strings.cc"
yy101:
	++s;
#line 96 "re2c-scanner-strings.re"
	{ return TOKEN_DOUBLE_DIV; }
#line 905 "re2c-scanner-strings.cc"
yy103:
	yych = *++s;
	switch (yych) {
	case '+':
	case '-':	goto yy111;
	case '0':
	case '1':
	case '2':
	case '3':
	case '4':
	case '5':
	case '6':
	case '7':
	case '8':
	case '9':	goto yy112;
	default:	goto yy89;
	}
yy104:
	++s;
	goto yy98;
yy105:
	++s;
	if (lim <= s) return false;
	yych = *s;
	switch (yych) {
	case 'L':
	case 'U':
	case 'l':
	case 'u':	goto yy105;
	default:	goto yy46;
	}
yy107:
	yych = *++s;
	switch (yych) {
	case '0':
	case '1':
	case '2':
	case '3':
	case '4':
	case '5':
	case '6':
	case '7':
	case '8':
	case '9':	goto yy114;
	default:	goto yy89;
	}
yy108:
	++s;
	if (lim <= s) return false;
	yych = *s;
	switch (yych) {
	case 0x80:
	case 0x81:
	case 0x82:
	case 0x83:
	case 0x84:
	case 0x85:
	case 0x86:
	case 0x87:
	case 0x88:
	case 0x89:
	case 0x8A:
	case 0x8B:
	case 0x8C:
	case 0x8D:
	case 0x8E:
	case 0x8F:
	case 0x90:
	case 0x91:
	case 0x92:
	case 0x93:
	case 0x94:
	case 0x95:
	case 0x96:
	case 0x97:
	case 0x98:
	case 0x99:
	case 0x9A:
	case 0x9B:
	case 0x9C:
	case 0x9D:
	case 0x9E:
	case 0x9F:
	case 0xA0:
	case 0xA1:
	case 0xA2:
	case 0xA3:
	case 0xA4:
	case 0xA5:
	case 0xA6:
	case 0xA7:
	case 0xA8:
	case 0xA9:
	case 0xAA:
	case 0xAB:
	case 0xAC:
	case 0xAD:
	case 0xAE:
	case 0xAF:
	case 0xB0:
	case 0xB1:
	case 0xB2:
	case 0xB3:
	case 0xB4:
	case 0xB5:
	case 0xB6:
	case 0xB7:
	case 0xB8:
	case 0xB9:
	case 0xBA:
	case 0xBB:
	case 0xBC:
	case 0xBD:
	case 0xBE:
	case 0xBF:	goto yy63;
	default:	goto yy89;
	}
yy109:
	++s;
	if (lim <= s) return false;
	yych = *s;
	switch (yych) {
	case 0x80:
	case 0x81:
	case 0x82:
	case 0x83:
	case 0x84:
	case 0x85:
	case 0x86:
	case 0x87:
	case 0x88:
	case 0x89:
	case 0x8A:
	case 0x8B:
	case 0x8C:
	case 0x8D:
	case 0x8E:
	case 0x8F:
	case 0x90:
	case 0x91:
	case 0x92:
	case 0x93:
	case 0x94:
	case 0x95:
	case 0x96:
	case 0x97:
	case 0x98:
	case 0x99:
	case 0x9A:
	case 0x9B:
	case 0x9C:
	case 0x9D:
	case 0x9E:
	case 0x9F:
	case 0xA0:
	case 0xA1:
	case 0xA2:
	case 0xA3:
	case 0xA4:
	case 0xA5:
	case 0xA6:
	case 0xA7:
	case 0xA8:
	case 0xA9:
	case 0xAA:
	case 0xAB:
	case 0xAC:
	case 0xAD:
	case 0xAE:
	case 0xAF:
	case 0xB0:
	case 0xB1:
	case 0xB2:
	case 0xB3:
	case 0xB4:
	case 0xB5:
	case 0xB6:
	case 0xB7:
	case 0xB8:
	case 0xB9:
	case 0xBA:
	case 0xBB:
	case 0xBC:
	case 0xBD:
	case 0xBE:
	case 0xBF:	goto yy108;
	default:	goto yy89;
	}
yy110:
	++s;
	if (lim <= s) return false;
	yych = *s;
	switch (yych) {
	case 0x80:
	case 0x81:
	case 0x82:
	case 0x83:
	case 0x84:
	case 0x85:
	case 0x86:
	case 0x87:
	case 0x88:
	case 0x89:
	case 0x8A:
	case 0x8B:
	case 0x8C:
	case 0x8D:
	case 0x8E:
	case 0x8F:
	case 0x90:
	case 0x91:
	case 0x92:
	case 0x93:
	case 0x94:
	case 0x95:
	case 0x96:
	case 0x97:
	case 0x98:
	case 0x99:
	case 0x9A:
	case 0x9B:
	case 0x9C:
	case 0x9D:
	case 0x9E:
	case 0x9F:
	case 0xA0:
	case 0xA1:
	case 0xA2:
	case 0xA3:
	case 0xA4:
	case 0xA5:
	case 0xA6:
	case 0xA7:
	case 0xA8:
	case 0xA9:
	case 0xAA:
	case 0xAB:
	case 0xAC:
	case 0xAD:
	case 0xAE:
	case 0xAF:
	case 0xB0:
	case 0xB1:
	case 0xB2:
	case 0xB3:
	case 0xB4:
	case 0xB5:
	case 0xB6:
	case 0xB7:
	case 0xB8:
	case 0xB9:
	case 0xBA:
	case 0xBB:
	case 0xBC:
	case 0xBD:
	case 0xBE:
	case 0xBF:	goto yy109;
	default:	goto yy89;
	}
yy111:
	yych = *++s;
	switch (yych) {
	case '0':
	case '1':
	case '2':
	case '3':
	case '4':
	case '5':
	case '6':
	case '7':
	case '8':
	case '9':	goto yy112;
	default:	goto yy89;
	}
yy112:
	++s;
	if (lim <= s) return false;
	yych = *s;
	switch (yych) {
	case '0':
	case '1':
	case '2':
	case '3':
	case '4':
	case '5':
	case '6':
	case '7':
	case '8':
	case '9':	goto yy112;
	case 'F':
	case 'L':
	case 'f':
	case 'l':	goto yy104;
	default:	goto yy98;
	}
yy114:
	++s;
	if (lim <= s) return false;
	yych = *s;
	switch (yych) {
	case '0':
	case '1':
	case '2':
	case '3':
	case '4':
	case '5':
	case '6':
	case '7':
	case '8':
	case '9':	goto yy114;
	case 'L':
	case 'U':
	case 'l':
	case 'u':	goto yy105;
	default:	goto yy46;
	}
}
#line 104 "re2c-scanner-strings.re"

}

/* Local Variables: */
/* mode: c */
/* coding: latin-1 */
/* End: */
