// -*- c++ -*- 
// This file has been automatically generated by
// gennc.sh 47
// from definition file xml/scanners.ncd.xml.

#include <string>
#include <cstring>
#include <iostream>
#include <cstdlib>
#include <stdio.h>
#include <stdint.h>
#include <stddef.h>


#define ScannerType__prefixLen 8


typedef uint8_t ScannerType_IndexT;



static int ScannerType__compnames(const void *m1, const void *m2) {
  char const * const * mi1 = (char const * const *) m1;
  char const * const * mi2 = (char const * const *) m2;
  return strcasecmp(*mi1, *mi2);
}

static  char const* const ScannerType__names[ScannerType__numItems + 1] = {
  "C", "FLEX_C", "FLEX_M", "FLEX_NO_STRINGS", "FLEX_R", "FLEX_STRINGS", "M", "NONE", "NO_STRINGS", "R",
  "RE2C_C", "RE2C_M", "RE2C_R", "RE2C_STRINGS", "STRINGS"
};

static ScannerType_IndexT const ScannerType__indexNames[ScannerType__numItems] = {
  5, 10, 9, 7, 8, 6, 4, 0, 2, 3,
  14, 13, 12, 11, 1
};

static ScannerType_IndexT const ScannerType__invNames[ScannerType__numItems + 1] = {
  7, 14, 8, 9, 6, 0, 5, 3, 4, 2,
  1, 13, 12, 11, 10, ScannerType__numItems
};

size_t ScannerType_getLength() {
  return ScannerType__numItems;
}

char const* ScannerType_getPrefix() {
  return ScannerType__prefix;
}

ScannerType_T ScannerType_getIthCode(int i) {
  if (i >= 0 && i < ScannerType__numItems) {

    return (ScannerType_T) i;

  }
  return (ScannerType_T) -1;
}

char const* ScannerType_getIthName(int i) {
  if (i >= 0 && i < ScannerType__numItems) {
    return ScannerType__names[ScannerType__invNames[i]];
  }
  return 0;
}

char const* ScannerType_getIthComment(int) {

  return 0;
}

int ScannerType_isCode(ScannerType_T n) {
  return ScannerType_getName(n) != 0;
}

static ScannerType_IndexT ScannerType__getCodeIndex(ScannerType_T code) {
  if ((unsigned) code < ScannerType__numItems) return code;
  return ScannerType__numItems;
}

char const *ScannerType_getName(ScannerType_T code) {
  return ScannerType__names[ScannerType__invNames[ScannerType__getCodeIndex(code)]];
}

ScannerType_T ScannerType_getCode(char const *name, int* res) {
  char const* const* found = (char const* const*)  bsearch(&name, ScannerType__names, ScannerType__numItems, sizeof(char const*), &ScannerType__compnames);
  if (res) *res = found == 0;
  if (found) {
    ScannerType_IndexT n = found - ScannerType__names;
    return (ScannerType_T) ScannerType__indexNames[n];
  }
  return (ScannerType_T) -1;
}

ScannerType_T ScannerType_getCodeFullName(char const *name, int* res) {
  return ScannerType_getCode(name + ScannerType__prefixLen, res);
}

char const *ScannerType_getComment(ScannerType_T) {

  return 0;

}


char const *getScannerTypeName(ScannerType_T c) {
  return ScannerType_getName(c);
}

char const *getScannerTypeComment(ScannerType_T c) {
  return ScannerType_getComment(c);
}

ScannerType_T getScannerTypeValue(char const *name, int *res) {
   if (strncasecmp(name, ScannerType__prefix, ScannerType__prefixLen) == 0) {
     return ScannerType_getCodeFullName(name, res);
   } else {
     return ScannerType_getCode(name, res);
   }
}

size_t getNumScannerType() {
  return ScannerType_getLength();
}

ScannerType_T getScannerType(int which) {
  return ScannerType_getIthCode(which);
}

