// -*- c++ -*- 
// This file has been automatically generated by
// gennc.sh 47
// from definition file xml/scanners.ncd.xml.
#ifndef gennc_funcScannerType__hh
#define gennc_funcScannerType__hh


    #include <stddef.h>
    #include <stdint.h>

    #define ScannerType__numItems 15
    #define ScannerType__prefix "SCANNER_"
    typedef ScannerType ScannerType_T;


    size_t ScannerType_getLength();
    char const *ScannerType_getPrefix();

    ScannerType_T ScannerType_getIthCode(int i);
    char const* ScannerType_getIthName(int i);
    char const* ScannerType_getIthComment(int i);

    char const *ScannerType_getName(ScannerType_T c);
    char const *ScannerType_getComment(ScannerType_T c);
    ScannerType_T ScannerType_getCode(char const *name, int *res = 0);
    ScannerType_T ScannerType_getCodeFullName(char const *name, int *res = 0);

    // backward compat
    char const *getScannerTypeName(ScannerType_T c);
    char const *getScannerTypeComment(ScannerType_T c);
    ScannerType_T getScannerTypeValue(char const *name, int *res = 0);

    inline ScannerType getScannerTypeValue(std::string const &t, int *res = 0) {
       return getScannerTypeValue(t.c_str(), res);
    }

    size_t getNumScannerType();
    ScannerType_T getScannerType(int which);
    
    inline std::ostream &operator << (std::ostream &out, ScannerType t) {
       out << getScannerTypeName(t);
       return out;
    }
    #endif

