// -*- c++ -*- 
// This file has been automatically generated by 
// gennc.sh $Id: gennc.xsl 31 2013-11-07 18:56:43Z jwillkomm $ 
// from definition file xml/scanners.ncd.xml. Class mode is false.
#ifndef gennc_enumScannerType__hh
#define gennc_enumScannerType__hh

    enum ScannerType {
       /**  */ 
SCANNER_NONE = 0, 
 /**  */ 
SCANNER_STRINGS, 
 /**  */ 
SCANNER_NO_STRINGS, 
 /**  */ 
SCANNER_R, 
 /**  */ 
SCANNER_C
 
    };
  #endif

