// -*- c++ -*- 
// This file has been automatically generated by
// gennc.sh $Id: gennc.xsl 110 2018-10-09 15:02:12Z jwillkomm $
// from definition file xml/scanners.ncd.xml. Class mode is false.
#ifndef gennc_enumScannerType__hh
#define gennc_enumScannerType__hh

    enum ScannerType {
SCANNER_NONE = 0,
SCANNER_STRINGS,
SCANNER_NO_STRINGS,
SCANNER_R,
SCANNER_M,
SCANNER_C,
SCANNER_FLEX_STRINGS,
SCANNER_FLEX_NO_STRINGS,
SCANNER_FLEX_R,
SCANNER_FLEX_M,
SCANNER_FLEX_C,
SCANNER_RE2C_STRINGS,
SCANNER_RE2C_R,
SCANNER_RE2C_M,
SCANNER_RE2C_C
    };
  #endif

