// -*- c++ -*- 
// This file has been automatically generated by 
// gennc.sh $Id: gennc.xsl 50 2015-04-08 12:45:49Z jwillkomm $ 
// from definition file xml/scanners.ncd.xml. Class mode is false.
#ifndef gennc_enumScannerType__hh
#define gennc_enumScannerType__hh

    enum ScannerType {
SCANNER_NONE = 0, 
SCANNER_STRINGS, 
SCANNER_NO_STRINGS, 
SCANNER_R, 
SCANNER_C
    };
  #endif

