// -*- c++ -*- 
// This file has been automatically generated by 
// gennc.sh $Id: gennc.xsl 50 2015-04-08 12:45:49Z jwillkomm $ 
// from definition file xml/token.ncd.xml. Class mode is true.
#ifndef gennc_funcParserToken__hh
#define gennc_funcParserToken__hh


//! modified by hand!
// -    inline std::ostream &operator << (std::ostream &out, Token::ParserToken t) {
// +    inline std::ostream &operator << (std::ostream &out, ParserToken t) {
    inline std::ostream &operator << (std::ostream &out, ParserToken t) {
       out << Token::getParserTokenName(t);
       return out;
    }
    #endif

